In [3]:
from NN_model_helper import (evaluate_fold_TL, set_freeze_mode, plot_training_progress, find_optimal_clusters)
from pathlib import Path
import sys
import pandas as pd
from sklearn.model_selection import StratifiedKFold
import numpy as np
from NN_model import ImprovedNN

/opt/anaconda3/envs/Surabie_S_clean_v2/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [5]:
# classifier/ → MELTING_POINT_2026/
PROJECT_ROOT = Path.cwd().parent        # directory above a path: .../MELTING_POINT_2026

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

train_path = PROJECT_ROOT / "Ro5" / "artifacts" / "train_scaled_bRo5_no_interaction.parquet"
df_bro5 = pd.read_parquet(train_path)

df_bro5.head()

,SMILES,MP,Type,Ro5,RDKit_SMR_VSA2,RDKit_Kappa2,MACCS_41,RDKit_SMR_VSA6,RDKit_SlogP_VSA5,RDKit_VSA_EState7,...,RDKit_fr_Ar_NH,RDKit_Chi4n,RDKit_PEOE_VSA12,RDKit_NumAliphaticRings,MACCS_101,RDKit_TPSA,RDKit_fr_ArN,RDKit_fr_SH,RDKit_NumHeteroatoms,Structure_Cluster
0,N#C/C(=C\c1ccc(cc1)F)/c1nc(c(s1)/N=N/c1c(Br)cc...,171.0,Train,0,3.123529,1.247300,4.045846,-0.670027,-0.165698,0.013278,...,-0.199183,0.164267,-0.434742,-0.504875,-0.618592,0.272086,-0.268728,-0.07374,1.667578,1
1,OC[C@H]1O[C@]([C@H]([C@@H]1O[C@@H]1O[C@H](CO)[...,175.5,Train,0,-0.239453,0.642113,-0.247167,1.468448,-0.815794,-2.818361,...,-0.199183,0.424527,1.124470,1.393072,-0.618592,3.929674,-0.268728,-0.07374,2.393770,0
2,BrC(CC1(C(=O)C2(C(C1CC2)(C)C)C)C1(CC(Cc2ccccc2...,215.0,Train,0,-0.239453,1.538568,-0.247167,-0.670027,2.829153,1.123928,...,-0.199183,5.565415,-0.434742,3.291019,-0.618592,-0.506076,-0.268728,-0.07374,-0.147901,1
3,Clc1nc(Oc2cc(cc(c2)Oc2nc(Cl)nc(n2)Cl)Oc2nc(Cl)...,240.0,Train,0,-0.239453,1.535102,-0.247167,-0.670027,-0.815794,-0.326855,...,-0.199183,0.112650,8.106551,-0.504875,-0.618592,2.621414,-0.268728,-0.07374,4.935441,1
4,CC(=O)OCC12OC1C(C1C2C(OC=C1)OC1OC(COC(=O)C)C(C...,135.0,Train,0,-0.239453,3.238981,-0.247167,0.755623,1.258615,-1.863942,...,-0.199183,2.794469,2.954683,3.291019,1.616573,4.922787,-0.268728,-0.07374,4.935441,4

In [6]:
TARGET_COL = "MP"

exclude = {"SMILES", TARGET_COL, "Type", "Ro5", "Structure_Cluster"}
num_cols = df_bro5.select_dtypes(include=[np.number]).columns
feature_cols = [c for c in num_cols if c not in exclude]

X = df_bro5[feature_cols].to_numpy(np.float32) 
y = df_bro5[TARGET_COL].to_numpy(np.float32)
y_strat = df_bro5["Structure_Cluster"].astype(str).to_numpy()

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=10)
folds = [(tr, va) for tr, va in skf.split(X, y_strat)]

print("Total samples:", len(X))
print("Num features:", X.shape[1])
print("Num folds:", len(folds))
print()

for i, (tr_idx, va_idx) in enumerate(folds):
    print(
        f"Fold {i:2d} | "
        f"Train: {len(tr_idx):4d} | "
        f"Val: {len(va_idx):4d}"
    )

BASELINE_CKPT = Path("artifacts/Ro5_best_models_no_interaction/Ro5_best_fold_0.pt")

Total samples: 257
Num features: 101
Num folds: 10

Fold  0 | Train:  231 | Val:   26
Fold  1 | Train:  231 | Val:   26
Fold  2 | Train:  231 | Val:   26
Fold  3 | Train:  231 | Val:   26
Fold  4 | Train:  231 | Val:   26
Fold  5 | Train:  231 | Val:   26
Fold  6 | Train:  231 | Val:   26
Fold  7 | Train:  232 | Val:   25
Fold  8 | Train:  232 | Val:   25
Fold  9 | Train:  232 | Val:   25

/opt/anaconda3/envs/Surabie_S_clean_v2/lib/python3.11/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 7 members, which is less than n_splits=10.
  warnings.warn(

In [7]:
from pathlib import Path
import json, joblib, numpy as np, pandas as pd, torch, optuna

# --- scenarios: name, vector (for your notes), freeze_level used by evaluate_fold_TL ---

HIDDEN_LAYERS = [192,96,48]   # must match baseline arch
N_TRIALS      = 20

OUT_ROOT = Path("artifacts/TL_Ro5_no_interaction")   # under the artifacts folder
OUT_ROOT.mkdir(parents=True, exist_ok=True)

def run_one_scenario(tag, freeze_vec, freeze_level):
    print(f"\n=== Scenario: {tag} | freeze={freeze_vec} (level={freeze_level}) ===")
    SCEN_OUT = OUT_ROOT / tag
    (SCEN_OUT / "trials").mkdir(parents=True, exist_ok=True)

    def objective_tl_fixed(trial):
        # fixed freeze level; tune the rest
        learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-3, log=True)
        weight_decay  = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
        batch_size    = trial.suggest_categorical("batch_size", [16, 32, 64])
        dropout_rate  = trial.suggest_float("dropout_rate", 0.2, 0.5)

        trial_dir = SCEN_OUT / "trials" / f"trial_{trial.number:04d}"
        trial_dir.mkdir(parents=True, exist_ok=True)

        fold_metrics, rmses = [], []
        for fold_idx, (tr_idx, va_idx) in enumerate(folds):
            X_tr, y_tr = X[tr_idx], y[tr_idx]
            X_va, y_va = X[va_idx], y[va_idx]

            rmse, r2, q2, model, *_ = evaluate_fold_TL(
                trial=trial,
                fold_idx=fold_idx,
                X_train_scaled=X_tr, y_train=y_tr,
                X_val_scaled=X_va,   y_val=y_va,
                hidden_layers=HIDDEN_LAYERS, dropout_rate=dropout_rate,
                learning_rate=learning_rate, weight_decay=weight_decay,
                batch_size=batch_size, freeze_level=freeze_level,
                baseline_ckpt=BASELINE_CKPT,
                max_epochs=10**6, patience=30, min_delta=0.0,
                save_checkpoints=False
            )

            ckpt_path = trial_dir / f"fold_{fold_idx}_best.pth"
            torch.save(model.state_dict(), ckpt_path)

            fold_metrics.append({
                "fold": fold_idx,
                "rmse": float(rmse),
                "r2":   float(r2),
                "q2":   float(q2),
                "checkpoint": str(ckpt_path)
            })
            rmses.append(rmse)

        summary = {
            "scenario": tag,
            "freeze_vector": freeze_vec,
            "freeze_level": freeze_level,
            "trial_number": trial.number,
            "params": {
                "learning_rate": learning_rate,
                "weight_decay":  weight_decay,
                "batch_size":    batch_size,
                "dropout_rate":  dropout_rate,
                "hidden_layers": HIDDEN_LAYERS
            },
            "avg_rmse": float(np.mean(rmses)),
            "folds":    fold_metrics
        }
        with open(trial_dir / "summary.json", "w") as f:
            json.dump(summary, f, indent=2)

        return float(np.mean(rmses))

    # -- HPO
    study = optuna.create_study(direction="minimize")
    study.optimize(objective_tl_fixed, n_trials=N_TRIALS, gc_after_trial=True)

    # save study artifacts
    joblib.dump(study, SCEN_OUT / "study.joblib")
    study.trials_dataframe().to_csv(SCEN_OUT / "trials.csv", index=False)
    with open(SCEN_OUT / "best_params.json","w") as f:
        json.dump(study.best_params, f, indent=2)
    with open(SCEN_OUT / "best_value.txt","w") as f:
        f.write(f"{study.best_value:.6f}\n")
    print(f"[{tag}] Best avg RMSE: {study.best_value:.4f}")
    print(f"[{tag}] Best params:  {study.best_params}")

    # -- Final per-fold retrain with best params (to produce clean fold models + metrics)
    best = study.best_params
    FINAL_DIR = SCEN_OUT / "final_fold_models"
    FINAL_DIR.mkdir(parents=True, exist_ok=True)

    rows = []
    for fold_idx, (tr_idx, va_idx) in enumerate(folds):
        X_tr, y_tr = X[tr_idx], y[tr_idx]
        X_va, y_va = X[va_idx], y[va_idx]

        rmse, r2, q2, model, *_ = evaluate_fold_TL(
            trial=None,
            fold_idx=fold_idx,
            X_train_scaled=X_tr, y_train=y_tr,
            X_val_scaled=X_va,   y_val=y_va,
            hidden_layers=HIDDEN_LAYERS,
            dropout_rate=best["dropout_rate"],
            learning_rate=best["learning_rate"],
            weight_decay=best["weight_decay"],
            batch_size=best["batch_size"],
            freeze_level=freeze_level,
            baseline_ckpt=BASELINE_CKPT,
            max_epochs=10**6, patience=30, min_delta=0.0,
            save_checkpoints=False
        )

        ckpt = FINAL_DIR / f"fold_{fold_idx}_best.pth"
        torch.save(model.state_dict(), ckpt)
        rows.append({"fold": fold_idx, "rmse": float(rmse), "r2": float(r2), "q2": float(q2), "checkpoint": str(ckpt)})

    cv_df = pd.DataFrame(rows).sort_values("rmse").reset_index(drop=True)
    cv_df.to_csv(SCEN_OUT / "cv_final_metrics.csv", index=False)

    best_row = cv_df.iloc[0]
    manifest = {
        "scenario": tag,
        "freeze_vector": freeze_vec,
        "freeze_level": freeze_level,
        "best_fold": int(best_row["fold"]),
        "checkpoint": best_row["checkpoint"],
        "hidden_layers": HIDDEN_LAYERS,
        "best_params": best
    }
    with open(SCEN_OUT / "manifest.json","w") as f:
        json.dump(manifest, f, indent=2)

    print(f"[{tag}] Best fold: {manifest['best_fold']} → {manifest['checkpoint']}")
    return study, cv_df, manifest


# ---------- RUN ALL THREE ----------
SCENARIOS = [
    ("no_freeze",        [0,0,0], 0),
    ("freeze_fc1",       [1,0,0], 1),
    ("freeze_fc1_fc2",   [1,1,0], 2),
]

results = {}
for tag, vec, lvl in SCENARIOS:
    study, cv_df, manifest = run_one_scenario(tag, vec, lvl)
    results[tag] = {"best": study.best_value, "manifest": manifest}
print("\nSummary:", json.dumps(results, indent=2))

[I 2026-02-09 21:46:21,710] A new study created in memory with name: no-name-84a04517-64e3-4ca0-9d81-5e2ff4641cf3

=== Scenario: no_freeze | freeze=[0, 0, 0] (level=0) ===
Fold 0: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch    1 | Train 70.6022 | Val 50.7976 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 50.7976)
Fold 1: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 66.3686 | Val 56.9202 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.9202)
Fold 2: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 72.1616 | Val 45.7723 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.7723)
Fold 3: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.7016 | Val 59.9306 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 59.9306)
Fold 4: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 68.4873 | Val 54.6576 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 54.6576)
Fold 5: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 67.4571 | Val 59.0470 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 59.0470)
Fold 6: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 69.8044 | Val 37.2856 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 37.2856)
Fold 7: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 66.3979 | Val 73.1160 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 73.1160)
Fold 8: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.5481 | Val 46.4641 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.4641)
Fold 9: TL on cpu | freeze=0 | lr=1.89448e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 69.9763 | Val 31.6209 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:46:24,629] Trial 0 finished with value: 51.56119804382324 and parameters: {'learning_rate': 1.894480481281034e-05, 'weight_decay': 1.0704051988086485e-06, 'batch_size': 32, 'dropout_rate': 0.20927726499447136}. Best is trial 0 with value: 51.56119804382324.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.6209)
Fold 0: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 68.3160 | Val 52.4399 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 52.4399)
Fold 1: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 71.6106 | Val 57.3280 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.3280)
Fold 2: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 73.1278 | Val 45.0350 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.0350)
Fold 3: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.9877 | Val 60.1943 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.1943)
Fold 4: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 69.2698 | Val 55.0885 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 55.0885)
Fold 5: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.0975 | Val 60.1436 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 60.1436)
Fold 6: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 71.2062 | Val 36.6971 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.6971)
Fold 7: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 68.4686 | Val 75.2123 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 75.2123)
Fold 8: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.5424 | Val 46.1332 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.1332)
Fold 9: TL on cpu | freeze=0 | lr=0.00014287
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 67.9207 | Val 31.6637 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:46:27,065] Trial 1 finished with value: 51.99355602264404 and parameters: {'learning_rate': 0.00014287013629684232, 'weight_decay': 1.5006490811422114e-05, 'batch_size': 32, 'dropout_rate': 0.41373029997146277}. Best is trial 0 with value: 51.56119804382324.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.6637)
Fold 0: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 71.3152 | Val 59.0165 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 49.8597 | Val 48.7611 | ES 4/30
[Fold 0] Epoch  100 | Train 44.3229 | Val 47.3364 | ES 1/30
[Fold 0] Early stopping at epoch 129 (best Val Loss: 45.7854)
Fold 1: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 74.6466 | Val 64.7968 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 52.8466 | Val 57.0910 | ES 1/30
[Fold 1] Epoch  100 | Train 50.2448 | Val 55.3595 | ES 4/30
[Fold 1] Epoch  150 | Train 47.7773 | Val 54.9579 | ES 19/30
[Fold 1] Epoch  200 | Train 47.3072 | Val 55.3136 | ES 13/30
[Fold 1] Early stopping at epoch 217 (best Val Loss: 53.9870)
Fold 2: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 71.3562 | Val 53.3044 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 52.8302 | Val 38.1921 | ES 2/30
[Fold 2] Epoch  100 | Train 46.8690 | Val 31.9392 | ES 15/30
[Fold 2] Early stopping at epoch 143 (best Val Loss: 30.4076)
Fold 3: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 68.0176 | Val 73.5940 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 56.3178 | Val 74.7035 | ES 6/30
[Fold 3] Epoch  100 | Train 52.8293 | Val 73.9943 | ES 4/30
[Fold 3] Early stopping at epoch 126 (best Val Loss: 68.5785)
Fold 4: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 67.3952 | Val 66.0121 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 50 (best Val Loss: 62.0757)
Fold 5: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 70.2394 | Val 68.0025 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 49.2808 | Val 59.0472 | ES 0/30
[Fold 5] Epoch  100 | Train 44.4701 | Val 53.0277 | ES 1/30
[Fold 5] Epoch  150 | Train 44.7603 | Val 53.4876 | ES 5/30
[Fold 5] Early stopping at epoch 175 (best Val Loss: 49.9691)
Fold 6: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 73.7343 | Val 44.7272 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 51.4361 | Val 35.4302 | ES 7/30
[Fold 6] Early stopping at epoch 84 (best Val Loss: 34.3440)
Fold 7: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 65.3022 | Val 69.7729 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 54.6811 | Val 61.8079 | ES 4/30
[Fold 7] Epoch  100 | Train 47.2495 | Val 59.8012 | ES 6/30
[Fold 7] Early stopping at epoch 124 (best Val Loss: 56.4956)
Fold 8: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 74.3952 | Val 55.7805 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 56.3350 | Val 46.3850 | ES 2/30
[Fold 8] Epoch  100 | Train 45.7711 | Val 42.9359 | ES 17/30
[Fold 8] Early stopping at epoch 113 (best Val Loss: 42.5024)
Fold 9: TL on cpu | freeze=0 | lr=0.000242909
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 71.2060 | Val 36.2799 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 53.3812 | Val 33.9108 | ES 0/30
[Fold 9] Epoch  100 | Train 52.9634 | Val 34.2111 | ES 19/30

[I 2026-02-09 21:46:44,313] Trial 2 finished with value: 47.850283813476565 and parameters: {'learning_rate': 0.0002429090067936898, 'weight_decay': 2.43348536489462e-06, 'batch_size': 16, 'dropout_rate': 0.47638070405836286}. Best is trial 2 with value: 47.850283813476565.

[Fold 9] Early stopping at epoch 139 (best Val Loss: 32.9872)
Fold 0: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 68.3747 | Val 51.3387 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 51.3387)
Fold 1: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 68.4600 | Val 57.0421 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.0421)
Fold 2: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 68.8040 | Val 45.2978 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.2978)
Fold 3: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 67.2958 | Val 60.4108 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.4108)
Fold 4: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 66.3726 | Val 54.4547 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 54.4547)
Fold 5: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 70.6478 | Val 59.8618 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 59.8618)
Fold 6: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 72.1110 | Val 36.9019 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.9019)
Fold 7: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 64.1225 | Val 74.3626 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.3626)
Fold 8: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 72.4121 | Val 46.8547 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.8547)
Fold 9: TL on cpu | freeze=0 | lr=2.99531e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 70.3260 | Val 31.4457 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:46:46,915] Trial 3 finished with value: 51.7971004486084 and parameters: {'learning_rate': 2.9953096058441237e-05, 'weight_decay': 4.371485984321336e-05, 'batch_size': 32, 'dropout_rate': 0.23747221510921304}. Best is trial 2 with value: 47.850283813476565.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.4457)
Fold 0: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 68.4424 | Val 51.3666 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 51.3666)
Fold 1: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 67.9891 | Val 57.0766 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.0766)
Fold 2: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 69.8076 | Val 44.1590 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 44.1590)
Fold 3: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 68.1645 | Val 59.8705 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 59.8705)
Fold 4: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 66.9036 | Val 55.0436 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 55.0436)
Fold 5: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.6106 | Val 59.3806 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 59.3806)
Fold 6: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.7704 | Val 36.7648 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.7648)
Fold 7: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 67.7207 | Val 73.5204 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 73.5204)
Fold 8: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 69.9096 | Val 47.4437 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 47.4437)
Fold 9: TL on cpu | freeze=0 | lr=1.26123e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 71.5779 | Val 31.8167 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:46:49,516] Trial 4 finished with value: 51.64425106048584 and parameters: {'learning_rate': 1.261234597830995e-05, 'weight_decay': 1.993126375126994e-05, 'batch_size': 32, 'dropout_rate': 0.2698592319338135}. Best is trial 2 with value: 47.850283813476565.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.8167)
Fold 0: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 71.5661 | Val 45.1889 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.1889)
Fold 1: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 74.6770 | Val 53.5354 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.5354)
Fold 2: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 72.8177 | Val 39.0709 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 39.0709)
Fold 3: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.8620 | Val 51.7680 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 51.7680)
Fold 4: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 71.5749 | Val 45.5931 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.5931)
Fold 5: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 66.1296 | Val 52.3444 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.3444)
Fold 6: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 69.1358 | Val 33.8598 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 33.8598)
Fold 7: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 66.0106 | Val 70.6178 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 70.6178)
Fold 8: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 67.8967 | Val 44.1391 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:46:51,177] Trial 5 finished with value: 46.82189826965332 and parameters: {'learning_rate': 0.0001330351220546513, 'weight_decay': 1.2382057942911112e-05, 'batch_size': 64, 'dropout_rate': 0.3877667045901865}. Best is trial 5 with value: 46.82189826965332.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.1391)
Fold 9: TL on cpu | freeze=0 | lr=0.000133035
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 67.3224 | Val 33.4077 | ES 0/30
[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.1017)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 66.0967 | Val 57.0901 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 57.0901)
Fold 1: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 66.3646 | Val 65.5061 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 65.5061)
Fold 2: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 71.0388 | Val 54.7410 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 61.7045 | Val 51.8798 | ES 6/30
[Fold 2] Epoch  100 | Train 59.8626 | Val 50.4662 | ES 13/30
[Fold 2] Epoch  150 | Train 58.9230 | Val 46.8433 | ES 15/30
[Fold 2] Early stopping at epoch 165 (best Val Loss: 46.2199)
Fold 3: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.6870 | Val 71.2847 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 71.2847)
Fold 4: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 71.3525 | Val 61.6918 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 61.6918)
Fold 5: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 70.9950 | Val 70.6977 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 70.6977)
Fold 6: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 69.8866 | Val 43.4019 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 62.3686 | Val 43.8689 | ES 4/30
[Fold 6] Epoch  100 | Train 61.8533 | Val 44.2130 | ES 20/30
[Fold 6] Early stopping at epoch 110 (best Val Loss: 40.4104)
Fold 7: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 65.4057 | Val 71.0498 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 61.7620 | Val 67.8886 | ES 0/30
[Fold 7] Early stopping at epoch 100 (best Val Loss: 66.5469)
Fold 8: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.6749 | Val 54.4746 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 64.1879 | Val 54.5278 | ES 12/30
[Fold 8] Early stopping at epoch 96 (best Val Loss: 51.6111)
Fold 9: TL on cpu | freeze=0 | lr=7.98781e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 69.9219 | Val 37.1374 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:47:00,449] Trial 6 finished with value: 56.5627555847168 and parameters: {'learning_rate': 7.987806668174358e-05, 'weight_decay': 0.00010258191382368638, 'batch_size': 16, 'dropout_rate': 0.30573566129081664}. Best is trial 5 with value: 46.82189826965332.

[Fold 9] Early stopping at epoch 47 (best Val Loss: 34.4381)
Fold 0: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 71.6162 | Val 58.1004 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 39.2943 | Val 45.7950 | ES 2/30
[Fold 0] Early stopping at epoch 78 (best Val Loss: 44.2802)
Fold 1: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 67.6257 | Val 64.1414 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 36.6146 | Val 52.8267 | ES 2/30
[Fold 1] Epoch  100 | Train 33.9004 | Val 52.3788 | ES 23/30
[Fold 1] Early stopping at epoch 107 (best Val Loss: 51.5991)
Fold 2: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 69.6127 | Val 52.4460 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 42.3499 | Val 31.4810 | ES 0/30
[Fold 2] Epoch  100 | Train 35.3103 | Val 27.8288 | ES 6/30
[Fold 2] Early stopping at epoch 124 (best Val Loss: 26.5703)
Fold 3: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 69.7679 | Val 76.1327 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 35.3148 | Val 62.8788 | ES 11/30
[Fold 3] Epoch  100 | Train 36.3557 | Val 59.8624 | ES 25/30
[Fold 3] Early stopping at epoch 105 (best Val Loss: 56.8398)
Fold 4: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 68.3905 | Val 67.8688 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 36.8948 | Val 53.0882 | ES 0/30
[Fold 4] Early stopping at epoch 85 (best Val Loss: 51.2538)
Fold 5: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 69.2066 | Val 69.1576 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 40.2372 | Val 52.7221 | ES 4/30
[Fold 5] Early stopping at epoch 76 (best Val Loss: 50.3043)
Fold 6: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.8344 | Val 43.4673 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 37.9536 | Val 37.4854 | ES 15/30
[Fold 6] Early stopping at epoch 65 (best Val Loss: 34.0669)
Fold 7: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch    1 | Train 66.1488 | Val 72.7137 | ES 0/30
[Fold 7] Epoch   50 | Train 37.6314 | Val 56.1271 | ES 7/30
[Fold 7] Early stopping at epoch 73 (best Val Loss: 53.3240)
Fold 8: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.2607 | Val 53.1205 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 42.9692 | Val 47.5395 | ES 3/30
[Fold 8] Early stopping at epoch 86 (best Val Loss: 44.4884)
Fold 9: TL on cpu | freeze=0 | lr=0.000404859
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 68.7977 | Val 36.9020 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:47:12,103] Trial 7 finished with value: 44.73329963684082 and parameters: {'learning_rate': 0.00040485907437153414, 'weight_decay': 4.0623972385258766e-05, 'batch_size': 16, 'dropout_rate': 0.24953527439378545}. Best is trial 7 with value: 44.73329963684082.

[Fold 9] Epoch   50 | Train 36.5682 | Val 32.8594 | ES 17/30
[Fold 9] Early stopping at epoch 63 (best Val Loss: 30.9503)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 71.3716 | Val 52.8010 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 52.8010)
Fold 1: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 71.3063 | Val 57.5892 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.5892)
Fold 2: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 72.8405 | Val 44.8722 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 44.8722)
Fold 3: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.7477 | Val 59.7967 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 59.7967)
Fold 4: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 70.3734 | Val 55.7564 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 55.7564)
Fold 5: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.4830 | Val 60.1559 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 60.1559)
Fold 6: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 71.8313 | Val 36.4294 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.4294)
Fold 7: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 63.4967 | Val 74.7145 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.7145)
Fold 8: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 73.9005 | Val 46.0457 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.0457)
Fold 9: TL on cpu | freeze=0 | lr=0.000177142
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 72.5155 | Val 31.3871 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:47:14,593] Trial 8 finished with value: 51.954812622070314 and parameters: {'learning_rate': 0.00017714202378051676, 'weight_decay': 4.771692150456737e-06, 'batch_size': 32, 'dropout_rate': 0.47404465640927684}. Best is trial 7 with value: 44.73329963684082.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.3871)
Fold 0: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 68.5247 | Val 57.0118 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 45.3693 | Val 46.8053 | ES 0/30
[Fold 0] Epoch  100 | Train 38.4336 | Val 47.1088 | ES 20/30
[Fold 0] Early stopping at epoch 110 (best Val Loss: 45.2861)
Fold 1: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 70.2631 | Val 65.2337 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 47.1707 | Val 53.1979 | ES 1/30
[Fold 1] Early stopping at epoch 91 (best Val Loss: 50.9469)
Fold 2: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 69.6564 | Val 53.8345 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 43.6040 | Val 35.1044 | ES 1/30
[Fold 2] Epoch  100 | Train 40.3146 | Val 28.8951 | ES 3/30
[Fold 2] Early stopping at epoch 127 (best Val Loss: 28.3581)
Fold 3: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 71.1120 | Val 73.9755 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 38.7024 | Val 64.3839 | ES 5/30
[Fold 3] Early stopping at epoch 82 (best Val Loss: 60.2371)
Fold 4: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 68.2615 | Val 63.1582 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 49.0878 | Val 62.5509 | ES 17/30
[Fold 4] Epoch  100 | Train 45.1560 | Val 60.0213 | ES 11/30
[Fold 4] Early stopping at epoch 119 (best Val Loss: 56.8248)
Fold 5: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 66.6205 | Val 68.5318 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 51.3861 | Val 63.1856 | ES 3/30
[Fold 5] Epoch  100 | Train 49.4057 | Val 61.1505 | ES 5/30
[Fold 5] Early stopping at epoch 125 (best Val Loss: 59.1065)
Fold 6: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 71.4271 | Val 43.0152 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 43.3715 | Val 34.1190 | ES 0/30
[Fold 6] Early stopping at epoch 80 (best Val Loss: 34.1190)
Fold 7: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 65.8854 | Val 73.2324 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 39.0696 | Val 58.3797 | ES 3/30
[Fold 7] Epoch  100 | Train 39.1110 | Val 55.3302 | ES 11/30
[Fold 7] Early stopping at epoch 119 (best Val Loss: 54.8627)
Fold 8: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 69.3365 | Val 54.8932 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 40.2689 | Val 46.2524 | ES 3/30
[Fold 8] Early stopping at epoch 100 (best Val Loss: 45.3480)
Fold 9: TL on cpu | freeze=0 | lr=0.000293017
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 69.2088 | Val 36.5121 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 47.6399 | Val 32.9973 | ES 2/30

[I 2026-02-09 21:47:28,748] Trial 9 finished with value: 46.97852725982666 and parameters: {'learning_rate': 0.00029301698581253924, 'weight_decay': 0.0007463871815018052, 'batch_size': 16, 'dropout_rate': 0.2751329791685101}. Best is trial 7 with value: 44.73329963684082.

[Fold 9] Early stopping at epoch 87 (best Val Loss: 32.4476)
Fold 0: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 74.5065 | Val 46.1768 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 46.1768)
Fold 1: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 68.2096 | Val 54.3708 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 54.3708)
Fold 2: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 67.7219 | Val 39.3062 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 39.3062)
Fold 3: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 63.0819 | Val 51.5488 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 51.5488)
Fold 4: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 62.4933 | Val 46.3471 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 46.3471)
Fold 5: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 70.3772 | Val 54.0463 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 54.0463)
Fold 6: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 71.1886 | Val 32.8528 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 32.8528)
Fold 7: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 61.9459 | Val 70.5242 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 39.0455 | Val 66.2963 | ES 3/30
[Fold 7] Epoch  100 | Train 35.3558 | Val 63.6579 | ES 0/30
[Fold 7] Early stopping at epoch 131 (best Val Loss: 63.4992)
Fold 8: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.7419 | Val 45.4310 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:47:31,383] Trial 10 finished with value: 46.5831974029541 and parameters: {'learning_rate': 0.0009854198383893093, 'weight_decay': 0.00020944774842521018, 'batch_size': 64, 'dropout_rate': 0.3345424071094971}. Best is trial 7 with value: 44.73329963684082.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 45.4310)
Fold 9: TL on cpu | freeze=0 | lr=0.00098542
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 73.2209 | Val 33.4434 | ES 0/30
[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.2530)
Fold 0: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 67.9934 | Val 45.7796 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.7796)
Fold 1: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 69.9788 | Val 54.3268 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 54.3268)
Fold 2: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 68.1954 | Val 39.9642 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 39.9642)
Fold 3: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 71.5253 | Val 53.4634 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 53.4634)
Fold 4: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 65.6630 | Val 47.3268 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 47.3268)
Fold 5: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 67.8403 | Val 53.4462 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 53.4462)
Fold 6: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.8483 | Val 32.9708 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 32.9708)
Fold 7: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 63.1535 | Val 67.9988 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 67.9988)
Fold 8: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 67.4160 | Val 46.1709 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.1709)
Fold 9: TL on cpu | freeze=0 | lr=0.000870828
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 70.7594 | Val 33.9303 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:47:32,941] Trial 11 finished with value: 47.46163749694824 and parameters: {'learning_rate': 0.000870828231790127, 'weight_decay': 0.0002528862583693806, 'batch_size': 64, 'dropout_rate': 0.33096602500249916}. Best is trial 7 with value: 44.73329963684082.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 33.1690)
Fold 0: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 66.3468 | Val 45.2868 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.2868)
Fold 1: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 66.4460 | Val 54.3206 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 54.3206)
Fold 2: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 74.2808 | Val 40.6734 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 40.6734)
Fold 3: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 70.3001 | Val 51.2939 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 51.2939)
Fold 4: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 66.3298 | Val 45.4781 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.4781)
Fold 5: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 71.5272 | Val 52.9090 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.9090)
Fold 6: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.1453 | Val 33.8471 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 33.8471)
Fold 7: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 65.7036 | Val 69.5461 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.5461)
Fold 8: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 65.6614 | Val 46.2049 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:47:34,472] Trial 12 finished with value: 47.14609642028809 and parameters: {'learning_rate': 0.0008388253605075965, 'weight_decay': 0.00012557357172114447, 'batch_size': 64, 'dropout_rate': 0.3553869675023179}. Best is trial 7 with value: 44.73329963684082.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.2049)
Fold 9: TL on cpu | freeze=0 | lr=0.000838825
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 74.0090 | Val 33.5243 | ES 0/30
[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.9011)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 73.6193 | Val 45.6649 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.6649)
Fold 1: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 64.2674 | Val 53.4867 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.4867)
Fold 2: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 70.6114 | Val 39.7437 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 39.7437)
Fold 3: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 62.7480 | Val 50.2392 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.2392)
Fold 4: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 68.4700 | Val 45.5931 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.5931)
Fold 5: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 66.6805 | Val 52.8466 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.8466)
Fold 6: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.5022 | Val 33.9529 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 33.9529)
Fold 7: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 69.2709 | Val 69.3863 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.3863)
Fold 8: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 71.1438 | Val 44.6865 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:47:36,072] Trial 13 finished with value: 46.736319351196286 and parameters: {'learning_rate': 0.0004984378328791635, 'weight_decay': 0.0003224317216102513, 'batch_size': 64, 'dropout_rate': 0.28358472762223297}. Best is trial 7 with value: 44.73329963684082.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.6865)
Fold 9: TL on cpu | freeze=0 | lr=0.000498438
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 69.5196 | Val 33.4328 | ES 0/30
[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.7632)
Fold 0: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 70.9466 | Val 57.2661 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 38.1903 | Val 46.3749 | ES 18/30
[Fold 0] Early stopping at epoch 91 (best Val Loss: 45.9080)
Fold 1: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 67.4051 | Val 65.5140 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 35.8051 | Val 52.4366 | ES 6/30
[Fold 1] Early stopping at epoch 74 (best Val Loss: 50.9061)
Fold 2: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 73.1313 | Val 53.9650 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 39.9538 | Val 30.8404 | ES 0/30
[Fold 2] Epoch  100 | Train 32.1382 | Val 27.0043 | ES 2/30
[Fold 2] Early stopping at epoch 136 (best Val Loss: 25.0931)
Fold 3: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 63.8330 | Val 71.5744 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 40.7881 | Val 66.1407 | ES 3/30
[Fold 3] Early stopping at epoch 77 (best Val Loss: 62.1550)
Fold 4: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 66.5703 | Val 68.6038 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 39.1627 | Val 54.8146 | ES 6/30
[Fold 4] Early stopping at epoch 84 (best Val Loss: 49.7424)
Fold 5: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.1807 | Val 69.3385 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 36.4575 | Val 53.3567 | ES 3/30
[Fold 5] Epoch  100 | Train 32.7337 | Val 51.5674 | ES 15/30
[Fold 5] Early stopping at epoch 133 (best Val Loss: 46.6254)
Fold 6: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 66.7963 | Val 43.5250 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 48 (best Val Loss: 34.4395)
Fold 7: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 68.4032 | Val 67.8438 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 36.5951 | Val 54.3872 | ES 11/30
[Fold 7] Early stopping at epoch 98 (best Val Loss: 53.5481)
Fold 8: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 69.7942 | Val 51.7877 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 46.1913 | Val 49.5138 | ES 6/30
[Fold 8] Epoch  100 | Train 44.9557 | Val 48.0017 | ES 25/30
[Fold 8] Early stopping at epoch 105 (best Val Loss: 47.4246)
Fold 9: TL on cpu | freeze=0 | lr=0.000375192
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 71.9181 | Val 34.6584 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:47:48,801] Trial 14 finished with value: 44.90889301300049 and parameters: {'learning_rate': 0.000375192245000101, 'weight_decay': 5.229259241675497e-05, 'batch_size': 16, 'dropout_rate': 0.21129090938271114}. Best is trial 7 with value: 44.73329963684082.

[Fold 9] Epoch   50 | Train 38.8275 | Val 32.3325 | ES 16/30
[Fold 9] Early stopping at epoch 64 (best Val Loss: 31.2131)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 69.9774 | Val 58.3913 | ES 0/30
[Fold 0] Epoch   50 | Train 60.2684 | Val 57.8584 | ES 5/30
[Fold 0] Early stopping at epoch 75 (best Val Loss: 56.5808)
Fold 1: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 69.6027 | Val 65.6672 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 59.6404 | Val 64.4945 | ES 0/30
[Fold 1] Epoch  100 | Train 61.7332 | Val 65.8135 | ES 8/30
[Fold 1] Early stopping at epoch 122 (best Val Loss: 62.1427)
Fold 2: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 69.4840 | Val 53.9368 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 62.3382 | Val 52.7487 | ES 11/30
[Fold 2] Epoch  100 | Train 60.8117 | Val 49.4251 | ES 14/30
[Fold 2] Early stopping at epoch 116 (best Val Loss: 47.6205)
Fold 3: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.5306 | Val 72.3146 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 72.3146)
Fold 4: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 68.8689 | Val 64.3400 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 64.3400)
Fold 5: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 71.6236 | Val 70.7893 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 70.7893)
Fold 6: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.9103 | Val 43.5905 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 62.0918 | Val 43.4675 | ES 16/30
[Fold 6] Early stopping at epoch 87 (best Val Loss: 41.1894)
Fold 7: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 65.4824 | Val 71.7125 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 53.9540 | Val 66.6248 | ES 1/30
[Fold 7] Epoch  100 | Train 46.3064 | Val 62.2736 | ES 3/30
[Fold 7] Early stopping at epoch 148 (best Val Loss: 57.2756)
Fold 8: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.5095 | Val 54.5723 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 61.3228 | Val 55.5286 | ES 6/30
[Fold 8] Early stopping at epoch 88 (best Val Loss: 52.2497)
Fold 9: TL on cpu | freeze=0 | lr=6.65002e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 72.3530 | Val 36.5419 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 63.9713 | Val 37.5705 | ES 9/30

[I 2026-02-09 21:47:59,432] Trial 15 finished with value: 56.002297973632814 and parameters: {'learning_rate': 6.650015017734181e-05, 'weight_decay': 5.420516784721781e-05, 'batch_size': 16, 'dropout_rate': 0.20114429183008592}. Best is trial 7 with value: 44.73329963684082.

[Fold 9] Early stopping at epoch 71 (best Val Loss: 35.4827)
Fold 0: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 68.7121 | Val 58.0512 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 40.9729 | Val 45.2000 | ES 10/30
[Fold 0] Early stopping at epoch 70 (best Val Loss: 43.1615)
Fold 1: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 66.8632 | Val 64.9830 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 35.0801 | Val 50.8467 | ES 0/30
[Fold 1] Early stopping at epoch 91 (best Val Loss: 49.4687)
Fold 2: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 71.8259 | Val 53.2381 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 41.1526 | Val 33.3666 | ES 2/30
[Fold 2] Epoch  100 | Train 29.6174 | Val 28.8916 | ES 22/30
[Fold 2] Early stopping at epoch 108 (best Val Loss: 27.5737)
Fold 3: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.0631 | Val 70.9971 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 39.8544 | Val 60.1792 | ES 0/30
[Fold 3] Epoch  100 | Train 34.5939 | Val 61.4122 | ES 19/30
[Fold 3] Early stopping at epoch 111 (best Val Loss: 59.0841)
Fold 4: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 64.7843 | Val 63.8203 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 36.2291 | Val 53.0909 | ES 2/30
[Fold 4] Early stopping at epoch 85 (best Val Loss: 50.2548)
Fold 5: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 72.7452 | Val 71.4550 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 33.9678 | Val 49.6111 | ES 2/30
[Fold 5] Early stopping at epoch 100 (best Val Loss: 46.6034)
Fold 6: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 69.8716 | Val 42.8526 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 42.6086 | Val 36.9798 | ES 29/30
[Fold 6] Early stopping at epoch 51 (best Val Loss: 34.2374)
Fold 7: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 65.7022 | Val 69.0841 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 35.6548 | Val 55.0026 | ES 6/30
[Fold 7] Early stopping at epoch 74 (best Val Loss: 52.7045)
Fold 8: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.6603 | Val 52.0377 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 36.1781 | Val 41.8970 | ES 5/30
[Fold 8] Epoch  100 | Train 38.9072 | Val 42.9988 | ES 26/30
[Fold 8] Early stopping at epoch 104 (best Val Loss: 40.9989)
Fold 9: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 70.5309 | Val 34.8391 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:48:10,755] Trial 16 finished with value: 44.137620544433595 and parameters: {'learning_rate': 0.0004408716160521325, 'weight_decay': 5.152851369559039e-05, 'batch_size': 16, 'dropout_rate': 0.23141264074960805}. Best is trial 16 with value: 44.137620544433595.

[Fold 9] Epoch   50 | Train 37.5738 | Val 35.0574 | ES 16/30
[Fold 9] Early stopping at epoch 64 (best Val Loss: 32.4354)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 66.3754 | Val 57.3426 | ES 0/30
[Fold 0] Epoch   50 | Train 34.7704 | Val 44.9247 | ES 13/30
[Fold 0] Early stopping at epoch 67 (best Val Loss: 44.3966)
Fold 1: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 68.1808 | Val 65.7504 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 33.5896 | Val 51.9722 | ES 6/30
[Fold 1] Epoch  100 | Train 30.7353 | Val 50.7326 | ES 24/30
[Fold 1] Early stopping at epoch 106 (best Val Loss: 49.4980)
Fold 2: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 66.9268 | Val 51.0083 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 37.8863 | Val 30.4239 | ES 3/30
[Fold 2] Epoch  100 | Train 34.2150 | Val 27.6517 | ES 0/30
[Fold 2] Epoch  150 | Train 27.7277 | Val 27.9839 | ES 10/30
[Fold 2] Early stopping at epoch 170 (best Val Loss: 27.3447)
Fold 3: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 67.3951 | Val 75.0536 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 37.6798 | Val 59.9311 | ES 8/30
[Fold 3] Early stopping at epoch 72 (best Val Loss: 59.5285)
Fold 4: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 66.4861 | Val 62.6811 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 35.0247 | Val 52.6482 | ES 0/30
[Fold 4] Early stopping at epoch 84 (best Val Loss: 49.4567)
Fold 5: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 71.9540 | Val 70.4263 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 34.7151 | Val 50.4463 | ES 0/30
[Fold 5] Epoch  100 | Train 34.2010 | Val 50.2183 | ES 29/30
[Fold 5] Early stopping at epoch 101 (best Val Loss: 49.0413)
Fold 6: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 65.3214 | Val 41.1895 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 47 (best Val Loss: 35.5548)
Fold 7: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 67.1907 | Val 70.2912 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 34.1855 | Val 55.0085 | ES 10/30
[Fold 7] Early stopping at epoch 70 (best Val Loss: 53.0997)
Fold 8: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 70.1346 | Val 54.5119 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 35.5719 | Val 44.2971 | ES 0/30
[Fold 8] Early stopping at epoch 95 (best Val Loss: 42.7301)
Fold 9: TL on cpu | freeze=0 | lr=0.000498331
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 68.8136 | Val 35.8579 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:48:22,261] Trial 17 finished with value: 44.838097381591794 and parameters: {'learning_rate': 0.0004983306484879774, 'weight_decay': 6.208544095871377e-06, 'batch_size': 16, 'dropout_rate': 0.2395342367161438}. Best is trial 16 with value: 44.137620544433595.

[Fold 9] Epoch   50 | Train 38.9399 | Val 35.4190 | ES 17/30
[Fold 9] Early stopping at epoch 63 (best Val Loss: 31.9565)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 72.7073 | Val 59.4212 | ES 0/30
[Fold 0] Epoch   50 | Train 60.6721 | Val 60.0367 | ES 14/30
[Fold 0] Epoch  100 | Train 64.3219 | Val 57.9667 | ES 26/30
[Fold 0] Early stopping at epoch 104 (best Val Loss: 56.3805)
Fold 1: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 70.2359 | Val 65.6391 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 65.6391)
Fold 2: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 74.2632 | Val 53.9688 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 53.9688)
Fold 3: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 69.0539 | Val 70.8793 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 70.8793)
Fold 4: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 69.8051 | Val 67.5343 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 60.7949 | Val 67.6504 | ES 19/30
[Fold 4] Early stopping at epoch 83 (best Val Loss: 65.8964)
Fold 5: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.7745 | Val 68.8184 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 68.8184)
Fold 6: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 72.7594 | Val 43.9151 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 43.9151)
Fold 7: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 65.2139 | Val 71.3045 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 71.3045)
Fold 8: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 69.0990 | Val 53.0307 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 53.0307)
Fold 9: TL on cpu | freeze=0 | lr=4.78965e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 70.8681 | Val 35.7490 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:48:28,298] Trial 18 finished with value: 58.22929725646973 and parameters: {'learning_rate': 4.789653100069178e-05, 'weight_decay': 3.02194488602598e-05, 'batch_size': 16, 'dropout_rate': 0.24596325283265072}. Best is trial 16 with value: 44.137620544433595.

[Fold 9] Epoch   50 | Train 66.3879 | Val 35.6128 | ES 20/30
[Fold 9] Early stopping at epoch 60 (best Val Loss: 34.9513)
Fold 0: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch    1 | Train 70.8960 | Val 57.4356 | ES 0/30
[Fold 0] Epoch   50 | Train 41.0134 | Val 46.0639 | ES 19/30
[Fold 0] Early stopping at epoch 61 (best Val Loss: 45.1992)
Fold 1: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 65.2410 | Val 64.1717 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 36.8398 | Val 50.3490 | ES 9/30
[Fold 1] Early stopping at epoch 94 (best Val Loss: 49.7786)
Fold 2: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 71.6276 | Val 53.5803 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 42.0907 | Val 32.6419 | ES 7/30
[Fold 2] Early stopping at epoch 91 (best Val Loss: 29.6563)
Fold 3: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.1922 | Val 75.6119 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 38.9099 | Val 57.2828 | ES 0/30
[Fold 3] Early stopping at epoch 91 (best Val Loss: 55.5257)
Fold 4: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 68.2949 | Val 62.4057 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 36.4704 | Val 55.3376 | ES 7/30
[Fold 4] Early stopping at epoch 86 (best Val Loss: 49.8551)
Fold 5: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.1450 | Val 70.5274 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 38.4624 | Val 51.1908 | ES 4/30
[Fold 5] Epoch  100 | Train 36.4460 | Val 52.5180 | ES 21/30
[Fold 5] Early stopping at epoch 109 (best Val Loss: 48.7189)
Fold 6: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 71.3329 | Val 43.8394 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 42 (best Val Loss: 33.9945)
Fold 7: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 66.2750 | Val 73.2316 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 40.6731 | Val 57.4364 | ES 19/30
[Fold 7] Early stopping at epoch 61 (best Val Loss: 56.0180)
Fold 8: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.6397 | Val 52.3909 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 42.8768 | Val 42.7293 | ES 12/30
[Fold 8] Early stopping at epoch 85 (best Val Loss: 40.0946)
Fold 9: TL on cpu | freeze=0 | lr=0.000542446
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 72.6391 | Val 36.2001 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:48:38,819] Trial 19 finished with value: 44.39885482788086 and parameters: {'learning_rate': 0.0005424463163436833, 'weight_decay': 0.0006238483371172624, 'batch_size': 16, 'dropout_rate': 0.30727646408606535}. Best is trial 16 with value: 44.137620544433595.

[Fold 9] Epoch   50 | Train 39.8206 | Val 33.6393 | ES 20/30
[Fold 9] Early stopping at epoch 60 (best Val Loss: 31.1009)
[no_freeze] Best avg RMSE: 44.1376
[no_freeze] Best params:  {'learning_rate': 0.0004408716160521325, 'weight_decay': 5.152851369559039e-05, 'batch_size': 16, 'dropout_rate': 0.23141264074960805}
Fold 0: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch    1 | Train 69.7856 | Val 58.4474 | ES 0/30
[Fold 0] Epoch   50 | Train 39.1116 | Val 43.3565 | ES 12/30
[Fold 0] Early stopping at epoch 68 (best Val Loss: 42.9947)
Fold 1: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 69.5559 | Val 66.3055 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 38.7267 | Val 49.1225 | ES 1/30
[Fold 1] Early stopping at epoch 79 (best Val Loss: 48.9164)
Fold 2: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 68.7860 | Val 51.6552 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 36.6837 | Val 32.3322 | ES 0/30
[Fold 2] Epoch  100 | Train 37.5566 | Val 29.2987 | ES 19/30
[Fold 2] Early stopping at epoch 111 (best Val Loss: 28.4470)
Fold 3: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 65.9739 | Val 73.3239 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 36.2926 | Val 61.9404 | ES 5/30
[Fold 3] Early stopping at epoch 75 (best Val Loss: 58.9858)
Fold 4: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 67.5175 | Val 65.7731 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 37.2860 | Val 52.8964 | ES 9/30
[Fold 4] Epoch  100 | Train 29.7539 | Val 54.0303 | ES 12/30
[Fold 4] Early stopping at epoch 150 (best Val Loss: 48.4289)
Fold 5: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 69.5005 | Val 69.9548 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 33.7851 | Val 50.9496 | ES 3/30
[Fold 5] Epoch  100 | Train 35.1154 | Val 50.6293 | ES 28/30
[Fold 5] Early stopping at epoch 102 (best Val Loss: 47.3361)
Fold 6: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 66.6870 | Val 43.5818 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 37.7989 | Val 38.2817 | ES 20/30
[Fold 6] Early stopping at epoch 60 (best Val Loss: 35.4729)
Fold 7: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 64.3334 | Val 72.2355 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 34.9826 | Val 56.1393 | ES 4/30
[Fold 7] Early stopping at epoch 83 (best Val Loss: 53.8829)
Fold 8: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.0629 | Val 52.3620 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 38.1955 | Val 42.0353 | ES 5/30
[Fold 8] Early stopping at epoch 99 (best Val Loss: 41.1986)
Fold 9: TL on cpu | freeze=0 | lr=0.000440872
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 69.7625 | Val 35.8335 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:48:50,428] A new study created in memory with name: no-name-98aed861-9f8d-4c66-9628-c94a14b75f65

[Fold 9] Epoch   50 | Train 40.8377 | Val 33.9239 | ES 18/30
[Fold 9] Early stopping at epoch 62 (best Val Loss: 31.7766)
[no_freeze] Best fold: 2 → artifacts/TL_Ro5_no_interaction/no_freeze/final_fold_models/fold_2_best.pth

=== Scenario: freeze_fc1 | freeze=[1, 0, 0] (level=1) ===
Fold 0: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.0791 | Val 51.3581 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 46.6250 | Val 46.3686 | ES 5/30
[Fold 0] Early stopping at epoch 75 (best Val Loss: 46.0935)
Fold 1: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 69.0026 | Val 55.8475 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 55.8475)
Fold 2: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.3173 | Val 44.8269 | ES 0/30
[Fold 2] Epoch   50 | Train 38.4530 | Val 29.4882 | ES 2/30
[Fold 2] Epoch  100 | Train 36.8547 | Val 25.7941 | ES 3/30
[Fold 2] Early stopping at epoch 132 (best Val Loss: 25.4283)
Fold 3: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch    1 | Train 64.5690 | Val 59.9236 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 59.9236)
Fold 4: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 69.0777 | Val 55.0559 | ES 0/30
[Fold 4] Epoch   50 | Train 48.0672 | Val 51.1599 | ES 0/30
[Fold 4] Epoch  100 | Train 44.7703 | Val 49.2909 | ES 20/30
[Fold 4] Early stopping at epoch 110 (best Val Loss: 48.5154)
Fold 5: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 67.3827 | Val 59.5260 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 44.1274 | Val 52.6026 | ES 0/30
[Fold 5] Epoch  100 | Train 41.7801 | Val 48.9277 | ES 7/30
[Fold 5] Early stopping at epoch 137 (best Val Loss: 47.3661)
Fold 6: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 71.1390 | Val 36.5892 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.5892)
Fold 7: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch    1 | Train 64.7004 | Val 74.4096 | ES 0/30
[Fold 7] Epoch   50 | Train 40.9682 | Val 66.9149 | ES 0/30
[Fold 7] Epoch  100 | Train 38.9371 | Val 63.7479 | ES 3/30
[Fold 7] Early stopping at epoch 145 (best Val Loss: 62.4908)
Fold 8: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 70.1051 | Val 46.9117 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.9117)
Fold 9: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 67.1789 | Val 31.7124 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:48:55,294] Trial 0 finished with value: 46.02029533386231 and parameters: {'learning_rate': 0.0009628679838622033, 'weight_decay': 1.137981512568195e-06, 'batch_size': 32, 'dropout_rate': 0.20509723092012022}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Epoch   50 | Train 46.2254 | Val 31.3279 | ES 25/30
[Fold 9] Early stopping at epoch 55 (best Val Loss: 31.0368)
Fold 0: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.1415 | Val 55.8521 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 55.8521)
Fold 1: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 69.5467 | Val 66.8686 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 66.8686)
Fold 2: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 69.9881 | Val 53.3835 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 53.3835)
Fold 3: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 68.6203 | Val 73.4788 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 73.4788)
Fold 4: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 66.6913 | Val 64.5834 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 64.5834)
Fold 5: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 69.7754 | Val 68.5127 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 68.5127)
Fold 6: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 71.4660 | Val 43.5078 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 43.5078)
Fold 7: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 68.2471 | Val 72.1874 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 72.1874)
Fold 8: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 71.8586 | Val 52.6120 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 52.6120)
Fold 9: TL on cpu | freeze=1 | lr=6.246e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 72.7331 | Val 35.1247 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:48:58,619] Trial 1 finished with value: 58.39817886352539 and parameters: {'learning_rate': 6.245998651244242e-05, 'weight_decay': 8.648605482155422e-05, 'batch_size': 16, 'dropout_rate': 0.20406955614678537}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 35.1247)
Fold 0: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.7277 | Val 51.6345 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 51.6345)
Fold 1: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.5944 | Val 57.0206 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.0206)
Fold 2: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch    1 | Train 71.9327 | Val 45.9707 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.9707)
Fold 3: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 66.3884 | Val 60.9996 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.9996)
Fold 4: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 68.4163 | Val 54.7441 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 54.7441)
Fold 5: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch    1 | Train 65.5449 | Val 59.1008 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 59.1008)
Fold 6: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 70.5736 | Val 36.7107 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.7107)
Fold 7: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 66.7762 | Val 74.3868 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.3868)
Fold 8: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 66.1667 | Val 46.4120 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:00,649] Trial 2 finished with value: 51.83123092651367 and parameters: {'learning_rate': 0.0004504525962223127, 'weight_decay': 1.291813766825645e-06, 'batch_size': 32, 'dropout_rate': 0.3417408275188495}. Best is trial 0 with value: 46.02029533386231.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.4120)
Fold 9: TL on cpu | freeze=1 | lr=0.000450453
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 70.4752 | Val 31.3325 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.3325)
Fold 0: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 69.7392 | Val 53.7787 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 53.7787)
Fold 1: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 67.0627 | Val 64.3621 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 60.3691 | Val 61.9497 | ES 2/30
[Fold 1] Epoch  100 | Train 55.9598 | Val 59.8509 | ES 7/30
[Fold 1] Epoch  150 | Train 52.7985 | Val 60.2487 | ES 6/30
[Fold 1] Early stopping at epoch 183 (best Val Loss: 58.8909)
Fold 2: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.8426 | Val 53.0217 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 55.7981 | Val 42.1467 | ES 0/30
[Fold 2] Epoch  100 | Train 52.0829 | Val 38.6331 | ES 7/30
[Fold 2] Epoch  150 | Train 53.3751 | Val 37.9600 | ES 7/30
[Fold 2] Epoch  200 | Train 53.8465 | Val 38.2527 | ES 17/30
[Fold 2] Early stopping at epoch 213 (best Val Loss: 34.9737)
Fold 3: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 64.4846 | Val 73.2569 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 73.2569)
Fold 4: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 67.6298 | Val 63.8521 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 57.2913 | Val 62.3118 | ES 1/30
[Fold 4] Epoch  100 | Train 55.1246 | Val 64.7693 | ES 10/30
[Fold 4] Early stopping at epoch 120 (best Val Loss: 59.3057)
Fold 5: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 67.2007 | Val 67.9120 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 57.7467 | Val 61.5785 | ES 0/30
[Fold 5] Epoch  100 | Train 50.6353 | Val 56.1697 | ES 7/30
[Fold 5] Epoch  150 | Train 50.5985 | Val 52.0109 | ES 9/30
[Fold 5] Early stopping at epoch 186 (best Val Loss: 50.5749)
Fold 6: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 70.8362 | Val 44.7310 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 53.1275 | Val 38.4422 | ES 7/30
[Fold 6] Early stopping at epoch 96 (best Val Loss: 35.9495)
Fold 7: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 63.2198 | Val 69.8087 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 55.6958 | Val 68.9480 | ES 16/30
[Fold 7] Epoch  100 | Train 53.9556 | Val 68.5673 | ES 14/30
[Fold 7] Early stopping at epoch 116 (best Val Loss: 67.5577)
Fold 8: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 68.0933 | Val 52.8602 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 56.2130 | Val 52.5218 | ES 4/30
[Fold 8] Early stopping at epoch 76 (best Val Loss: 51.9259)
Fold 9: TL on cpu | freeze=1 | lr=0.000250398
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 72.3416 | Val 35.2100 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 58.1992 | Val 33.1918 | ES 1/30
[Fold 9] Epoch  100 | Train 55.6922 | Val 33.2202 | ES 17/30

[I 2026-02-09 21:49:13,287] Trial 3 finished with value: 51.775153732299806 and parameters: {'learning_rate': 0.00025039786600622677, 'weight_decay': 1.1006873495521895e-06, 'batch_size': 16, 'dropout_rate': 0.21545747306985094}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 132 (best Val Loss: 31.9971)
Fold 0: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 66.5317 | Val 45.5582 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.5582)
Fold 1: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 71.8536 | Val 53.2841 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.2841)
Fold 2: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 73.6511 | Val 38.9326 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.9326)
Fold 3: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 67.3064 | Val 52.3951 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 52.3951)
Fold 4: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 70.7778 | Val 47.3868 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 47.3868)
Fold 5: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 71.6512 | Val 52.2054 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.2054)
Fold 6: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 77.4443 | Val 34.3622 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.3622)
Fold 7: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 65.5114 | Val 70.8025 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 70.8025)
Fold 8: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 72.9123 | Val 44.1809 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.1809)
Fold 9: TL on cpu | freeze=1 | lr=1.98333e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 69.7937 | Val 33.3581 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:14,550] Trial 4 finished with value: 47.094336891174315 and parameters: {'learning_rate': 1.9833257428810153e-05, 'weight_decay': 0.0001017392665191896, 'batch_size': 64, 'dropout_rate': 0.4811269595451082}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.8357)
Fold 0: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 64.6847 | Val 45.4194 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.4194)
Fold 1: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 69.7604 | Val 53.5583 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.5583)
Fold 2: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 72.0676 | Val 39.2763 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 39.2763)
Fold 3: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 66.4561 | Val 49.2440 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 49.2440)
Fold 4: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 70.6361 | Val 46.2275 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 46.2275)
Fold 5: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 70.7521 | Val 52.3194 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.3194)
Fold 6: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 70.2355 | Val 34.5897 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.5897)
Fold 7: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 66.4820 | Val 69.2662 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.2662)
Fold 8: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 65.6486 | Val 45.0039 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 45.0039)
Fold 9: TL on cpu | freeze=1 | lr=4.26316e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 70.4320 | Val 33.1865 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:15,807] Trial 5 finished with value: 46.68441734313965 and parameters: {'learning_rate': 4.263156982764238e-05, 'weight_decay': 7.202503701620223e-05, 'batch_size': 64, 'dropout_rate': 0.31534755887171106}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.9394)
Fold 0: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.7377 | Val 58.6056 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 58.6056)
Fold 1: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.5115 | Val 65.1639 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 65.1639)
Fold 2: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.3633 | Val 53.7565 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 53.7565)
Fold 3: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 68.7163 | Val 73.5066 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 73.5066)
Fold 4: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 68.3842 | Val 68.2389 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 68.2389)
Fold 5: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 69.6107 | Val 69.3139 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 69.3139)
Fold 6: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 72.4842 | Val 42.5257 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 42.5257)
Fold 7: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 67.4214 | Val 74.2535 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.2535)
Fold 8: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 72.1823 | Val 50.9413 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 50.9413)
Fold 9: TL on cpu | freeze=1 | lr=1.66894e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 74.4048 | Val 36.1736 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:19,199] Trial 6 finished with value: 59.063533020019534 and parameters: {'learning_rate': 1.668938896302694e-05, 'weight_decay': 8.8234859712107e-06, 'batch_size': 16, 'dropout_rate': 0.48907712540225756}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 36.1736)
Fold 0: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.8288 | Val 56.8174 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 56.8174)
Fold 1: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 72.6267 | Val 64.9487 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 64.9487)
Fold 2: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 71.9079 | Val 54.1065 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 54.1065)
Fold 3: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 66.9924 | Val 74.1464 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 74.1464)
Fold 4: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 68.0866 | Val 62.1617 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 62.1617)
Fold 5: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 66.8442 | Val 69.2603 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 69.2603)
Fold 6: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 72.4702 | Val 42.9643 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 42.9643)
Fold 7: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 65.2849 | Val 72.8229 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 72.8229)
Fold 8: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 71.8991 | Val 52.4002 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 52.4002)
Fold 9: TL on cpu | freeze=1 | lr=6.10126e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.0050 | Val 36.0217 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:22,495] Trial 7 finished with value: 58.349477005004886 and parameters: {'learning_rate': 6.1012588576967646e-05, 'weight_decay': 1.0194793535797962e-05, 'batch_size': 16, 'dropout_rate': 0.3215920428708248}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 36.0217)
Fold 0: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 71.1559 | Val 52.1719 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 52.1719)
Fold 1: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.5356 | Val 56.7307 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.7307)
Fold 2: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 72.1639 | Val 45.3862 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.3862)
Fold 3: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 68.0561 | Val 62.8404 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 62.8404)
Fold 4: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 69.3054 | Val 55.3811 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 55.3811)
Fold 5: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 70.9123 | Val 59.6805 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 59.6805)
Fold 6: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 70.5889 | Val 37.3663 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 37.3663)
Fold 7: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 64.7714 | Val 74.2772 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.2772)
Fold 8: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 69.2863 | Val 46.3050 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:24,495] Trial 8 finished with value: 52.16580448150635 and parameters: {'learning_rate': 0.0006160904931923352, 'weight_decay': 1.8536094359822583e-06, 'batch_size': 32, 'dropout_rate': 0.46989159481360787}. Best is trial 0 with value: 46.02029533386231.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.3050)
Fold 9: TL on cpu | freeze=1 | lr=0.00061609
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 73.2793 | Val 31.5187 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.5187)
Fold 0: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 68.8621 | Val 56.2957 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 56.2957)
Fold 1: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 67.5384 | Val 64.9698 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 64.9698)
Fold 2: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 69.5198 | Val 52.4996 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 52.4996)
Fold 3: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 66.4970 | Val 73.7645 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 73.7645)
Fold 4: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 67.6578 | Val 65.4578 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 65.4578)
Fold 5: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 70.9979 | Val 68.2226 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 68.2226)
Fold 6: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 69.1053 | Val 45.4263 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 63.4789 | Val 45.5678 | ES 6/30
[Fold 6] Epoch  100 | Train 62.8935 | Val 46.7111 | ES 23/30
[Fold 6] Early stopping at epoch 107 (best Val Loss: 42.5792)
Fold 7: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 65.3602 | Val 72.2114 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 62.4226 | Val 71.7905 | ES 1/30
[Fold 7] Early stopping at epoch 92 (best Val Loss: 69.0251)
Fold 8: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 69.4948 | Val 53.9172 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 53.9172)
Fold 9: TL on cpu | freeze=1 | lr=0.000112647
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 72.8613 | Val 36.9552 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 65.4244 | Val 35.9805 | ES 0/30

[I 2026-02-09 21:49:30,037] Trial 9 finished with value: 58.02331657409668 and parameters: {'learning_rate': 0.00011264714457290045, 'weight_decay': 3.2063937417013356e-06, 'batch_size': 16, 'dropout_rate': 0.24309896513901097}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Epoch  100 | Train 65.1956 | Val 36.6113 | ES 29/30
[Fold 9] Early stopping at epoch 101 (best Val Loss: 35.6731)
Fold 0: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 69.0058 | Val 52.5064 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 49.8756 | Val 47.8640 | ES 0/30
[Fold 0] Epoch  100 | Train 50.4938 | Val 47.2275 | ES 21/30
[Fold 0] Early stopping at epoch 109 (best Val Loss: 46.3779)
Fold 1: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 71.1975 | Val 56.6530 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.6530)
Fold 2: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 73.3292 | Val 45.1043 | ES 0/30
[Fold 2] Epoch   50 | Train 55.8740 | Val 34.0416 | ES 5/30
[Fold 2] Epoch  100 | Train 47.9359 | Val 28.4904 | ES 6/30
[Fold 2] Epoch  150 | Train 48.9835 | Val 27.4300 | ES 6/30
[Fold 2] Early stopping at epoch 174 (best Val Loss: 27.3173)
Fold 3: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 69.1929 | Val 62.3157 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 62.3157)
Fold 4: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 66.7610 | Val 56.1586 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 56.1586)
Fold 5: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch    1 | Train 69.6668 | Val 60.9163 | ES 0/30
[Fold 5] Epoch   50 | Train 52.8832 | Val 54.0114 | ES 4/30
[Fold 5] Epoch  100 | Train 49.3689 | Val 49.3892 | ES 2/30
[Fold 5] Epoch  150 | Train 46.9354 | Val 48.1515 | ES 29/30
[Fold 5] Early stopping at epoch 151 (best Val Loss: 46.5873)
Fold 6: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 71.1415 | Val 36.8528 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.8528)
Fold 7: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch    1 | Train 65.2581 | Val 74.2660 | ES 0/30
[Fold 7] Epoch   50 | Train 54.1887 | Val 71.4784 | ES 1/30
[Fold 7] Epoch  100 | Train 49.0815 | Val 67.5344 | ES 0/30
[Fold 7] Epoch  150 | Train 46.9277 | Val 66.7391 | ES 5/30
[Fold 7] Early stopping at epoch 189 (best Val Loss: 65.9297)
Fold 8: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 68.8545 | Val 45.7253 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 45.7253)
Fold 9: TL on cpu | freeze=1 | lr=0.000993547
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:35,155] Trial 10 finished with value: 47.55044097900391 and parameters: {'learning_rate': 0.0009935466952743467, 'weight_decay': 0.0009561443802302474, 'batch_size': 32, 'dropout_rate': 0.3995351640076677}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Epoch    1 | Train 69.1816 | Val 31.5870 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.5870)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 71.4314 | Val 44.6986 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 44.6986)
Fold 1: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.2216 | Val 53.4970 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.4970)
Fold 2: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.4921 | Val 38.3999 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.3999)
Fold 3: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 66.9241 | Val 50.9936 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.9936)
Fold 4: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 64.6591 | Val 45.2723 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.2723)
Fold 5: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 68.0171 | Val 52.1718 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.1718)
Fold 6: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 70.7482 | Val 34.3752 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.3752)
Fold 7: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 63.0289 | Val 69.6537 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.6537)
Fold 8: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 69.9119 | Val 45.1052 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 45.1052)
Fold 9: TL on cpu | freeze=1 | lr=4.05626e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 74.0966 | Val 33.4658 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:36,435] Trial 11 finished with value: 46.68448143005371 and parameters: {'learning_rate': 4.056263358207213e-05, 'weight_decay': 5.650210489966848e-05, 'batch_size': 64, 'dropout_rate': 0.28695306721854286}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.6774)
Fold 0: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 64.8194 | Val 44.6650 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 44.6650)
Fold 1: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 66.9510 | Val 53.5664 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.5664)
Fold 2: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 74.4484 | Val 38.9380 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.9380)
Fold 3: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 67.4349 | Val 50.2374 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.2374)
Fold 4: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 70.3405 | Val 46.8258 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 46.8258)
Fold 5: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 66.9630 | Val 52.2730 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.2730)
Fold 6: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 71.1679 | Val 34.2083 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.2083)
Fold 7: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 66.2316 | Val 69.6083 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.6083)
Fold 8: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 72.2132 | Val 44.4607 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.4607)
Fold 9: TL on cpu | freeze=1 | lr=0.00010295
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 72.6243 | Val 33.4505 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:37,713] Trial 12 finished with value: 46.646649551391604 and parameters: {'learning_rate': 0.00010294970598974811, 'weight_decay': 0.00031985970130192265, 'batch_size': 64, 'dropout_rate': 0.40559442397958256}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.6837)
Fold 0: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.9439 | Val 52.0922 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 52.0922)
Fold 1: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 63.7470 | Val 56.6094 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.6094)
Fold 2: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch    1 | Train 73.9333 | Val 45.7903 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.7903)
Fold 3: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 67.7097 | Val 59.0825 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 59.0825)
Fold 4: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 69.2494 | Val 54.8948 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 54.8948)
Fold 5: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch    1 | Train 68.5182 | Val 60.8427 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 60.8427)
Fold 6: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 73.2316 | Val 37.0208 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 37.0208)
Fold 7: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 69.8456 | Val 74.6330 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.6330)
Fold 8: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 71.5504 | Val 47.1596 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:39,828] Trial 13 finished with value: 51.980831909179685 and parameters: {'learning_rate': 0.00020049348267156254, 'weight_decay': 0.0004135699021039039, 'batch_size': 32, 'dropout_rate': 0.3965064258438273}. Best is trial 0 with value: 46.02029533386231.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 47.1596)
Fold 9: TL on cpu | freeze=1 | lr=0.000200493
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.3876 | Val 31.6829 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.6829)
Fold 0: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.0355 | Val 45.5965 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.5965)
Fold 1: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.7325 | Val 53.6004 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.6004)
Fold 2: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 69.7151 | Val 38.7876 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.7876)
Fold 3: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 68.8513 | Val 50.7554 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.7554)
Fold 4: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 71.5007 | Val 46.9025 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 46.9025)
Fold 5: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 70.6805 | Val 52.4384 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.4384)
Fold 6: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 73.7640 | Val 34.1797 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.1797)
Fold 7: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 64.9055 | Val 70.8507 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 70.8507)
Fold 8: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 70.3006 | Val 44.8452 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.8452)
Fold 9: TL on cpu | freeze=1 | lr=1.01366e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.0411 | Val 33.6218 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:41,103] Trial 14 finished with value: 46.979601287841795 and parameters: {'learning_rate': 1.013658908194261e-05, 'weight_decay': 0.0002026362672855499, 'batch_size': 64, 'dropout_rate': 0.4023246615973469}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.8395)
Fold 0: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.2041 | Val 52.3946 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 52.3946)
Fold 1: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 71.2829 | Val 57.2595 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.2595)
Fold 2: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch    1 | Train 73.4377 | Val 45.1665 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.1665)
Fold 3: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 68.4489 | Val 58.6560 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 58.6560)
Fold 4: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 68.0850 | Val 54.0378 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 54.0378)
Fold 5: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 69.9412 | Val 60.0029 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 60.0029)
Fold 6: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch    1 | Train 70.7615 | Val 36.7575 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.7575)
Fold 7: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 68.5877 | Val 74.5178 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.5178)
Fold 8: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 66.4790 | Val 46.4528 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.4528)
Fold 9: TL on cpu | freeze=1 | lr=0.000184805
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:43,158] Trial 15 finished with value: 51.654382133483885 and parameters: {'learning_rate': 0.00018480491100304947, 'weight_decay': 1.969624466064355e-05, 'batch_size': 32, 'dropout_rate': 0.44100452153656156}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Epoch    1 | Train 72.1180 | Val 31.2984 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.2984)
Fold 0: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 73.2074 | Val 45.8117 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.8117)
Fold 1: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 66.7595 | Val 53.3845 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.3845)
Fold 2: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 68.9889 | Val 38.5967 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.5967)
Fold 3: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 69.5230 | Val 51.0708 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 51.0708)
Fold 4: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 65.3787 | Val 45.9205 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.9205)
Fold 5: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 72.4043 | Val 52.3459 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.3459)
Fold 6: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 68.9676 | Val 34.1844 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.1844)
Fold 7: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 65.1230 | Val 69.9823 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.9823)
Fold 8: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 73.2115 | Val 44.9582 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.9582)
Fold 9: TL on cpu | freeze=1 | lr=0.000453176
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 72.6853 | Val 33.6365 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:44,439] Trial 16 finished with value: 46.774542045593265 and parameters: {'learning_rate': 0.00045317595226361556, 'weight_decay': 4.363422873650024e-06, 'batch_size': 64, 'dropout_rate': 0.2673908589204114}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.4904)
Fold 0: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 71.4745 | Val 51.8040 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 51.8040)
Fold 1: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 68.7809 | Val 56.9186 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.9186)
Fold 2: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch    1 | Train 72.2168 | Val 45.6251 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.6251)
Fold 3: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 64.6836 | Val 60.3010 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.3010)
Fold 4: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 68.3159 | Val 54.5692 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 54.5692)
Fold 5: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 69.3093 | Val 60.2986 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 60.2986)
Fold 6: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 70.2297 | Val 36.4396 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.4396)
Fold 7: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch    1 | Train 66.5574 | Val 74.3528 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.3528)
Fold 8: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 69.2144 | Val 46.5863 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:46,495] Trial 17 finished with value: 51.884476280212404 and parameters: {'learning_rate': 0.00012093403964747736, 'weight_decay': 2.728353243154627e-05, 'batch_size': 32, 'dropout_rate': 0.3639064365956418}. Best is trial 0 with value: 46.02029533386231.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.5863)
Fold 9: TL on cpu | freeze=1 | lr=0.000120934
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.1692 | Val 31.9494 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.9494)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 66.9099 | Val 46.0961 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 46.0961)
Fold 1: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 68.8599 | Val 53.5575 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.5575)
Fold 2: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 73.1053 | Val 39.6660 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 39.6660)
Fold 3: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 66.7398 | Val 51.4138 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 51.4138)
Fold 4: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 68.5786 | Val 47.0830 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 47.0830)
Fold 5: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 71.6597 | Val 52.7212 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.7212)
Fold 6: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 74.4983 | Val 34.3039 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.3039)
Fold 7: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 66.2015 | Val 70.5497 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 70.5497)
Fold 8: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 69.7796 | Val 44.7712 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.7712)
Fold 9: TL on cpu | freeze=1 | lr=0.000332455
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 75.9119 | Val 33.4128 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:47,783] Trial 18 finished with value: 47.22681655883789 and parameters: {'learning_rate': 0.0003324551450715378, 'weight_decay': 0.0002861992725405254, 'batch_size': 64, 'dropout_rate': 0.4242921572664685}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.1057)
Fold 0: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.4978 | Val 51.4916 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 53.3770 | Val 50.0508 | ES 2/30
[Fold 0] Epoch  100 | Train 53.7418 | Val 47.4946 | ES 6/30
[Fold 0] Epoch  150 | Train 51.3027 | Val 46.8194 | ES 14/30
[Fold 0] Early stopping at epoch 166 (best Val Loss: 46.3640)
Fold 1: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 67.0630 | Val 57.0275 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.0275)
Fold 2: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 71.0518 | Val 44.8324 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 53.5668 | Val 36.3524 | ES 0/30
[Fold 2] Epoch  100 | Train 49.0010 | Val 30.3688 | ES 5/30
[Fold 2] Epoch  150 | Train 45.8062 | Val 28.4792 | ES 2/30
[Fold 2] Epoch  200 | Train 46.7206 | Val 27.9390 | ES 23/30
[Fold 2] Early stopping at epoch 207 (best Val Loss: 27.5404)
Fold 3: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 69.1355 | Val 60.5081 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.5081)
Fold 4: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 65.9204 | Val 55.0894 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 55.0894)
Fold 5: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch    1 | Train 66.5578 | Val 59.2672 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 59.2672)
Fold 6: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 71.3459 | Val 36.8570 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.8570)
Fold 7: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 69.3921 | Val 73.4335 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 73.4335)
Fold 8: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch    1 | Train 70.7045 | Val 46.2040 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.2040)
Fold 9: TL on cpu | freeze=1 | lr=0.000768763
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 69.5843 | Val 31.7120 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:51,787] Trial 19 finished with value: 49.400322151184085 and parameters: {'learning_rate': 0.0007687631146742076, 'weight_decay': 0.0008623080887412681, 'batch_size': 32, 'dropout_rate': 0.3700182863706169}. Best is trial 0 with value: 46.02029533386231.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.7120)
[freeze_fc1] Best avg RMSE: 46.0203
[freeze_fc1] Best params:  {'learning_rate': 0.0009628679838622033, 'weight_decay': 1.137981512568195e-06, 'batch_size': 32, 'dropout_rate': 0.20509723092012022}
Fold 0: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 67.4081 | Val 52.8138 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 42.9370 | Val 48.0090 | ES 25/30
[Fold 0] Early stopping at epoch 55 (best Val Loss: 46.5320)
Fold 1: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 68.2500 | Val 56.3574 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.3574)
Fold 2: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.1549 | Val 45.2744 | ES 0/30
[Fold 2] Epoch   50 | Train 42.4651 | Val 30.1076 | ES 6/30
[Fold 2] Epoch  100 | Train 36.9587 | Val 25.7272 | ES 6/30
[Fold 2] Early stopping at epoch 124 (best Val Loss: 25.2650)
Fold 3: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 65.0363 | Val 60.8369 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.8369)
Fold 4: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 68.0034 | Val 54.1324 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 54.1324)
Fold 5: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch    1 | Train 70.1636 | Val 59.5281 | ES 0/30
[Fold 5] Epoch   50 | Train 45.9644 | Val 52.5140 | ES 2/30
[Fold 5] Epoch  100 | Train 40.3133 | Val 48.0561 | ES 7/30
[Fold 5] Early stopping at epoch 123 (best Val Loss: 47.3235)
Fold 6: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 68.0749 | Val 35.9830 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 35.9830)
Fold 7: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 67.0770 | Val 72.2009 | ES 0/30
[Fold 7] Epoch   50 | Train 44.8599 | Val 70.4261 | ES 2/30
[Fold 7] Epoch  100 | Train 42.5361 | Val 66.3322 | ES 1/30
[Fold 7] Epoch  150 | Train 36.9404 | Val 66.0203 | ES 17/30
[Fold 7] Early stopping at epoch 183 (best Val Loss: 64.9900)
Fold 8: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 66.8701 | Val 47.2461 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 47.2461)
Fold 9: TL on cpu | freeze=1 | lr=0.000962868
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch    1 | Train 67.7587 | Val 31.2876 | ES 0/30

[I 2026-02-09 21:49:56,449] A new study created in memory with name: no-name-791f982f-6c33-4d81-97da-c4c8e62c9127

[Fold 9] Epoch   50 | Train 51.5298 | Val 31.7414 | ES 9/30
[Fold 9] Early stopping at epoch 82 (best Val Loss: 31.0157)
[freeze_fc1] Best fold: 2 → artifacts/TL_Ro5_no_interaction/freeze_fc1/final_fold_models/fold_2_best.pth

=== Scenario: freeze_fc1_fc2 | freeze=[1, 1, 0] (level=2) ===
Fold 0: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch    1 | Train 67.6315 | Val 56.5676 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 56.5676)
Fold 1: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 70.3586 | Val 65.2501 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 65.2501)
Fold 2: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 73.9584 | Val 52.2320 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 52.2320)
Fold 3: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 68.7455 | Val 73.7221 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 73.7221)
Fold 4: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 69.5220 | Val 64.3743 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 64.3743)
Fold 5: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 71.7015 | Val 66.8068 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 66.8068)
Fold 6: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 72.6289 | Val 41.8321 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 41.8321)
Fold 7: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 68.5159 | Val 73.9102 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 73.9102)
Fold 8: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 72.0125 | Val 51.3917 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 51.3917)
Fold 9: TL on cpu | freeze=2 | lr=0.000134219
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 73.4399 | Val 37.6086 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:49:59,415] Trial 0 finished with value: 58.22902908325195 and parameters: {'learning_rate': 0.00013421854846150204, 'weight_decay': 0.00031356230564360643, 'batch_size': 16, 'dropout_rate': 0.4616789044058852}. Best is trial 0 with value: 58.22902908325195.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 37.6086)
Fold 0: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 68.8032 | Val 58.0095 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 53.9054 | Val 48.2709 | ES 12/30
[Fold 0] Early stopping at epoch 86 (best Val Loss: 46.6939)
Fold 1: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 69.2258 | Val 65.4845 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 54.0392 | Val 61.9373 | ES 4/30
[Fold 1] Epoch  100 | Train 51.7212 | Val 60.1878 | ES 4/30
[Fold 1] Early stopping at epoch 137 (best Val Loss: 59.8398)
Fold 2: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 73.8945 | Val 50.2993 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 55.9501 | Val 31.8136 | ES 2/30
[Fold 2] Epoch  100 | Train 55.6023 | Val 28.9813 | ES 23/30
[Fold 2] Early stopping at epoch 107 (best Val Loss: 28.3629)
Fold 3: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 67.3659 | Val 72.7766 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 51.5335 | Val 70.4614 | ES 13/30
[Fold 3] Epoch  100 | Train 54.5880 | Val 69.3325 | ES 8/30
[Fold 3] Epoch  150 | Train 54.2153 | Val 69.0287 | ES 13/30
[Fold 3] Early stopping at epoch 184 (best Val Loss: 66.6121)
Fold 4: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 66.0492 | Val 63.3042 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 56.5664 | Val 57.3119 | ES 6/30
[Fold 4] Epoch  100 | Train 53.3382 | Val 52.3807 | ES 12/30
[Fold 4] Early stopping at epoch 147 (best Val Loss: 50.7396)
Fold 5: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 68.6797 | Val 69.4532 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 54.4944 | Val 49.1002 | ES 1/30
[Fold 5] Epoch  100 | Train 54.8907 | Val 44.8731 | ES 4/30
[Fold 5] Epoch  150 | Train 50.0819 | Val 44.0079 | ES 2/30
[Fold 5] Early stopping at epoch 178 (best Val Loss: 43.1159)
Fold 6: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 70.7907 | Val 43.2530 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 56.1696 | Val 40.1945 | ES 3/30
[Fold 6] Early stopping at epoch 86 (best Val Loss: 39.9882)
Fold 7: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 66.4668 | Val 73.9945 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 50.1687 | Val 69.5525 | ES 9/30
[Fold 7] Epoch  100 | Train 50.2746 | Val 69.1305 | ES 13/30
[Fold 7] Epoch  150 | Train 49.4585 | Val 68.6939 | ES 21/30
[Fold 7] Early stopping at epoch 159 (best Val Loss: 67.4461)
Fold 8: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.7922 | Val 52.8958 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 54.8760 | Val 40.6467 | ES 0/30
[Fold 8] Epoch  100 | Train 53.1592 | Val 41.1977 | ES 21/30
[Fold 8] Early stopping at epoch 109 (best Val Loss: 40.3007)
Fold 9: TL on cpu | freeze=2 | lr=0.000491036
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 72.0282 | Val 36.0173 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:10,198] Trial 1 finished with value: 47.871954917907715 and parameters: {'learning_rate': 0.0004910362867422751, 'weight_decay': 5.690150531897369e-06, 'batch_size': 16, 'dropout_rate': 0.258377283356505}. Best is trial 1 with value: 47.871954917907715.

[Fold 9] Epoch   50 | Train 54.0663 | Val 34.8902 | ES 26/30
[Fold 9] Early stopping at epoch 54 (best Val Loss: 33.8871)
Fold 0: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 72.5671 | Val 53.1403 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 53.1403)
Fold 1: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 71.2405 | Val 57.0102 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.0102)
Fold 2: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.9201 | Val 45.2661 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.2661)
Fold 3: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 68.2919 | Val 61.5447 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 61.5447)
Fold 4: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 70.7773 | Val 55.0186 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 55.0186)
Fold 5: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 72.0488 | Val 59.5620 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 59.5620)
Fold 6: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 70.5529 | Val 37.1506 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 37.1506)
Fold 7: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 68.8682 | Val 74.5557 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.5557)
Fold 8: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 72.6148 | Val 46.7014 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:11,811] Trial 2 finished with value: 52.17275276184082 and parameters: {'learning_rate': 8.315873671188867e-05, 'weight_decay': 8.268841294999175e-05, 'batch_size': 32, 'dropout_rate': 0.42435224978922287}. Best is trial 1 with value: 47.871954917907715.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.7014)
Fold 9: TL on cpu | freeze=2 | lr=8.31587e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 73.6131 | Val 31.7779 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.7779)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 69.1890 | Val 58.4294 | ES 0/30
[Fold 0] Epoch   50 | Train 61.3944 | Val 56.6152 | ES 1/30
[Fold 0] Epoch  100 | Train 61.5802 | Val 55.9272 | ES 23/30
[Fold 0] Early stopping at epoch 107 (best Val Loss: 53.7157)
Fold 1: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 67.1733 | Val 64.6895 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 64.6895)
Fold 2: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.7141 | Val 55.1086 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 62.9510 | Val 51.2703 | ES 6/30
[Fold 2] Epoch  100 | Train 60.3753 | Val 43.4590 | ES 10/30
[Fold 2] Epoch  150 | Train 58.7428 | Val 40.2887 | ES 19/30
[Fold 2] Early stopping at epoch 161 (best Val Loss: 38.5131)
Fold 3: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 65.8000 | Val 71.9932 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 71.9932)
Fold 4: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 70.4860 | Val 64.1750 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 64.1750)
Fold 5: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 71.2867 | Val 69.8639 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 64.8179 | Val 70.4142 | ES 25/30
[Fold 5] Early stopping at epoch 55 (best Val Loss: 68.4934)
Fold 6: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 71.6309 | Val 42.0134 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 42.0134)
Fold 7: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 65.2814 | Val 70.3995 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 70.3995)
Fold 8: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 68.2685 | Val 52.9580 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 63.1757 | Val 53.3695 | ES 19/30
[Fold 8] Epoch  100 | Train 65.6373 | Val 54.2920 | ES 22/30
[Fold 8] Early stopping at epoch 108 (best Val Loss: 51.6956)
Fold 9: TL on cpu | freeze=2 | lr=0.000175612
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 69.3613 | Val 36.8195 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:17,336] Trial 3 finished with value: 56.111890411376955 and parameters: {'learning_rate': 0.0001756124062747045, 'weight_decay': 2.230472485985352e-05, 'batch_size': 16, 'dropout_rate': 0.2451905126853373}. Best is trial 1 with value: 47.871954917907715.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 36.8195)
Fold 0: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 66.7013 | Val 52.2900 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 52.2900)
Fold 1: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 66.6347 | Val 56.6373 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.6373)
Fold 2: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.1814 | Val 44.3611 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 44.3611)
Fold 3: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 69.0214 | Val 61.2901 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 61.2901)
Fold 4: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 70.4567 | Val 54.8145 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 54.8145)
Fold 5: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 70.9784 | Val 60.2089 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 60.2089)
Fold 6: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 71.9280 | Val 37.0103 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 37.0103)
Fold 7: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 64.6900 | Val 74.3879 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.3879)
Fold 8: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 73.5155 | Val 47.0409 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:18,996] Trial 4 finished with value: 51.98536968231201 and parameters: {'learning_rate': 0.00015189537054712197, 'weight_decay': 0.0005851436178020901, 'batch_size': 32, 'dropout_rate': 0.3416266124912217}. Best is trial 1 with value: 47.871954917907715.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 47.0409)
Fold 9: TL on cpu | freeze=2 | lr=0.000151895
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 71.8889 | Val 31.8127 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.8127)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 71.3224 | Val 58.8984 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 58.8984)
Fold 1: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 69.2550 | Val 66.2918 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 66.2918)
Fold 2: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.8736 | Val 53.6253 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 53.6253)
Fold 3: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 69.3103 | Val 75.4349 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 75.4349)
Fold 4: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.6051 | Val 67.0656 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 67.0656)
Fold 5: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 69.4254 | Val 70.5687 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 70.5687)
Fold 6: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 70.8120 | Val 43.1061 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 43.1061)
Fold 7: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 65.3871 | Val 72.0048 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 72.0048)
Fold 8: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 72.9600 | Val 51.1325 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 51.1325)
Fold 9: TL on cpu | freeze=2 | lr=1.56772e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.6724 | Val 35.5388 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:21,772] Trial 5 finished with value: 59.15126266479492 and parameters: {'learning_rate': 1.5677211955948502e-05, 'weight_decay': 0.0003420594147603651, 'batch_size': 16, 'dropout_rate': 0.3500329658102525}. Best is trial 1 with value: 47.871954917907715.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 35.5388)
Fold 0: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 67.8156 | Val 51.7644 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 51.7644)
Fold 1: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 68.0398 | Val 57.3109 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.3109)
Fold 2: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.7062 | Val 44.4722 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 44.4722)
Fold 3: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 67.4903 | Val 60.3254 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.3254)
Fold 4: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.9210 | Val 53.8635 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 53.8635)
Fold 5: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 69.2289 | Val 59.0278 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 59.0278)
Fold 6: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 71.7375 | Val 36.9326 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.9326)
Fold 7: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 66.8151 | Val 74.5970 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.5970)
Fold 8: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 70.7194 | Val 46.4407 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:23,438] Trial 6 finished with value: 51.6081621170044 and parameters: {'learning_rate': 0.0005153166649120363, 'weight_decay': 0.0002046812811907716, 'batch_size': 32, 'dropout_rate': 0.33575063951895107}. Best is trial 1 with value: 47.871954917907715.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.4407)
Fold 9: TL on cpu | freeze=2 | lr=0.000515317
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 71.1027 | Val 31.3473 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.3473)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 66.8699 | Val 52.3626 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 52.3626)
Fold 1: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch    1 | Train 67.8987 | Val 56.5108 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.5108)
Fold 2: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 72.6433 | Val 45.9202 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.9202)
Fold 3: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 68.1705 | Val 61.0519 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 61.0519)
Fold 4: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 69.0436 | Val 56.6046 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 56.6046)
Fold 5: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 71.1638 | Val 60.1046 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 60.1046)
Fold 6: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 74.5551 | Val 36.6772 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 36.6772)
Fold 7: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 65.4400 | Val 74.6222 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 74.6222)
Fold 8: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 72.4404 | Val 46.8166 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:25,146] Trial 7 finished with value: 52.202603340148926 and parameters: {'learning_rate': 1.61960844590291e-05, 'weight_decay': 0.0006231132326463202, 'batch_size': 32, 'dropout_rate': 0.4297657535925037}. Best is trial 1 with value: 47.871954917907715.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 46.8166)
Fold 9: TL on cpu | freeze=2 | lr=1.61961e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 69.8864 | Val 31.3554 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 31.3554)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 71.2351 | Val 45.0708 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.0708)
Fold 1: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 69.8665 | Val 53.3510 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.3510)
Fold 2: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 68.8947 | Val 38.6716 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.6716)
Fold 3: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 68.9346 | Val 50.5504 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.5504)
Fold 4: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.1660 | Val 45.9751 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.9751)
Fold 5: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 68.9204 | Val 51.8287 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 51.8287)
Fold 6: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 73.8596 | Val 34.5096 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.5096)
Fold 7: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 63.3643 | Val 70.2435 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 70.2435)
Fold 8: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.4429 | Val 45.6979 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 45.6979)
Fold 9: TL on cpu | freeze=2 | lr=0.000460441
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.9824 | Val 33.4698 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:26,396] Trial 8 finished with value: 46.789859771728516 and parameters: {'learning_rate': 0.0004604405113508402, 'weight_decay': 4.1647653263909556e-05, 'batch_size': 64, 'dropout_rate': 0.23053811566498053}. Best is trial 8 with value: 46.789859771728516.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.0001)
Fold 0: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 67.3274 | Val 45.3484 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.3484)
Fold 1: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 67.5656 | Val 53.1235 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.1235)
Fold 2: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.0004 | Val 38.4417 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.4417)
Fold 3: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 67.2283 | Val 51.4402 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 51.4402)
Fold 4: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 66.9222 | Val 45.6050 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.6050)
Fold 5: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 66.0158 | Val 51.8804 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 51.8804)
Fold 6: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 72.8104 | Val 34.3963 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.3963)
Fold 7: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 62.3320 | Val 70.0063 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 70.0063)
Fold 8: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 69.3325 | Val 44.5801 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.5801)
Fold 9: TL on cpu | freeze=2 | lr=5.32712e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 69.2815 | Val 34.2182 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:27,583] Trial 9 finished with value: 46.7341968536377 and parameters: {'learning_rate': 5.327119587839548e-05, 'weight_decay': 2.521769747345151e-05, 'batch_size': 64, 'dropout_rate': 0.26367934748574634}. Best is trial 9 with value: 46.7341968536377.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.5200)
Fold 0: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 64.2271 | Val 44.6136 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 44.6136)
Fold 1: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 69.3443 | Val 53.5229 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.5229)
Fold 2: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.8851 | Val 38.8052 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.8052)
Fold 3: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 67.7501 | Val 49.5455 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 49.5455)
Fold 4: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.3638 | Val 46.1613 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 46.1613)
Fold 5: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 68.8357 | Val 52.2899 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.2899)
Fold 6: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 67.9922 | Val 34.4643 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.4643)
Fold 7: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 61.8902 | Val 68.9903 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 68.9903)
Fold 8: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 69.1652 | Val 44.7203 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.7203)
Fold 9: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 68.6781 | Val 33.6185 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:28,832] Trial 10 finished with value: 46.48822135925293 and parameters: {'learning_rate': 3.9339113330737946e-05, 'weight_decay': 1.598817723319727e-06, 'batch_size': 64, 'dropout_rate': 0.20058952180402873}. Best is trial 10 with value: 46.48822135925293.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.7688)
Fold 0: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 71.1345 | Val 45.6056 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.6056)
Fold 1: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 69.8549 | Val 53.6131 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.6131)
Fold 2: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.3205 | Val 38.7927 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.7927)
Fold 3: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 66.9521 | Val 50.8173 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.8173)
Fold 4: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 66.9643 | Val 45.7603 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.7603)
Fold 5: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 65.0008 | Val 51.7440 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 51.7440)
Fold 6: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 67.9349 | Val 34.6152 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.6152)
Fold 7: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 63.0675 | Val 69.5525 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.5525)
Fold 8: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 70.4750 | Val 45.4888 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 45.4888)
Fold 9: TL on cpu | freeze=2 | lr=4.45676e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 69.1543 | Val 34.1980 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:30,025] Trial 11 finished with value: 46.843980407714845 and parameters: {'learning_rate': 4.456758914131068e-05, 'weight_decay': 1.4817996038760014e-06, 'batch_size': 64, 'dropout_rate': 0.20458193063715605}. Best is trial 10 with value: 46.48822135925293.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.4501)
Fold 0: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 68.0396 | Val 45.2900 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.2900)
Fold 1: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 62.7890 | Val 53.1719 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.1719)
Fold 2: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 68.4935 | Val 38.5265 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.5265)
Fold 3: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 65.9170 | Val 49.5812 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 49.5812)
Fold 4: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 69.9893 | Val 45.5315 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.5315)
Fold 5: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 65.3713 | Val 51.7168 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 51.7168)
Fold 6: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 65.1358 | Val 34.4108 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.4108)
Fold 7: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 62.3740 | Val 69.7159 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.7159)
Fold 8: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 69.5227 | Val 45.0199 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 45.0199)
Fold 9: TL on cpu | freeze=2 | lr=4.15124e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 68.9411 | Val 34.2708 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:31,260] Trial 12 finished with value: 46.53207588195801 and parameters: {'learning_rate': 4.1512355482048825e-05, 'weight_decay': 1.09214902438195e-06, 'batch_size': 64, 'dropout_rate': 0.28884467777690614}. Best is trial 10 with value: 46.48822135925293.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.3564)
Fold 0: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 67.9020 | Val 45.8308 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.8308)
Fold 1: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 69.6219 | Val 53.7896 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.7896)
Fold 2: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 72.2891 | Val 38.6989 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.6989)
Fold 3: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 68.5352 | Val 49.4132 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 49.4132)
Fold 4: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 63.9647 | Val 45.9793 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.9793)
Fold 5: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 67.1589 | Val 52.3255 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.3255)
Fold 6: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 69.4465 | Val 34.2913 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.2913)
Fold 7: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 67.0788 | Val 70.1707 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 70.1707)
Fold 8: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 67.0183 | Val 44.9756 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.9756)
Fold 9: TL on cpu | freeze=2 | lr=3.32368e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 69.5526 | Val 33.6139 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:32,442] Trial 13 finished with value: 46.714207077026366 and parameters: {'learning_rate': 3.323678015788805e-05, 'weight_decay': 1.0797966763712893e-06, 'batch_size': 64, 'dropout_rate': 0.29329390119076737}. Best is trial 10 with value: 46.48822135925293.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.6671)
Fold 0: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 69.2959 | Val 45.9199 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.9199)
Fold 1: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 69.4090 | Val 53.5162 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.5162)
Fold 2: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 66.3975 | Val 38.2975 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.2975)
Fold 3: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 66.8057 | Val 50.6462 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.6462)
Fold 4: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 65.3175 | Val 45.7882 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.7882)
Fold 5: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 67.3864 | Val 51.9788 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 51.9788)
Fold 6: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 71.5440 | Val 34.3316 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.3316)
Fold 7: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 64.1160 | Val 69.5594 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.5594)
Fold 8: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 69.3736 | Val 44.7136 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.7136)
Fold 9: TL on cpu | freeze=2 | lr=2.57623e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.7313 | Val 34.3117 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:33,630] Trial 14 finished with value: 46.6768684387207 and parameters: {'learning_rate': 2.576230182424054e-05, 'weight_decay': 3.624995624034397e-06, 'batch_size': 64, 'dropout_rate': 0.3023343654901051}. Best is trial 10 with value: 46.48822135925293.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.0173)
Fold 0: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 65.5801 | Val 45.4908 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.4908)
Fold 1: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 72.0304 | Val 53.5560 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.5560)
Fold 2: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 68.0606 | Val 38.6329 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.6329)
Fold 3: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 67.7308 | Val 50.1683 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.1683)
Fold 4: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 64.2193 | Val 46.1362 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 46.1362)
Fold 5: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 70.9693 | Val 52.3009 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.3009)
Fold 6: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 71.1156 | Val 34.5906 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.5906)
Fold 7: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 67.1720 | Val 69.9255 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.9255)
Fold 8: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.7314 | Val 44.5172 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:34,864] Trial 15 finished with value: 46.759897994995114 and parameters: {'learning_rate': 6.890012698907764e-05, 'weight_decay': 5.666793599654902e-06, 'batch_size': 64, 'dropout_rate': 0.20284103957393818}. Best is trial 10 with value: 46.48822135925293.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.5172)
Fold 9: TL on cpu | freeze=2 | lr=6.89001e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.8338 | Val 33.7941 | ES 0/30
[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.2806)
Fold 0: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 70.4379 | Val 45.7488 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.7488)
Fold 1: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 74.0858 | Val 53.4597 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.4597)
Fold 2: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.9017 | Val 38.5523 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.5523)
Fold 3: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 65.9827 | Val 51.4862 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 51.4862)
Fold 4: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 65.5388 | Val 46.3565 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 46.3565)
Fold 5: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 70.9785 | Val 52.1939 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.1939)
Fold 6: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 74.2122 | Val 34.4041 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.4041)
Fold 7: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 68.5615 | Val 69.9673 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.9673)
Fold 8: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 70.8518 | Val 44.6140 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:36,111] Trial 16 finished with value: 46.837959098815915 and parameters: {'learning_rate': 1.0058063206517361e-05, 'weight_decay': 2.6817770372861226e-06, 'batch_size': 64, 'dropout_rate': 0.38012540197809025}. Best is trial 10 with value: 46.48822135925293.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.6140)
Fold 9: TL on cpu | freeze=2 | lr=1.00581e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 68.6826 | Val 33.7221 | ES 0/30
[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.5969)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 69.3496 | Val 45.5547 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.5547)
Fold 1: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 74.6121 | Val 53.8938 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.8938)
Fold 2: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 68.7582 | Val 39.0704 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 39.0704)
Fold 3: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 63.0703 | Val 51.3205 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 51.3205)
Fold 4: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.3712 | Val 45.9160 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.9160)
Fold 5: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 67.5996 | Val 52.0137 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.0137)
Fold 6: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 69.9246 | Val 34.3921 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.3921)
Fold 7: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 60.4328 | Val 69.8610 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.8610)
Fold 8: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 67.0330 | Val 44.6824 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.6824)
Fold 9: TL on cpu | freeze=2 | lr=2.61354e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 74.3143 | Val 33.7976 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:37,314] Trial 17 finished with value: 46.85515460968018 and parameters: {'learning_rate': 2.6135392516411497e-05, 'weight_decay': 1.097145071565124e-05, 'batch_size': 64, 'dropout_rate': 0.2970769397093145}. Best is trial 10 with value: 46.48822135925293.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.8470)
Fold 0: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 68.0679 | Val 44.9143 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 44.9143)
Fold 1: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 72.4494 | Val 53.4315 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.4315)
Fold 2: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.4702 | Val 38.5539 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.5539)
Fold 3: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 66.3652 | Val 50.6666 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.6666)
Fold 4: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.8506 | Val 46.5415 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 46.5415)
Fold 5: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 67.8006 | Val 52.2939 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.2939)
Fold 6: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 70.0144 | Val 34.4338 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.4338)
Fold 7: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 64.9748 | Val 69.9093 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.9093)
Fold 8: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.4578 | Val 43.8197 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 43.8197)
Fold 9: TL on cpu | freeze=2 | lr=0.000260891
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 71.2898 | Val 33.5234 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:38,540] Trial 18 finished with value: 46.63879947662353 and parameters: {'learning_rate': 0.0002608908024745598, 'weight_decay': 1.9050053575030398e-06, 'batch_size': 64, 'dropout_rate': 0.3851003814257453}. Best is trial 10 with value: 46.48822135925293.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.8236)
Fold 0: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 68.9584 | Val 46.1580 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 46.1580)
Fold 1: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 75.2549 | Val 53.1329 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.1329)
Fold 2: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 74.5798 | Val 39.2884 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 39.2884)
Fold 3: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 70.8208 | Val 52.7980 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 52.7980)
Fold 4: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.5750 | Val 47.4424 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 47.4424)
Fold 5: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 73.4440 | Val 53.2576 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 53.2576)
Fold 6: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 75.8132 | Val 34.1591 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.1591)
Fold 7: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 64.0599 | Val 71.0516 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 71.0516)
Fold 8: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 69.5438 | Val 44.8286 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.8286)
Fold 9: TL on cpu | freeze=2 | lr=4.13069e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 73.8871 | Val 33.7214 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-09 21:50:39,716] Trial 19 finished with value: 47.37855472564697 and parameters: {'learning_rate': 4.130690978904423e-05, 'weight_decay': 1.0020172157795665e-06, 'batch_size': 64, 'dropout_rate': 0.49531253088309535}. Best is trial 10 with value: 46.48822135925293.

[Fold 9] Early stopping at epoch 32 (best Val Loss: 31.6689)
[freeze_fc1_fc2] Best avg RMSE: 46.4882
[freeze_fc1_fc2] Best params:  {'learning_rate': 3.9339113330737946e-05, 'weight_decay': 1.598817723319727e-06, 'batch_size': 64, 'dropout_rate': 0.20058952180402873}
Fold 0: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 72.6726 | Val 45.5298 | ES 0/30
[Fold 0] Early stopping at epoch 31 (best Val Loss: 45.5298)
Fold 1: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 64.4863 | Val 53.3721 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 53.3721)
Fold 2: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.1968 | Val 38.6333 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 38.6333)
Fold 3: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 65.5244 | Val 50.5140 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 50.5140)
Fold 4: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 63.9181 | Val 45.8936 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 45.8936)
Fold 5: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 70.2622 | Val 52.0737 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 52.0737)
Fold 6: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 69.9091 | Val 34.7433 | ES 0/30
[Fold 6] Early stopping at epoch 31 (best Val Loss: 34.7433)
Fold 7: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 67.8190 | Val 69.5231 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 69.5231)
Fold 8: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 70.5202 | Val 44.8378 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 44.8378)
Fold 9: TL on cpu | freeze=2 | lr=3.93391e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 68.3684 | Val 33.8248 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Early stopping at epoch 32 (best Val Loss: 32.2158)
[freeze_fc1_fc2] Best fold: 9 → artifacts/TL_Ro5_no_interaction/freeze_fc1_fc2/final_fold_models/fold_9_best.pth

Summary: {
  "no_freeze": {
    "best": 44.137620544433595,
    "manifest": {
      "scenario": "no_freeze",
      "freeze_vector": [
        0,
        0,
        0
      ],
      "freeze_level": 0,
      "best_fold": 2,
      "checkpoint": "artifacts/TL_Ro5_no_interaction/no_freeze/final_fold_models/fold_2_best.pth",
      "hidden_layers": [
        192,
        96,
        48
      ],
      "best_params": {
        "learning_rate": 0.0004408716160521325,
        "weight_decay": 5.152851369559039e-05,
        "batch_size": 16,
        "dropout_rate": 0.23141264074960805
      }
    }
  },
  "freeze_fc1": {
    "best": 46.02029533386231,
    "manifest": {
      "scenario": "freeze_fc1",
      "freeze_vector": [
        1,
        0,
        0
      ],
      "freeze_level": 1,
      "best_fold": 2,
      "checkpoint": "artifacts/TL_Ro5_no_interaction/freeze_fc1/final_fold_models/fold_2_best.pth",
      "hidden_layers": [
        192,
        96,
        48
      ],
      "best_params": {
        "learning_rate": 0.0009628679838622033,
        "weight_decay": 1.137981512568195e-06,
        "batch_size": 32,
        "dropout_rate": 0.20509723092012022
      }
    }
  },
  "freeze_fc1_fc2": {
    "best": 46.48822135925293,
    "manifest": {
      "scenario": "freeze_fc1_fc2",
      "freeze_vector": [
        1,
        1,
        0
      ],
      "freeze_level": 2,
      "best_fold": 9,
      "checkpoint": "artifacts/TL_Ro5_no_interaction/freeze_fc1_fc2/final_fold_models/fold_9_best.pth",
      "hidden_layers": [
        192,
        96,
        48
      ],
      "best_params": {
        "learning_rate": 3.9339113330737946e-05,
        "weight_decay": 1.598817723319727e-06,
        "batch_size": 64,
        "dropout_rate": 0.20058952180402873
      }
    }
  }
}

In [9]:
from NN_model import ImprovedNN
import torch
import pandas as pd
from pathlib import Path
import json

def load_best_models_for_scenarios(
    root_dir="artifacts/TL_Ro5_no_interaction",
    scenarios=("no_freeze", "freeze_fc1", "freeze_fc1_fc2"),
):
    root_dir = Path(root_dir)
    models = {}
    manifests = {}

    for tag in scenarios:
        manifest_path = root_dir / tag / "manifest.json"
        cv_metrics_path = root_dir / tag / "cv_final_metrics.csv"

        # Load manifest
        with open(manifest_path, "r") as f:
            manifest = json.load(f)
        manifests[tag] = manifest

        # Load best RMSE from cv_final_metrics.csv
        cv_df = pd.read_csv(cv_metrics_path)
        best_row = cv_df.sort_values("rmse").iloc[0]
        best_rmse = float(best_row["rmse"])

        # Load checkpoint
        ckpt_path = Path(best_row["checkpoint"]).resolve()
        state = torch.load(ckpt_path, map_location="cpu")

        # Build model
        input_size = state["network.0.weight"].shape[1]
        hidden_layers = manifest["hidden_layers"]
        dropout_rate = manifest["best_params"]["dropout_rate"]

        model = ImprovedNN(
            input_size=input_size,
            hidden_layers=hidden_layers,
            dropout_rate=dropout_rate,
        )
        model.load_state_dict(state)
        model.eval()

        models[tag] = model

        print(f"Loaded model for scenario '{tag}'")
        print(f"  └─ Best fold checkpoint: {ckpt_path}")
        print(f"  └─ Best RMSE: {best_rmse:.4f}\n")

    return models, manifests

models, manifests = load_best_models_for_scenarios(
    root_dir="artifacts/TL_Ro5_no_interaction",
    scenarios=["no_freeze", "freeze_fc1", "freeze_fc1_fc2"]
)

Loaded model for scenario 'no_freeze'
  └─ Best fold checkpoint: /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/TL_Ro5_no_interaction/no_freeze/final_fold_models/fold_2_best.pth
  └─ Best RMSE: 28.9620

Loaded model for scenario 'freeze_fc1'
  └─ Best fold checkpoint: /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/TL_Ro5_no_interaction/freeze_fc1/final_fold_models/fold_2_best.pth
  └─ Best RMSE: 25.2650

Loaded model for scenario 'freeze_fc1_fc2'
  └─ Best fold checkpoint: /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/TL_Ro5_no_interaction/freeze_fc1_fc2/final_fold_models/fold_9_best.pth
  └─ Best RMSE: 32.2158

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_61633/2999602402.py:31: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(ckpt_path, map_location="cpu")
/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_61633/2999602402.py:31: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(ckpt_path, map_location="cpu")
/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_61633/2999602402.py:31: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(ckpt_path, map_location="cpu")

In [10]:
import pandas as pd
from pathlib import Path

def print_rmse_all_folds(
    root_dir="artifacts/TL_Ro5_no_interaction",
    scenarios=("no_freeze", "freeze_fc1", "freeze_fc1_fc2"),
):
    root_dir = Path(root_dir)

    for tag in scenarios:
        cv_metrics_path = root_dir / tag / "cv_final_metrics.csv"

        if not cv_metrics_path.exists():
            print(f"[WARN] Missing CV metrics for scenario '{tag}'")
            continue

        cv_df = pd.read_csv(cv_metrics_path)

        print(f"\nScenario: {tag}")
        print("-" * (10 + len(tag)))

        # Expecting columns like: fold, rmse, r2, q2, checkpoint, ...
        for _, row in cv_df.iterrows():
            fold = row.get("fold", "N/A")
            rmse = row["rmse"]
            print(f"  Fold {fold}: RMSE = {rmse:.4f}")

        print(f"  Mean RMSE: {cv_df['rmse'].mean():.4f}")
        print(f"  Std  RMSE: {cv_df['rmse'].std():.4f}")

# Run it
print_rmse_all_folds(
    root_dir="artifacts/TL_Ro5_no_interaction",
    scenarios=["no_freeze", "freeze_fc1", "freeze_fc1_fc2"]
)

Scenario: no_freeze
-------------------
  Fold 2: RMSE = 28.9620
  Fold 9: RMSE = 30.5112
  Fold 6: RMSE = 34.8829
  Fold 8: RMSE = 43.7701
  Fold 0: RMSE = 44.3762
  Fold 5: RMSE = 46.0855
  Fold 4: RMSE = 47.4786
  Fold 1: RMSE = 47.6129
  Fold 3: RMSE = 58.7672
  Fold 7: RMSE = 59.2791
  Mean RMSE: 44.1726
  Std  RMSE: 10.3930

Scenario: freeze_fc1
--------------------
  Fold 2: RMSE = 25.2650
  Fold 9: RMSE = 31.0157
  Fold 6: RMSE = 35.9830
  Fold 0: RMSE = 46.5320
  Fold 8: RMSE = 47.2461
  Fold 5: RMSE = 47.3235
  Fold 4: RMSE = 54.1324
  Fold 1: RMSE = 56.3574
  Fold 3: RMSE = 60.8369
  Fold 7: RMSE = 64.9900
  Mean RMSE: 46.9682
  Std  RMSE: 12.9237

Scenario: freeze_fc1_fc2
------------------------
  Fold 9: RMSE = 32.2158
  Fold 6: RMSE = 34.7433
  Fold 2: RMSE = 38.6333
  Fold 8: RMSE = 44.8378
  Fold 0: RMSE = 45.5298
  Fold 4: RMSE = 45.8936
  Fold 3: RMSE = 50.5140
  Fold 5: RMSE = 52.0737
  Fold 1: RMSE = 53.3721
  Fold 7: RMSE = 69.5231
  Mean RMSE: 46.7337
  Std  RMSE: 10.7090

In [11]:
import sys
# classifier/ → MELTING_POINT_2026/
PROJECT_ROOT = Path.cwd().parent        # directory above a path: .../MELTING_POINT_2026

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

test_path = PROJECT_ROOT / "Ro5" / "artifacts" / "full_test_scaled_no_interaction.parquet"
df_test = pd.read_parquet(test_path)

df_test.head()

,SMILES,MP,Type,Ro5,RDKit_SMR_VSA2,RDKit_Kappa2,MACCS_41,RDKit_SMR_VSA6,RDKit_SlogP_VSA5,RDKit_VSA_EState7,...,RDKit_fr_Ar_NH,RDKit_Chi4n,RDKit_PEOE_VSA12,RDKit_NumAliphaticRings,MACCS_101,RDKit_TPSA,RDKit_fr_ArN,RDKit_fr_SH,RDKit_NumHeteroatoms,Structure_Cluster
0,[O-][N+](=O)c1c(C)c(C(=O)C)c(c(c1C(C)(C)C)[N+]...,135.5,Test,1,-0.239453,0.035665,-0.247167,-0.670027,1.372242,-0.326855,...,-0.199183,0.467617,-0.434742,-0.504875,-0.618592,1.469587,-0.268728,-0.07374,0.941386,0
1,CN(NC(=O)CCC(=O)O)C,154.5,Test,1,-0.239453,-0.135213,-0.247167,0.850738,-0.302526,-0.348069,...,-0.199183,-0.823819,1.156820,-0.504875,-0.618592,0.507304,-0.268728,-0.07374,0.215195,2
2,CCCCc1ccc(cc1)NC(=O)Oc1ccc(cc1)OC,143.0,Test,1,-0.239453,0.908580,-0.247167,0.670693,0.196575,0.265272,...,-0.199183,0.069489,-0.434742,-0.504875,-0.618592,-0.122990,-0.268728,-0.07374,-0.147901,2
3,OC(=O)COCCN1C(=O)c2c(C1=O)cccc2,128.0,Test,1,-0.239453,-0.044857,-0.247167,1.461745,0.012203,-0.326855,...,-0.199183,-0.092230,-0.434742,0.444098,1.616573,0.914654,-0.268728,-0.07374,0.578291,0
4,CCCCCCCCCCCCCCC,10.0,Test,1,-0.239453,2.727335,-0.247167,-0.670027,3.073919,3.533921,...,-0.199183,0.105820,-0.434742,-0.504875,-0.618592,-1.480633,-0.268728,-0.07374,-1.600284,5

In [1]:
from pathlib import Path
import numpy as np
import pandas as pd
import torch
import joblib

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from NN_model import ImprovedNN  # adjust if needed

# --------------------
# PATHS
# --------------------
BASE = Path.cwd()  # wherever your notebook is running
CKPT_PTH = BASE / "artifacts/TL_Ro5/no_freeze/final_fold_models/fold_9_best.pth"

TEST_SCALED = BASE / "artifacts/df_test_scaled.parquet"   # <-- adjust to your actual location
OUT_PRED_CSV = BASE / "artifacts/test_TL_Ro5_predictions.csv"

# --------------------
# MODEL PARAMETERS (must match checkpoint architecture)
# --------------------
HIDDEN_LAYERS = [224, 112, 56]
DROPOUT_RATE = 0.31955324794371087  # must match best params used for that checkpoint

# --------------------
# Load scaled test set
# --------------------
df_test = pd.read_parquet(TEST_SCALED)

NON_FEATURES = ["SMILES", "MP", "Type", "Ro5"]
feature_cols = [c for c in df_test.columns if c not in NON_FEATURES]
feature_cols = [c for c in feature_cols if pd.api.types.is_numeric_dtype(df_test[c])]


X_test = df_test[feature_cols].to_numpy(dtype=np.float32)
y_true = df_test["MP"].to_numpy(dtype=float)
smiles = df_test["SMILES"].astype(str).to_numpy()

print("Test rows:", len(df_test))
print("Features:", X_test.shape[1])

# --------------------
# Recreate model + load checkpoint
# --------------------
device = torch.device("cpu")

model = ImprovedNN(
    input_size=X_test.shape[1],
    hidden_layers=HIDDEN_LAYERS,
    dropout_rate=DROPOUT_RATE
).to(device)

loaded = torch.load(CKPT_PTH, map_location=device)

if isinstance(loaded, dict) and "model_state_dict" in loaded:
    model.load_state_dict(loaded["model_state_dict"], strict=True)
else:
    model.load_state_dict(loaded, strict=True)

model.eval()

# --------------------
# Predict
# --------------------
X_tensor = torch.tensor(X_test, dtype=torch.float32, device=device)

with torch.no_grad():
    y_pred = model(X_tensor).squeeze().cpu().numpy().astype(float)

# --------------------
# Evaluate
# --------------------
rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
mae  = float(mean_absolute_error(y_true, y_pred))
r2   = float(r2_score(y_true, y_pred))

print("\n=== TEST METRICS ===")
print(f"RMSE: {rmse:.4f}")
print(f"MAE : {mae:.4f}")
print(f"R^2 : {r2:.4f}")

# --------------------
# Save predictions
# --------------------
out_df = pd.DataFrame({
    "SMILES": smiles,
    "Type": df_test["Type"].astype(str).to_numpy(),
    "Ro5": df_test["Ro5"].to_numpy(),
    "exp MP": y_true,
    "pred MP": y_pred,
    "error": y_pred - y_true,
    "abs_error": np.abs(y_pred - y_true),
})

OUT_PRED_CSV.parent.mkdir(parents=True, exist_ok=True)
out_df.to_csv(OUT_PRED_CSV, index=False)
print(f"\nSaved predictions -> {OUT_PRED_CSV}")

Test rows: 5166
Features: 118

=== TEST METRICS ===
RMSE: 47.3295
MAE : 37.7536
R^2 : 0.5580

Saved predictions -> /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/test_TL_Ro5_predictions.csv

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_61109/889717099.py:53: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded = torch.load(CKPT_PTH, map_location=device)

In [2]:
import pandas as pd
out_df = pd.read_csv("/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/test_TL_Ro5_predictions.csv")

rmse_total = np.sqrt(np.mean(out_df["error"] ** 2))
print(f"Total RMSE (all): {rmse_total:.3f}")

df_ro5 = out_df[out_df["Ro5"] == 1]
rmse_ro5 = np.sqrt(np.mean(df_ro5["error"] ** 2))
print(f"RMSE (Ro5): {rmse_ro5:.3f}")

df_bro5 = out_df[out_df["Ro5"] == 0]
rmse_bro5 = np.sqrt(np.mean(df_bro5["error"] ** 2))
print(f"RMSE (bRo5): {rmse_bro5:.3f}")

Total RMSE (all): 47.329
RMSE (Ro5): 47.304
RMSE (bRo5): 48.504

In [3]:

from pathlib import Path
import numpy as np
import pandas as pd
import torch
import joblib

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from NN_model import ImprovedNN  # adjust if needed

# --------------------
# PATHS
# --------------------
BASE = Path.cwd()  # wherever your notebook is running
CKPT_PTH = BASE / "artifacts/TL_Ro5/freeze_fc1_fc2/final_fold_models/fold_9_best.pth"

TEST_SCALED = BASE / "artifacts/df_test_scaled.parquet"   # <-- adjust to your actual location
OUT_PRED_CSV = BASE / "artifacts/test_TL_Ro5_freeze_fc1_fc2_predictions.csv"

# --------------------
# MODEL PARAMETERS (must match checkpoint architecture)
# --------------------
HIDDEN_LAYERS = [224, 112, 56]
DROPOUT_RATE = 0.31955324794371087  # must match best params used for that checkpoint

# --------------------
# Load scaled test set
# --------------------
df_test = pd.read_parquet(TEST_SCALED)

NON_FEATURES = ["SMILES", "MP", "Type", "Ro5"]
feature_cols = [c for c in df_test.columns if c not in NON_FEATURES]
feature_cols = [c for c in feature_cols if pd.api.types.is_numeric_dtype(df_test[c])]

# Optional: enforce deterministic order (better: load exact feature list from training manifest)
#feature_cols = sorted(feature_cols)

X_test = df_test[feature_cols].to_numpy(dtype=np.float32)
y_true = df_test["MP"].to_numpy(dtype=float)
smiles = df_test["SMILES"].astype(str).to_numpy()

print("Test rows:", len(df_test))
print("Features:", X_test.shape[1])

# --------------------
# Recreate model + load checkpoint
# --------------------
device = torch.device("cpu")

model = ImprovedNN(
    input_size=X_test.shape[1],
    hidden_layers=HIDDEN_LAYERS,
    dropout_rate=DROPOUT_RATE
).to(device)

loaded = torch.load(CKPT_PTH, map_location=device)

if isinstance(loaded, dict) and "model_state_dict" in loaded:
    model.load_state_dict(loaded["model_state_dict"], strict=True)
else:
    model.load_state_dict(loaded, strict=True)

model.eval()

# --------------------
# Predict
# --------------------
X_tensor = torch.tensor(X_test, dtype=torch.float32, device=device)

with torch.no_grad():
    y_pred = model(X_tensor).squeeze().cpu().numpy().astype(float)

# --------------------
# Evaluate
# --------------------
rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
mae  = float(mean_absolute_error(y_true, y_pred))
r2   = float(r2_score(y_true, y_pred))

print("\n=== TEST METRICS ===")
print(f"RMSE: {rmse:.4f}")
print(f"MAE : {mae:.4f}")
print(f"R^2 : {r2:.4f}")

# --------------------
# Save predictions
# --------------------
out_df = pd.DataFrame({
    "SMILES": smiles,
    "Type": df_test["Type"].astype(str).to_numpy(),
    "Ro5": df_test["Ro5"].to_numpy(),
    "exp MP": y_true,
    "pred MP": y_pred,
    "error": y_pred - y_true,
    "abs_error": np.abs(y_pred - y_true),
})

OUT_PRED_CSV.parent.mkdir(parents=True, exist_ok=True)
out_df.to_csv(OUT_PRED_CSV, index=False)
print(f"\nSaved predictions -> {OUT_PRED_CSV}")

Test rows: 5166
Features: 118

=== TEST METRICS ===
RMSE: 48.7401
MAE : 39.9270
R^2 : 0.5312

Saved predictions -> /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/test_TL_Ro5_freeze_fc1_fc2_predictions.csv

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_61109/120300737.py:55: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded = torch.load(CKPT_PTH, map_location=device)

In [4]:
import pandas as pd
out_df = pd.read_csv("/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/test_TL_Ro5_freeze_fc1_fc2_predictions.csv")

rmse_total = np.sqrt(np.mean(out_df["error"] ** 2))
print(f"Total RMSE (all): {rmse_total:.3f}")

df_ro5 = out_df[out_df["Ro5"] == 1]
rmse_ro5 = np.sqrt(np.mean(df_ro5["error"] ** 2))
print(f"RMSE (Ro5): {rmse_ro5:.3f}")

df_bro5 = out_df[out_df["Ro5"] == 0]
rmse_bro5 = np.sqrt(np.mean(df_bro5["error"] ** 2))
print(f"RMSE (bRo5): {rmse_bro5:.3f}")

Total RMSE (all): 48.740
RMSE (Ro5): 48.679
RMSE (bRo5): 51.489

In [5]:

from pathlib import Path
import numpy as np
import pandas as pd
import torch
import joblib

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from NN_model import ImprovedNN  # adjust if needed

# --------------------
# PATHS
# --------------------
BASE = Path.cwd()  # wherever your notebook is running
CKPT_PTH = BASE / "artifacts/TL_Ro5/freeze_fc1/final_fold_models/fold_9_best.pth"

TEST_SCALED = BASE / "artifacts/df_test_scaled.parquet"   # <-- adjust to your actual location
OUT_PRED_CSV = BASE / "artifacts/test_TL_Ro5_freeze_fc1_predictions.csv"

# --------------------
# MODEL PARAMETERS (must match checkpoint architecture)
# --------------------
HIDDEN_LAYERS = [224, 112, 56]
DROPOUT_RATE = 0.31955324794371087  # must match best params used for that checkpoint

# --------------------
# Load scaled test set
# --------------------
df_test = pd.read_parquet(TEST_SCALED)

NON_FEATURES = ["SMILES", "MP", "Type", "Ro5"]
feature_cols = [c for c in df_test.columns if c not in NON_FEATURES]
feature_cols = [c for c in feature_cols if pd.api.types.is_numeric_dtype(df_test[c])]

# Optional: enforce deterministic order (better: load exact feature list from training manifest)
#feature_cols = sorted(feature_cols)

X_test = df_test[feature_cols].to_numpy(dtype=np.float32)
y_true = df_test["MP"].to_numpy(dtype=float)
smiles = df_test["SMILES"].astype(str).to_numpy()

print("Test rows:", len(df_test))
print("Features:", X_test.shape[1])

# --------------------
# Recreate model + load checkpoint
# --------------------
device = torch.device("cpu")

model = ImprovedNN(
    input_size=X_test.shape[1],
    hidden_layers=HIDDEN_LAYERS,
    dropout_rate=DROPOUT_RATE
).to(device)

loaded = torch.load(CKPT_PTH, map_location=device)

if isinstance(loaded, dict) and "model_state_dict" in loaded:
    model.load_state_dict(loaded["model_state_dict"], strict=True)
else:
    model.load_state_dict(loaded, strict=True)

model.eval()

# --------------------
# Predict
# --------------------
X_tensor = torch.tensor(X_test, dtype=torch.float32, device=device)

with torch.no_grad():
    y_pred = model(X_tensor).squeeze().cpu().numpy().astype(float)

# --------------------
# Evaluate
# --------------------
rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
mae  = float(mean_absolute_error(y_true, y_pred))
r2   = float(r2_score(y_true, y_pred))

print("\n=== TEST METRICS ===")
print(f"RMSE: {rmse:.4f}")
print(f"MAE : {mae:.4f}")
print(f"R^2 : {r2:.4f}")

# --------------------
# Save predictions
# --------------------
out_df = pd.DataFrame({
    "SMILES": smiles,
    "Type": df_test["Type"].astype(str).to_numpy(),
    "Ro5": df_test["Ro5"].to_numpy(),
    "exp MP": y_true,
    "pred MP": y_pred,
    "error": y_pred - y_true,
    "abs_error": np.abs(y_pred - y_true),
})

OUT_PRED_CSV.parent.mkdir(parents=True, exist_ok=True)
out_df.to_csv(OUT_PRED_CSV, index=False)
print(f"\nSaved predictions -> {OUT_PRED_CSV}")

Test rows: 5166
Features: 118

=== TEST METRICS ===
RMSE: 45.6578
MAE : 36.6763
R^2 : 0.5886

Saved predictions -> /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/test_TL_Ro5_freeze_fc1_predictions.csv

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_61109/3113043937.py:55: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded = torch.load(CKPT_PTH, map_location=device)

In [6]:
import pandas as pd
out_df = pd.read_csv("/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/test_TL_Ro5_freeze_fc1_predictions.csv")

rmse_total = np.sqrt(np.mean(out_df["error"] ** 2))
print(f"Total RMSE (all): {rmse_total:.3f}")

df_ro5 = out_df[out_df["Ro5"] == 1]
rmse_ro5 = np.sqrt(np.mean(df_ro5["error"] ** 2))
print(f"RMSE (Ro5): {rmse_ro5:.3f}")

df_bro5 = out_df[out_df["Ro5"] == 0]
rmse_bro5 = np.sqrt(np.mean(df_bro5["error"] ** 2))
print(f"RMSE (bRo5): {rmse_bro5:.3f}")

Total RMSE (all): 45.658
RMSE (Ro5): 45.564
RMSE (bRo5): 49.768