In [13]:
from NN_model_helper import (evaluate_fold_TL, set_freeze_mode, plot_training_progress, find_optimal_clusters)
from pathlib import Path
import sys
import pandas as pd
from sklearn.model_selection import StratifiedKFold
import numpy as np
from NN_model import ImprovedNN

In [4]:
# classifier/ → MELTING_POINT_2026/
PROJECT_ROOT = Path.cwd().parent        # directory above a path: .../MELTING_POINT_2026

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

train_path = PROJECT_ROOT / "Ro5" / "artifacts" / "train_scaled_bRo5.parquet"
df_bro5 = pd.read_parquet(train_path)

df_bro5.head()

,SMILES,MP,Type,Ro5,RDKit_PEOE_VSA3,RDKit_NumAliphaticRings X RDKit_SlogP_VSA8,RDKit_NHOHCount,RDKit_SMR_VSA10 X RDKit_VSA_EState6,MACCS_105 X RDKit_NHOHCount,MACCS_105 X RDKit_fr_Ar_COO,...,RDKit_NHOHCount X RDKit_SlogP_VSA8,RDKit_BertzCT X RDKit_RingCount,RDKit_fr_ArN,RDKit_SMR_VSA5,MACCS_126 X RDKit_NumHDonors,RDKit_MaxAbsPartialCharge,MACCS_155 X RDKit_fr_Ar_OH,RDKit_Chi3n X RDKit_NumRotatableBonds,RDKit_SlogP_VSA2,Structure_Cluster
0,N#C/C(=C\c1ccc(cc1)F)/c1nc(c(s1)/N=N/c1c(Br)cc...,171.0,Train,0,1.377362,-0.195586,-0.839721,3.627567,-0.350082,-0.077211,...,-0.258763,1.327017,-0.268728,-0.438588,-0.316404,-1.364477,-0.145223,0.156274,-0.787455,5
1,OC[C@H]1O[C@]([C@H]([C@@H]1O[C@@H]1O[C@H](CO)[...,175.5,Train,0,-0.651134,-0.195586,5.295755,-0.618301,-0.350082,-0.077211,...,-0.258763,-0.277778,-0.268728,1.279756,10.270491,-0.003473,-0.145223,0.432013,5.665969,0
2,BrC(CC1(C(=O)C2(C(C1CC2)(C)C)C)C1(CC(Cc2ccccc2...,215.0,Train,0,-0.651134,-0.195586,-0.839721,3.455480,-0.350082,-0.077211,...,-0.258763,4.014965,-0.268728,2.993696,-0.316404,-0.837160,-0.145223,5.187947,0.160864,5
3,Clc1nc(Oc2cc(cc(c2)Oc2nc(Cl)nc(n2)Cl)Oc2nc(Cl)...,240.0,Train,0,-0.651134,-0.195586,-0.839721,0.493197,-0.350082,-0.077211,...,-0.258763,2.045446,-0.268728,-0.687065,-0.316404,0.262027,-0.145223,0.376171,1.541271,5
4,CC(=O)OCC12OC1C(C1C2C(OC=C1)OC1OC(COC(=O)C)C(C...,135.0,Train,0,0.386341,-0.195586,-0.839721,0.432663,-0.350082,-0.077211,...,-0.258763,4.293800,-0.268728,2.770617,-0.316404,0.686378,-0.145223,4.153629,5.334579,5

In [7]:
TARGET_COL = "MP"

exclude = {"SMILES", TARGET_COL, "Type", "Ro5", "Structure_Cluster"}
num_cols = df_bro5.select_dtypes(include=[np.number]).columns
feature_cols = [c for c in num_cols if c not in exclude]

X = df_bro5[feature_cols].to_numpy(np.float32) 
y = df_bro5[TARGET_COL].to_numpy(np.float32)
y_strat = df_bro5["Structure_Cluster"].astype(str).to_numpy()

skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=10)
folds = [(tr, va) for tr, va in skf.split(X, y_strat)]

print("Total samples:", len(X))
print("Num features:", X.shape[1])
print("Num folds:", len(folds))
print()

for i, (tr_idx, va_idx) in enumerate(folds):
    print(
        f"Fold {i:2d} | "
        f"Train: {len(tr_idx):4d} | "
        f"Val: {len(va_idx):4d}"
    )

BASELINE_CKPT = Path("artifacts/Ro5_best_models/Ro5_best_fold_3.pt")

Total samples: 257
Num features: 118
Num folds: 10

Fold  0 | Train:  231 | Val:   26
Fold  1 | Train:  231 | Val:   26
Fold  2 | Train:  231 | Val:   26
Fold  3 | Train:  231 | Val:   26
Fold  4 | Train:  231 | Val:   26
Fold  5 | Train:  231 | Val:   26
Fold  6 | Train:  231 | Val:   26
Fold  7 | Train:  232 | Val:   25
Fold  8 | Train:  232 | Val:   25
Fold  9 | Train:  232 | Val:   25

/opt/anaconda3/envs/Surabie_S_clean_v2/lib/python3.11/site-packages/sklearn/model_selection/_split.py:811: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(

In [9]:
from pathlib import Path
import json, joblib, numpy as np, pandas as pd, torch, optuna

# --- scenarios: name, vector (for your notes), freeze_level used by evaluate_fold_TL ---

HIDDEN_LAYERS = [224,112,56]   # must match baseline arch
N_TRIALS      = 20

OUT_ROOT = Path("artifacts/TL_Ro5")   # under the artifacts folder
OUT_ROOT.mkdir(parents=True, exist_ok=True)

def run_one_scenario(tag, freeze_vec, freeze_level):
    print(f"\n=== Scenario: {tag} | freeze={freeze_vec} (level={freeze_level}) ===")
    SCEN_OUT = OUT_ROOT / tag
    (SCEN_OUT / "trials").mkdir(parents=True, exist_ok=True)

    def objective_tl_fixed(trial):
        # fixed freeze level; tune the rest
        learning_rate = trial.suggest_float("learning_rate", 1e-5, 1e-3, log=True)
        weight_decay  = trial.suggest_float("weight_decay", 1e-6, 1e-3, log=True)
        batch_size    = trial.suggest_categorical("batch_size", [16, 32, 64])
        dropout_rate  = trial.suggest_float("dropout_rate", 0.2, 0.5)

        trial_dir = SCEN_OUT / "trials" / f"trial_{trial.number:04d}"
        trial_dir.mkdir(parents=True, exist_ok=True)

        fold_metrics, rmses = [], []
        for fold_idx, (tr_idx, va_idx) in enumerate(folds):
            X_tr, y_tr = X[tr_idx], y[tr_idx]
            X_va, y_va = X[va_idx], y[va_idx]

            rmse, r2, q2, model, *_ = evaluate_fold_TL(
                trial=trial,
                fold_idx=fold_idx,
                X_train_scaled=X_tr, y_train=y_tr,
                X_val_scaled=X_va,   y_val=y_va,
                hidden_layers=HIDDEN_LAYERS, dropout_rate=dropout_rate,
                learning_rate=learning_rate, weight_decay=weight_decay,
                batch_size=batch_size, freeze_level=freeze_level,
                baseline_ckpt=BASELINE_CKPT,
                max_epochs=10**6, patience=30, min_delta=0.0,
                save_checkpoints=False
            )

            ckpt_path = trial_dir / f"fold_{fold_idx}_best.pth"
            torch.save(model.state_dict(), ckpt_path)

            fold_metrics.append({
                "fold": fold_idx,
                "rmse": float(rmse),
                "r2":   float(r2),
                "q2":   float(q2),
                "checkpoint": str(ckpt_path)
            })
            rmses.append(rmse)

        summary = {
            "scenario": tag,
            "freeze_vector": freeze_vec,
            "freeze_level": freeze_level,
            "trial_number": trial.number,
            "params": {
                "learning_rate": learning_rate,
                "weight_decay":  weight_decay,
                "batch_size":    batch_size,
                "dropout_rate":  dropout_rate,
                "hidden_layers": HIDDEN_LAYERS
            },
            "avg_rmse": float(np.mean(rmses)),
            "folds":    fold_metrics
        }
        with open(trial_dir / "summary.json", "w") as f:
            json.dump(summary, f, indent=2)

        return float(np.mean(rmses))

    # -- HPO
    study = optuna.create_study(direction="minimize")
    study.optimize(objective_tl_fixed, n_trials=N_TRIALS, gc_after_trial=True)

    # save study artifacts
    joblib.dump(study, SCEN_OUT / "study.joblib")
    study.trials_dataframe().to_csv(SCEN_OUT / "trials.csv", index=False)
    with open(SCEN_OUT / "best_params.json","w") as f:
        json.dump(study.best_params, f, indent=2)
    with open(SCEN_OUT / "best_value.txt","w") as f:
        f.write(f"{study.best_value:.6f}\n")
    print(f"[{tag}] Best avg RMSE: {study.best_value:.4f}")
    print(f"[{tag}] Best params:  {study.best_params}")

    # -- Final per-fold retrain with best params (to produce clean fold models + metrics)
    best = study.best_params
    FINAL_DIR = SCEN_OUT / "final_fold_models"
    FINAL_DIR.mkdir(parents=True, exist_ok=True)

    rows = []
    for fold_idx, (tr_idx, va_idx) in enumerate(folds):
        X_tr, y_tr = X[tr_idx], y[tr_idx]
        X_va, y_va = X[va_idx], y[va_idx]

        rmse, r2, q2, model, *_ = evaluate_fold_TL(
            trial=None,
            fold_idx=fold_idx,
            X_train_scaled=X_tr, y_train=y_tr,
            X_val_scaled=X_va,   y_val=y_va,
            hidden_layers=HIDDEN_LAYERS,
            dropout_rate=best["dropout_rate"],
            learning_rate=best["learning_rate"],
            weight_decay=best["weight_decay"],
            batch_size=best["batch_size"],
            freeze_level=freeze_level,
            baseline_ckpt=BASELINE_CKPT,
            max_epochs=10**6, patience=30, min_delta=0.0,
            save_checkpoints=False
        )

        ckpt = FINAL_DIR / f"fold_{fold_idx}_best.pth"
        torch.save(model.state_dict(), ckpt)
        rows.append({"fold": fold_idx, "rmse": float(rmse), "r2": float(r2), "q2": float(q2), "checkpoint": str(ckpt)})

    cv_df = pd.DataFrame(rows).sort_values("rmse").reset_index(drop=True)
    cv_df.to_csv(SCEN_OUT / "cv_final_metrics.csv", index=False)

    best_row = cv_df.iloc[0]
    manifest = {
        "scenario": tag,
        "freeze_vector": freeze_vec,
        "freeze_level": freeze_level,
        "best_fold": int(best_row["fold"]),
        "checkpoint": best_row["checkpoint"],
        "hidden_layers": HIDDEN_LAYERS,
        "best_params": best
    }
    with open(SCEN_OUT / "manifest.json","w") as f:
        json.dump(manifest, f, indent=2)

    print(f"[{tag}] Best fold: {manifest['best_fold']} → {manifest['checkpoint']}")
    return study, cv_df, manifest


# ---------- RUN ALL THREE ----------
SCENARIOS = [
    ("no_freeze",        [0,0,0], 0),
    ("freeze_fc1",       [1,0,0], 1),
    ("freeze_fc1_fc2",   [1,1,0], 2),
]

results = {}
for tag, vec, lvl in SCENARIOS:
    study, cv_df, manifest = run_one_scenario(tag, vec, lvl)
    results[tag] = {"best": study.best_value, "manifest": manifest}
print("\nSummary:", json.dumps(results, indent=2))

[I 2026-02-02 11:27:30,467] A new study created in memory with name: no-name-4c900bf8-2978-4ee4-bcc0-28af63f1d3d5

=== Scenario: no_freeze | freeze=[0, 0, 0] (level=0) ===
Fold 0: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 72.5031 | Val 61.0063 | ES 0/30
[Fold 0] Epoch   50 | Train 57.3715 | Val 55.5213 | ES 4/30
[Fold 0] Epoch  100 | Train 49.5552 | Val 52.4116 | ES 3/30
[Fold 0] Epoch  150 | Train 41.4279 | Val 50.4370 | ES 1/30
[Fold 0] Epoch  200 | Train 42.7739 | Val 49.3419 | ES 8/30
[Fold 0] Early stopping at epoch 222 (best Val Loss: 48.1519)
Fold 1: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch    1 | Train 71.5825 | Val 62.7453 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 62.7453)
Fold 2: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 71.0012 | Val 50.2651 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 50.2651)
Fold 3: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 72.0136 | Val 61.2902 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 53.4737 | Val 57.5459 | ES 3/30
[Fold 3] Epoch  100 | Train 55.0154 | Val 54.4115 | ES 3/30
[Fold 3] Epoch  150 | Train 50.5549 | Val 54.8964 | ES 11/30
[Fold 3] Epoch  200 | Train 51.7789 | Val 53.1806 | ES 29/30
[Fold 3] Early stopping at epoch 201 (best Val Loss: 52.3602)
Fold 4: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 72.7862 | Val 64.3345 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 63.6302 | Val 64.9919 | ES 13/30
[Fold 4] Early stopping at epoch 86 (best Val Loss: 62.7780)
Fold 5: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 73.6048 | Val 62.8041 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 62.8041)
Fold 6: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.6668 | Val 67.6102 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 60.5417 | Val 66.8374 | ES 28/30
[Fold 6] Early stopping at epoch 52 (best Val Loss: 65.9275)
Fold 7: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 71.6485 | Val 55.4877 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 55.4877)
Fold 8: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 72.8920 | Val 53.7317 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 56.5499 | Val 51.2528 | ES 9/30
[Fold 8] Early stopping at epoch 71 (best Val Loss: 49.7037)
Fold 9: TL on cpu | freeze=0 | lr=0.000161577
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 73.2104 | Val 51.1388 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:27:37,726] Trial 0 finished with value: 56.13625030517578 and parameters: {'learning_rate': 0.00016157746168358406, 'weight_decay': 2.978941343075916e-06, 'batch_size': 32, 'dropout_rate': 0.4056504739043934}. Best is trial 0 with value: 56.13625030517578.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 51.1388)
Fold 0: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 73.5297 | Val 60.0009 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 65.7079 | Val 58.1028 | ES 3/30
[Fold 0] Early stopping at epoch 95 (best Val Loss: 56.7117)
Fold 1: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 75.4480 | Val 56.7104 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.7104)
Fold 2: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 72.7045 | Val 45.4804 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.4804)
Fold 3: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 71.1176 | Val 58.1268 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 58.1268)
Fold 4: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 67.5512 | Val 56.8112 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 56.8112)
Fold 5: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 75.7215 | Val 57.9037 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 57.9037)
Fold 6: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 71.7628 | Val 67.5692 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 67.5692)
Fold 7: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 72.6259 | Val 51.3907 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.3907)
Fold 8: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 69.9422 | Val 49.6356 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 49.6356)
Fold 9: TL on cpu | freeze=0 | lr=0.000107932
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 72.7111 | Val 44.1176 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:27:41,319] Trial 1 finished with value: 54.445729446411136 and parameters: {'learning_rate': 0.00010793230688320604, 'weight_decay': 0.00059995376339259, 'batch_size': 64, 'dropout_rate': 0.437996827467549}. Best is trial 1 with value: 54.445729446411136.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 44.1176)
Fold 0: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 68.5254 | Val 60.2738 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 44.8859 | Val 50.6247 | ES 0/30
[Fold 0] Epoch  100 | Train 43.6009 | Val 48.7424 | ES 15/30
[Fold 0] Early stopping at epoch 115 (best Val Loss: 48.1287)
Fold 1: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 71.1442 | Val 62.1221 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 48.5733 | Val 46.2461 | ES 0/30
[Fold 1] Epoch  100 | Train 39.0408 | Val 35.8310 | ES 5/30
[Fold 1] Epoch  150 | Train 41.2544 | Val 34.8000 | ES 21/30
[Fold 1] Epoch  200 | Train 35.9179 | Val 34.3140 | ES 19/30
[Fold 1] Early stopping at epoch 240 (best Val Loss: 33.1941)
Fold 2: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 72.2523 | Val 49.2976 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.2976)
Fold 3: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 67.8085 | Val 61.7037 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 49.0461 | Val 51.4252 | ES 0/30
[Fold 3] Epoch  100 | Train 43.0104 | Val 46.9518 | ES 1/30
[Fold 3] Epoch  150 | Train 40.6238 | Val 46.4539 | ES 22/30
[Fold 3] Early stopping at epoch 158 (best Val Loss: 45.7739)
Fold 4: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 71.3112 | Val 62.4731 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 52.0443 | Val 58.9859 | ES 0/30
[Fold 4] Epoch  100 | Train 53.5839 | Val 58.8144 | ES 10/30
[Fold 4] Early stopping at epoch 150 (best Val Loss: 56.0267)
Fold 5: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 70.1986 | Val 61.6487 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 53.6172 | Val 54.2137 | ES 0/30
[Fold 5] Epoch  100 | Train 44.0926 | Val 47.0459 | ES 0/30
[Fold 5] Epoch  150 | Train 44.5890 | Val 44.9874 | ES 1/30
[Fold 5] Early stopping at epoch 191 (best Val Loss: 44.0040)
Fold 6: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 71.6029 | Val 68.6508 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 50.6116 | Val 62.5654 | ES 16/30
[Fold 6] Early stopping at epoch 64 (best Val Loss: 62.3479)
Fold 7: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 69.0473 | Val 55.5072 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 50.9413 | Val 52.6971 | ES 2/30
[Fold 7] Epoch  100 | Train 46.7939 | Val 46.9435 | ES 5/30
[Fold 7] Early stopping at epoch 148 (best Val Loss: 45.0820)
Fold 8: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 71.4935 | Val 51.5285 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 46.6714 | Val 45.6167 | ES 4/30
[Fold 8] Epoch  100 | Train 44.0859 | Val 43.6085 | ES 24/30
[Fold 8] Early stopping at epoch 106 (best Val Loss: 42.2445)
Fold 9: TL on cpu | freeze=0 | lr=0.000382474
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 76.7318 | Val 50.9594 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 53.6483 | Val 44.6101 | ES 2/30
[Fold 9] Epoch  100 | Train 46.6286 | Val 39.7428 | ES 8/30
[Fold 9] Epoch  150 | Train 48.8685 | Val 36.8344 | ES 3/30
[Fold 9] Epoch  200 | Train 44.8246 | Val 36.5510 | ES 9/30

[I 2026-02-02 11:27:53,824] Trial 2 finished with value: 46.11953163146973 and parameters: {'learning_rate': 0.0003824735817467787, 'weight_decay': 0.0001991281736368768, 'batch_size': 32, 'dropout_rate': 0.4286646018712459}. Best is trial 2 with value: 46.11953163146973.

[Fold 9] Early stopping at epoch 238 (best Val Loss: 35.0958)
Fold 0: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 75.0372 | Val 58.6719 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 58.6719)
Fold 1: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 68.0085 | Val 56.6902 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.6902)
Fold 2: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 70.6374 | Val 45.8550 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.8550)
Fold 3: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 74.2879 | Val 58.5926 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 58.5926)
Fold 4: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 72.6659 | Val 58.5263 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 58.5263)
Fold 5: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 76.0379 | Val 58.3365 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 58.3365)
Fold 6: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.3821 | Val 67.9863 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 67.9863)
Fold 7: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 74.2403 | Val 52.5092 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 52.5092)
Fold 8: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 78.2659 | Val 49.3297 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 49.3297)
Fold 9: TL on cpu | freeze=0 | lr=1.20546e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 75.1582 | Val 43.4796 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:27:56,996] Trial 3 finished with value: 54.997731399536136 and parameters: {'learning_rate': 1.2054574539048846e-05, 'weight_decay': 0.0004993103128489286, 'batch_size': 64, 'dropout_rate': 0.47258209898335607}. Best is trial 2 with value: 46.11953163146973.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 43.4796)
Fold 0: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 67.1339 | Val 58.5157 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 57.0278 | Val 57.4152 | ES 6/30
[Fold 0] Epoch  100 | Train 57.5199 | Val 53.8071 | ES 11/30
[Fold 0] Early stopping at epoch 119 (best Val Loss: 53.4882)
Fold 1: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 67.4365 | Val 72.2864 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 62.2015 | Val 67.6949 | ES 8/30
[Fold 1] Epoch  100 | Train 58.1605 | Val 64.2028 | ES 10/30
[Fold 1] Epoch  150 | Train 59.6717 | Val 63.9703 | ES 11/30
[Fold 1] Early stopping at epoch 169 (best Val Loss: 60.7457)
Fold 2: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 66.8563 | Val 56.0629 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 56.0629)
Fold 3: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 67.0296 | Val 62.9366 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 64.0638 | Val 61.9864 | ES 4/30
[Fold 3] Early stopping at epoch 76 (best Val Loss: 60.7108)
Fold 4: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 68.2156 | Val 68.5833 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 57.6301 | Val 68.2024 | ES 7/30
[Fold 4] Epoch  100 | Train 61.0692 | Val 68.0957 | ES 18/30
[Fold 4] Early stopping at epoch 112 (best Val Loss: 64.6116)
Fold 5: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 69.2325 | Val 67.6651 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 62.9801 | Val 66.5200 | ES 14/30
[Fold 5] Early stopping at epoch 66 (best Val Loss: 64.4542)
Fold 6: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 68.5545 | Val 68.7387 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 59.6268 | Val 69.0234 | ES 8/30
[Fold 6] Epoch  100 | Train 56.5645 | Val 67.3900 | ES 11/30
[Fold 6] Early stopping at epoch 146 (best Val Loss: 66.0000)
Fold 7: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 69.7535 | Val 64.5449 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 59.2356 | Val 60.8241 | ES 4/30
[Fold 7] Epoch  100 | Train 52.0825 | Val 55.6922 | ES 2/30
[Fold 7] Epoch  150 | Train 50.8327 | Val 55.6082 | ES 8/30
[Fold 7] Early stopping at epoch 194 (best Val Loss: 51.5883)
Fold 8: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.2254 | Val 58.0377 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 64.2121 | Val 54.2930 | ES 10/30
[Fold 8] Early stopping at epoch 70 (best Val Loss: 53.0066)
Fold 9: TL on cpu | freeze=0 | lr=5.07696e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 70.8197 | Val 60.9308 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 63.3108 | Val 56.2448 | ES 10/30

[I 2026-02-02 11:28:11,663] Trial 4 finished with value: 57.90454330444336 and parameters: {'learning_rate': 5.0769561385864134e-05, 'weight_decay': 3.349860853001062e-05, 'batch_size': 16, 'dropout_rate': 0.23251168036340297}. Best is trial 2 with value: 46.11953163146973.

[Fold 9] Early stopping at epoch 90 (best Val Loss: 53.4662)
Fold 0: TL on cpu | freeze=0 | lr=2.23951e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 69.9135 | Val 59.5707 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 68.1728 | Val 56.9510 | ES 15/30
[Fold 0] Early stopping at epoch 65 (best Val Loss: 56.2476)
Fold 1: TL on cpu | freeze=0 | lr=2.23951e-05

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 74.8268 | Val 66.5537 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 66.5537)
Fold 2: TL on cpu | freeze=0 | lr=2.23951e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 74.4843 | Val 57.5957 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 69.7734 | Val 59.0293 | ES 3/30
[Fold 2] Early stopping at epoch 77 (best Val Loss: 56.4416)
Fold 3: TL on cpu | freeze=0 | lr=2.23951e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 69.6012 | Val 65.2703 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 69.1450 | Val 66.2990 | ES 3/30
[Fold 3] Epoch  100 | Train 67.8071 | Val 63.4444 | ES 19/30
[Fold 3] Early stopping at epoch 111 (best Val Loss: 60.5812)
Fold 4: TL on cpu | freeze=0 | lr=2.23951e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 71.6431 | Val 71.2061 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 68.7511 | Val 71.3389 | ES 12/30
[Fold 4] Epoch  100 | Train 66.3166 | Val 69.2493 | ES 13/30
[Fold 4] Early stopping at epoch 117 (best Val Loss: 65.9328)
Fold 5: TL on cpu | freeze=0 | lr=2.23951e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 74.6988 | Val 67.4789 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 45 (best Val Loss: 67.2963)
Fold 6: TL on cpu | freeze=0 | lr=2.23951e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 71.3807 | Val 70.6961 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 68.0788 | Val 71.3734 | ES 21/30
[Fold 6] Early stopping at epoch 59 (best Val Loss: 69.3586)
Fold 7: TL on cpu | freeze=0 | lr=2.23951e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 71.1850 | Val 60.5445 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 60.5445)
Fold 8: TL on cpu | freeze=0 | lr=2.23951e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 77.4750 | Val 60.3375 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 72.2678 | Val 56.9750 | ES 12/30
[Fold 8] Early stopping at epoch 68 (best Val Loss: 55.8139)
Fold 9: TL on cpu | freeze=0 | lr=2.23951e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 74.8818 | Val 59.7722 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 73.9942 | Val 62.1231 | ES 4/30

[I 2026-02-02 11:28:20,850] Trial 5 finished with value: 61.14154968261719 and parameters: {'learning_rate': 2.239512012878658e-05, 'weight_decay': 6.146054760093228e-06, 'batch_size': 16, 'dropout_rate': 0.49714990460879993}. Best is trial 2 with value: 46.11953163146973.

[Fold 9] Early stopping at epoch 76 (best Val Loss: 56.7111)
Fold 0: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 66.9195 | Val 59.8100 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 47.8542 | Val 54.6945 | ES 2/30
[Fold 0] Epoch  100 | Train 43.0157 | Val 52.1667 | ES 0/30
[Fold 0] Epoch  150 | Train 44.1823 | Val 51.4171 | ES 27/30
[Fold 0] Early stopping at epoch 153 (best Val Loss: 51.3012)
Fold 1: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 65.6803 | Val 62.0192 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 53.2456 | Val 58.6393 | ES 8/30
[Fold 1] Epoch  100 | Train 50.9737 | Val 53.5669 | ES 0/30
[Fold 1] Early stopping at epoch 149 (best Val Loss: 53.3182)
Fold 2: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 67.2389 | Val 49.1003 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.1003)
Fold 3: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 70.1499 | Val 60.4560 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 44.2964 | Val 52.2084 | ES 1/30
[Fold 3] Epoch  100 | Train 40.6904 | Val 49.7983 | ES 7/30
[Fold 3] Epoch  150 | Train 37.9806 | Val 48.8876 | ES 15/30
[Fold 3] Early stopping at epoch 165 (best Val Loss: 48.2540)
Fold 4: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 66.4878 | Val 62.6243 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 62.6243)
Fold 5: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.2044 | Val 62.3272 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 52.2109 | Val 58.3416 | ES 9/30
[Fold 5] Epoch  100 | Train 48.7314 | Val 53.7192 | ES 4/30
[Fold 5] Epoch  150 | Train 45.2530 | Val 51.6887 | ES 3/30
[Fold 5] Early stopping at epoch 177 (best Val Loss: 50.1914)
Fold 6: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 68.6719 | Val 67.2510 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 45.8945 | Val 62.4871 | ES 2/30
[Fold 6] Early stopping at epoch 88 (best Val Loss: 61.2749)
Fold 7: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 70.0705 | Val 55.1912 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 55.1912)
Fold 8: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 71.3845 | Val 52.4389 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 54.8007 | Val 50.0309 | ES 1/30
[Fold 8] Epoch  100 | Train 47.3961 | Val 47.6828 | ES 7/30
[Fold 8] Epoch  150 | Train 44.2531 | Val 48.1698 | ES 24/30
[Fold 8] Epoch  200 | Train 46.9354 | Val 48.6351 | ES 17/30
[Fold 8] Early stopping at epoch 213 (best Val Loss: 45.8578)
Fold 9: TL on cpu | freeze=0 | lr=0.000221059
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 73.4894 | Val 49.5629 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:28:30,106] Trial 6 finished with value: 52.66760673522949 and parameters: {'learning_rate': 0.00022105872819186143, 'weight_decay': 2.8181981681829932e-05, 'batch_size': 32, 'dropout_rate': 0.24924577195973024}. Best is trial 2 with value: 46.11953163146973.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 49.5629)
Fold 0: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 67.8614 | Val 60.8354 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 50 (best Val Loss: 58.2128)
Fold 1: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 70.1059 | Val 62.5726 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 62.5726)
Fold 2: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 68.6483 | Val 49.3870 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.3870)
Fold 3: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 67.1901 | Val 60.8773 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.8773)
Fold 4: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 70.6280 | Val 63.8387 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 63.8387)
Fold 5: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.7296 | Val 63.6059 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 63.6059)
Fold 6: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.1947 | Val 67.7386 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 65.9658 | Val 66.8356 | ES 0/30
[Fold 6] Early stopping at epoch 98 (best Val Loss: 66.4360)
Fold 7: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 71.4953 | Val 56.4077 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 56.4077)
Fold 8: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.3666 | Val 53.0772 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 53.0772)
Fold 9: TL on cpu | freeze=0 | lr=4.24386e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 71.4506 | Val 50.4433 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:28:33,641] Trial 7 finished with value: 58.48586883544922 and parameters: {'learning_rate': 4.243855140933265e-05, 'weight_decay': 1.0065365054139202e-06, 'batch_size': 32, 'dropout_rate': 0.29041263553940094}. Best is trial 2 with value: 46.11953163146973.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 50.4433)
Fold 0: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 69.9483 | Val 57.6091 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 52.7283 | Val 48.7343 | ES 0/30
[Fold 0] Epoch  100 | Train 47.1409 | Val 47.6314 | ES 11/30
[Fold 0] Epoch  150 | Train 48.4696 | Val 48.3024 | ES 23/30
[Fold 0] Early stopping at epoch 157 (best Val Loss: 47.2777)
Fold 1: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 71.9592 | Val 65.9603 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 51.4638 | Val 47.6757 | ES 0/30
[Fold 1] Epoch  100 | Train 46.4260 | Val 42.5227 | ES 2/30
[Fold 1] Early stopping at epoch 136 (best Val Loss: 40.7622)
Fold 2: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 69.9839 | Val 56.8206 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 54.0086 | Val 47.5557 | ES 0/30
[Fold 2] Epoch  100 | Train 46.8157 | Val 42.8087 | ES 11/30
[Fold 2] Early stopping at epoch 119 (best Val Loss: 42.1387)
Fold 3: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 69.3708 | Val 64.1971 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 48.3246 | Val 54.4025 | ES 8/30
[Fold 3] Epoch  100 | Train 44.1187 | Val 49.4400 | ES 3/30
[Fold 3] Early stopping at epoch 140 (best Val Loss: 46.4553)
Fold 4: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 76.8547 | Val 67.9100 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 51.0378 | Val 56.7094 | ES 4/30
[Fold 4] Epoch  100 | Train 45.6000 | Val 53.3134 | ES 23/30
[Fold 4] Early stopping at epoch 136 (best Val Loss: 51.4441)
Fold 5: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 70.8394 | Val 65.9937 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 57.2959 | Val 51.0176 | ES 2/30
[Fold 5] Epoch  100 | Train 41.4782 | Val 44.5591 | ES 2/30
[Fold 5] Early stopping at epoch 149 (best Val Loss: 41.3969)
Fold 6: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.4070 | Val 71.5406 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 47.3218 | Val 65.1324 | ES 0/30
[Fold 6] Epoch  100 | Train 49.2555 | Val 66.0801 | ES 25/30
[Fold 6] Early stopping at epoch 105 (best Val Loss: 64.7126)
Fold 7: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 73.1347 | Val 61.7502 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 52.7327 | Val 51.5478 | ES 8/30
[Fold 7] Early stopping at epoch 93 (best Val Loss: 45.1858)
Fold 8: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 69.2051 | Val 58.1480 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 48.1280 | Val 46.7140 | ES 3/30
[Fold 8] Epoch  100 | Train 44.8071 | Val 42.5570 | ES 0/30
[Fold 8] Early stopping at epoch 142 (best Val Loss: 41.7535)
Fold 9: TL on cpu | freeze=0 | lr=0.000218839
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 74.2980 | Val 58.4332 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 49.1448 | Val 40.1294 | ES 1/30
[Fold 9] Epoch  100 | Train 47.2020 | Val 33.4719 | ES 5/30
[Fold 9] Epoch  150 | Train 46.3108 | Val 31.7316 | ES 2/30

[I 2026-02-02 11:28:53,328] Trial 8 finished with value: 44.95439472198486 and parameters: {'learning_rate': 0.00021883920291545226, 'weight_decay': 2.5233027220846224e-06, 'batch_size': 16, 'dropout_rate': 0.41853969764505405}. Best is trial 8 with value: 44.95439472198486.

[Fold 9] Early stopping at epoch 197 (best Val Loss: 31.4423)
Fold 0: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 68.6060 | Val 55.8781 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 46.2814 | Val 47.2408 | ES 11/30
[Fold 0] Early stopping at epoch 94 (best Val Loss: 46.7284)
Fold 1: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 73.7421 | Val 69.9969 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 41.8422 | Val 37.9790 | ES 2/30
[Fold 1] Epoch  100 | Train 44.3286 | Val 33.9664 | ES 25/30
[Fold 1] Early stopping at epoch 105 (best Val Loss: 32.0632)
Fold 2: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 70.9458 | Val 57.3774 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 41.7362 | Val 43.4294 | ES 5/30
[Fold 2] Epoch  100 | Train 40.9173 | Val 41.7928 | ES 24/30
[Fold 2] Early stopping at epoch 106 (best Val Loss: 41.0397)
Fold 3: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 71.7986 | Val 61.9251 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 42.9173 | Val 44.6915 | ES 0/30
[Fold 3] Epoch  100 | Train 40.8823 | Val 41.4427 | ES 12/30
[Fold 3] Early stopping at epoch 118 (best Val Loss: 39.7244)
Fold 4: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 69.0551 | Val 65.6097 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 42.4037 | Val 53.8485 | ES 13/30
[Fold 4] Early stopping at epoch 67 (best Val Loss: 53.0138)
Fold 5: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 71.0364 | Val 66.4286 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 45.2596 | Val 43.2109 | ES 7/30
[Fold 5] Early stopping at epoch 99 (best Val Loss: 40.0245)
Fold 6: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 67.9705 | Val 67.5552 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 44.7578 | Val 68.0657 | ES 29/30
[Fold 6] Early stopping at epoch 51 (best Val Loss: 66.5522)
Fold 7: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 69.9657 | Val 61.5782 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 43.3982 | Val 41.0975 | ES 0/30
[Fold 7] Early stopping at epoch 93 (best Val Loss: 39.9826)
Fold 8: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 70.6747 | Val 55.9248 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 44.2718 | Val 40.6191 | ES 3/30
[Fold 8] Epoch  100 | Train 40.5228 | Val 39.7570 | ES 8/30
[Fold 8] Early stopping at epoch 122 (best Val Loss: 38.5658)
Fold 9: TL on cpu | freeze=0 | lr=0.000565423
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 71.3853 | Val 55.4591 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 42.1015 | Val 34.0557 | ES 10/30
[Fold 9] Epoch  100 | Train 44.9024 | Val 31.8708 | ES 18/30

[I 2026-02-02 11:29:07,160] Trial 9 finished with value: 42.906761741638185 and parameters: {'learning_rate': 0.0005654231321819462, 'weight_decay': 2.38599846880559e-05, 'batch_size': 16, 'dropout_rate': 0.40252063432765206}. Best is trial 9 with value: 42.906761741638185.

[Fold 9] Early stopping at epoch 137 (best Val Loss: 30.1699)
Fold 0: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 69.8981 | Val 56.6748 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 38.8646 | Val 48.6776 | ES 19/30
[Fold 0] Early stopping at epoch 61 (best Val Loss: 46.3958)
Fold 1: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 63.7813 | Val 66.6460 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 41.1522 | Val 35.5230 | ES 3/30
[Fold 1] Early stopping at epoch 99 (best Val Loss: 31.6614)
Fold 2: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 71.3803 | Val 55.6606 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 38.3803 | Val 46.0514 | ES 10/30
[Fold 2] Early stopping at epoch 70 (best Val Loss: 42.5568)
Fold 3: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 67.2183 | Val 63.8249 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 35.6988 | Val 40.6249 | ES 4/30
[Fold 3] Early stopping at epoch 76 (best Val Loss: 40.4892)
Fold 4: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 68.3466 | Val 67.6197 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 43.7194 | Val 52.4280 | ES 0/30
[Fold 4] Early stopping at epoch 94 (best Val Loss: 52.1621)
Fold 5: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 71.1208 | Val 68.2922 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 40.3786 | Val 43.0226 | ES 14/30
[Fold 5] Early stopping at epoch 66 (best Val Loss: 41.3466)
Fold 6: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 66.8430 | Val 69.9498 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 47 (best Val Loss: 63.6687)
Fold 7: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 69.8200 | Val 59.7677 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 38.8679 | Val 43.6966 | ES 23/30
[Fold 7] Early stopping at epoch 94 (best Val Loss: 40.8317)
Fold 8: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.3602 | Val 56.3409 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 38.4922 | Val 40.5585 | ES 7/30
[Fold 8] Early stopping at epoch 88 (best Val Loss: 36.2574)
Fold 9: TL on cpu | freeze=0 | lr=0.000948608
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 70.3681 | Val 55.6240 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:29:17,769] Trial 10 finished with value: 42.861697578430174 and parameters: {'learning_rate': 0.0009486077673672874, 'weight_decay': 4.3261954168860756e-05, 'batch_size': 16, 'dropout_rate': 0.3563340028282294}. Best is trial 10 with value: 42.861697578430174.

[Fold 9] Epoch   50 | Train 40.3531 | Val 33.0188 | ES 20/30
[Fold 9] Early stopping at epoch 60 (best Val Loss: 31.3460)
Fold 0: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch    1 | Train 69.0713 | Val 55.4098 | ES 0/30
[Fold 0] Epoch   50 | Train 33.9930 | Val 46.6974 | ES 17/30
[Fold 0] Early stopping at epoch 63 (best Val Loss: 44.6842)
Fold 1: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 67.8851 | Val 65.4964 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 40.3378 | Val 32.4589 | ES 0/30
[Fold 1] Early stopping at epoch 89 (best Val Loss: 31.7938)
Fold 2: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 72.3196 | Val 53.9941 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 40.8909 | Val 42.5075 | ES 28/30
[Fold 2] Early stopping at epoch 52 (best Val Loss: 41.3586)
Fold 3: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.6159 | Val 64.0909 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 35.5161 | Val 43.0857 | ES 13/30
[Fold 3] Epoch  100 | Train 39.1353 | Val 40.9821 | ES 22/30
[Fold 3] Early stopping at epoch 144 (best Val Loss: 39.7831)
Fold 4: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 67.0679 | Val 67.1016 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 35.0049 | Val 54.4489 | ES 2/30
[Fold 4] Early stopping at epoch 78 (best Val Loss: 51.4742)
Fold 5: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 69.5835 | Val 64.2883 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 38.1721 | Val 41.2809 | ES 18/30
[Fold 5] Early stopping at epoch 89 (best Val Loss: 40.3854)
Fold 6: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 67.0039 | Val 68.7130 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 37.4041 | Val 68.3122 | ES 26/30
[Fold 6] Early stopping at epoch 54 (best Val Loss: 63.6896)
Fold 7: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 70.4442 | Val 59.4434 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 40.0879 | Val 41.2551 | ES 8/30
[Fold 7] Early stopping at epoch 72 (best Val Loss: 38.4652)
Fold 8: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 67.0237 | Val 54.5656 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 41.9171 | Val 41.4022 | ES 18/30
[Fold 8] Early stopping at epoch 62 (best Val Loss: 39.9545)
Fold 9: TL on cpu | freeze=0 | lr=0.000896287
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 68.1436 | Val 54.8346 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:29:28,505] Trial 11 finished with value: 42.256737327575685 and parameters: {'learning_rate': 0.0008962869801534851, 'weight_decay': 3.9524355656029234e-05, 'batch_size': 16, 'dropout_rate': 0.33649082140342756}. Best is trial 11 with value: 42.256737327575685.

[Fold 9] Epoch   50 | Train 37.7021 | Val 30.4702 | ES 16/30
[Fold 9] Early stopping at epoch 64 (best Val Loss: 29.9323)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 68.4089 | Val 55.4682 | ES 0/30
[Fold 0] Epoch   50 | Train 34.2586 | Val 46.0369 | ES 25/30
[Fold 0] Early stopping at epoch 55 (best Val Loss: 45.3451)
Fold 1: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 69.7351 | Val 63.9793 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 40.3504 | Val 38.7483 | ES 11/30
[Fold 1] Early stopping at epoch 69 (best Val Loss: 34.3169)
Fold 2: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 69.3588 | Val 54.5837 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 35.1198 | Val 44.5244 | ES 19/30
[Fold 2] Early stopping at epoch 61 (best Val Loss: 41.4897)
Fold 3: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 72.7930 | Val 63.0895 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 40.0058 | Val 43.4921 | ES 1/30
[Fold 3] Early stopping at epoch 91 (best Val Loss: 41.8470)
Fold 4: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 68.2805 | Val 67.9802 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 40.5425 | Val 54.8271 | ES 27/30
[Fold 4] Early stopping at epoch 53 (best Val Loss: 51.7315)
Fold 5: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.4415 | Val 66.2798 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 50 (best Val Loss: 40.8451)
Fold 6: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 69.0310 | Val 69.1426 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 46 (best Val Loss: 65.8335)
Fold 7: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 72.5043 | Val 57.5893 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 38.4034 | Val 42.8235 | ES 22/30
[Fold 7] Early stopping at epoch 58 (best Val Loss: 40.3320)
Fold 8: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.1225 | Val 57.3010 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 40.5146 | Val 40.5837 | ES 2/30
[Fold 8] Early stopping at epoch 93 (best Val Loss: 38.1326)
Fold 9: TL on cpu | freeze=0 | lr=0.000996801
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 74.5324 | Val 57.3330 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 42.8024 | Val 30.8830 | ES 15/30

[I 2026-02-02 11:29:37,720] Trial 12 finished with value: 43.05717868804932 and parameters: {'learning_rate': 0.0009968010170336224, 'weight_decay': 7.206577520107152e-05, 'batch_size': 16, 'dropout_rate': 0.3403591703887353}. Best is trial 11 with value: 42.256737327575685.

[Fold 9] Early stopping at epoch 88 (best Val Loss: 28.9578)
Fold 0: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 70.4370 | Val 57.2004 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 40.2068 | Val 48.9792 | ES 29/30
[Fold 0] Early stopping at epoch 51 (best Val Loss: 47.1433)
Fold 1: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 69.4456 | Val 64.6445 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 37.8167 | Val 35.3382 | ES 1/30
[Fold 1] Epoch  100 | Train 34.4394 | Val 32.7089 | ES 27/30
[Fold 1] Early stopping at epoch 103 (best Val Loss: 29.6613)
Fold 2: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 73.3663 | Val 56.1136 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 37.8391 | Val 44.3762 | ES 14/30
[Fold 2] Early stopping at epoch 66 (best Val Loss: 41.0406)
Fold 3: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 68.6536 | Val 61.2244 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 41.8709 | Val 43.0358 | ES 0/30
[Fold 3] Early stopping at epoch 99 (best Val Loss: 40.4819)
Fold 4: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 65.3256 | Val 66.7677 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 36.9944 | Val 54.4493 | ES 10/30
[Fold 4] Epoch  100 | Train 34.2752 | Val 51.9931 | ES 13/30
[Fold 4] Early stopping at epoch 117 (best Val Loss: 50.5945)
Fold 5: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 72.6949 | Val 64.5692 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 36.5942 | Val 42.8959 | ES 13/30
[Fold 5] Early stopping at epoch 67 (best Val Loss: 41.1950)
Fold 6: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 68.8400 | Val 66.5466 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 45 (best Val Loss: 60.8306)
Fold 7: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 69.3860 | Val 61.0225 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 36.8412 | Val 42.7089 | ES 4/30
[Fold 7] Early stopping at epoch 76 (best Val Loss: 39.2291)
Fold 8: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 69.4882 | Val 56.9398 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 39.4285 | Val 39.5906 | ES 1/30
[Fold 8] Early stopping at epoch 94 (best Val Loss: 38.2374)
Fold 9: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 70.9862 | Val 54.2445 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 43.0224 | Val 32.1166 | ES 15/30
[Fold 9] Epoch  100 | Train 37.4508 | Val 30.6880 | ES 4/30

[I 2026-02-02 11:29:49,774] Trial 13 finished with value: 41.86210613250732 and parameters: {'learning_rate': 0.0008391407174139767, 'weight_decay': 0.00010108606474819895, 'batch_size': 16, 'dropout_rate': 0.3361295973831194}. Best is trial 13 with value: 41.86210613250732.

[Fold 9] Early stopping at epoch 147 (best Val Loss: 29.1952)
Fold 0: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 67.6928 | Val 56.8617 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 41.9186 | Val 48.1498 | ES 6/30
[Fold 0] Early stopping at epoch 74 (best Val Loss: 46.4577)
Fold 1: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 69.0122 | Val 67.5263 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 39.7618 | Val 36.6195 | ES 0/30
[Fold 1] Epoch  100 | Train 37.5881 | Val 32.8349 | ES 5/30
[Fold 1] Early stopping at epoch 131 (best Val Loss: 30.9506)
Fold 2: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 68.7190 | Val 53.4519 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 40.3514 | Val 43.6947 | ES 9/30
[Fold 2] Early stopping at epoch 95 (best Val Loss: 40.9300)
Fold 3: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 70.2397 | Val 61.5685 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 37.8240 | Val 46.4349 | ES 4/30
[Fold 3] Epoch  100 | Train 36.7131 | Val 42.0404 | ES 5/30
[Fold 3] Epoch  150 | Train 40.7179 | Val 42.4043 | ES 7/30
[Fold 3] Early stopping at epoch 173 (best Val Loss: 40.3545)
Fold 4: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 65.8437 | Val 67.3411 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 40.3975 | Val 55.7705 | ES 15/30
[Fold 4] Early stopping at epoch 82 (best Val Loss: 52.3665)
Fold 5: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 72.4987 | Val 66.4723 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 41.9662 | Val 41.5250 | ES 0/30
[Fold 5] Early stopping at epoch 97 (best Val Loss: 39.8885)
Fold 6: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 68.1097 | Val 67.5558 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 50 (best Val Loss: 63.0434)
Fold 7: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 67.9101 | Val 62.8772 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 40.0321 | Val 40.6960 | ES 4/30
[Fold 7] Early stopping at epoch 76 (best Val Loss: 40.1321)
Fold 8: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 71.4673 | Val 57.2340 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 35.7605 | Val 41.6570 | ES 0/30
[Fold 8] Early stopping at epoch 98 (best Val Loss: 38.3654)
Fold 9: TL on cpu | freeze=0 | lr=0.000466851
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 72.0943 | Val 56.3524 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 41.0720 | Val 31.2990 | ES 0/30
[Fold 9] Epoch  100 | Train 39.0956 | Val 30.3729 | ES 9/30

[I 2026-02-02 11:30:03,871] Trial 14 finished with value: 42.28821773529053 and parameters: {'learning_rate': 0.0004668512996729417, 'weight_decay': 0.00013786860979172685, 'batch_size': 16, 'dropout_rate': 0.32003701593206724}. Best is trial 13 with value: 41.86210613250732.

[Fold 9] Early stopping at epoch 146 (best Val Loss: 27.7521)
Fold 0: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 70.4652 | Val 57.5895 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 41.8344 | Val 46.9195 | ES 10/30
[Fold 0] Early stopping at epoch 85 (best Val Loss: 46.0168)
Fold 1: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 68.6872 | Val 70.1497 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 39.7971 | Val 40.2969 | ES 0/30
[Fold 1] Epoch  100 | Train 39.2068 | Val 36.7555 | ES 21/30
[Fold 1] Early stopping at epoch 109 (best Val Loss: 34.6787)
Fold 2: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 70.0021 | Val 55.0250 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 38.6210 | Val 43.4926 | ES 2/30
[Fold 2] Epoch  100 | Train 42.1410 | Val 42.2622 | ES 15/30
[Fold 2] Early stopping at epoch 132 (best Val Loss: 41.3450)
Fold 3: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 68.3490 | Val 63.6695 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 39.9585 | Val 44.8355 | ES 0/30
[Fold 3] Epoch  100 | Train 36.2254 | Val 43.9573 | ES 15/30
[Fold 3] Early stopping at epoch 115 (best Val Loss: 40.7670)
Fold 4: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 69.2288 | Val 68.2769 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 39.3540 | Val 56.8419 | ES 6/30
[Fold 4] Epoch  100 | Train 36.1686 | Val 55.4173 | ES 9/30
[Fold 4] Early stopping at epoch 121 (best Val Loss: 52.8864)
Fold 5: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.3831 | Val 67.0384 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 42.9391 | Val 44.2366 | ES 3/30
[Fold 5] Epoch  100 | Train 37.2337 | Val 43.3705 | ES 8/30
[Fold 5] Epoch  150 | Train 42.0647 | Val 43.2626 | ES 3/30
[Fold 5] Early stopping at epoch 177 (best Val Loss: 41.4919)
Fold 6: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 70.8569 | Val 67.3709 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 41.1863 | Val 65.0620 | ES 22/30
[Fold 6] Early stopping at epoch 58 (best Val Loss: 63.2353)
Fold 7: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 70.5748 | Val 59.4596 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 40.7295 | Val 43.9806 | ES 3/30
[Fold 7] Epoch  100 | Train 37.7303 | Val 40.8297 | ES 0/30
[Fold 7] Early stopping at epoch 130 (best Val Loss: 40.8297)
Fold 8: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 67.8337 | Val 55.9999 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 39.2980 | Val 42.3346 | ES 5/30
[Fold 8] Epoch  100 | Train 36.3490 | Val 39.6675 | ES 14/30
[Fold 8] Early stopping at epoch 116 (best Val Loss: 39.3369)
Fold 9: TL on cpu | freeze=0 | lr=0.000358288
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 68.9126 | Val 58.3349 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 38.1224 | Val 35.2905 | ES 0/30

[I 2026-02-02 11:30:19,893] Trial 15 finished with value: 43.142288780212404 and parameters: {'learning_rate': 0.00035828833795753144, 'weight_decay': 1.3786705499446731e-05, 'batch_size': 16, 'dropout_rate': 0.28854060937033427}. Best is trial 13 with value: 41.86210613250732.

[Fold 9] Epoch  100 | Train 36.4929 | Val 30.2658 | ES 18/30
[Fold 9] Early stopping at epoch 112 (best Val Loss: 29.0566)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 69.9113 | Val 58.5240 | ES 0/30
[Fold 0] Epoch   50 | Train 45.2084 | Val 51.6088 | ES 1/30
[Fold 0] Epoch  100 | Train 37.7921 | Val 50.5900 | ES 21/30
[Fold 0] Early stopping at epoch 109 (best Val Loss: 50.0353)
Fold 1: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 72.0893 | Val 54.4912 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 54.4912)
Fold 2: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 71.2152 | Val 43.7201 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 43.7201)
Fold 3: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 69.2411 | Val 57.0600 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 49.5602 | Val 53.1985 | ES 0/30
[Fold 3] Epoch  100 | Train 41.9021 | Val 48.9939 | ES 1/30
[Fold 3] Epoch  150 | Train 40.7961 | Val 47.8729 | ES 7/30
[Fold 3] Early stopping at epoch 200 (best Val Loss: 47.2001)
Fold 4: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 72.7000 | Val 55.7180 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 55.7180)
Fold 5: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 72.4552 | Val 55.8859 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 55.8859)
Fold 6: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 73.4616 | Val 66.9270 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 41.2732 | Val 60.0687 | ES 2/30
[Fold 6] Early stopping at epoch 78 (best Val Loss: 59.6917)
Fold 7: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 74.0434 | Val 51.8281 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.8281)
Fold 8: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 71.0013 | Val 49.6410 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 49.6410)
Fold 9: TL on cpu | freeze=0 | lr=0.000706444
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 71.4788 | Val 43.1501 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:30:25,754] Trial 16 finished with value: 51.13615531921387 and parameters: {'learning_rate': 0.000706443734048551, 'weight_decay': 0.00018669127742872637, 'batch_size': 64, 'dropout_rate': 0.3738898205702214}. Best is trial 13 with value: 41.86210613250732.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 43.1501)
Fold 0: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 67.7606 | Val 58.0865 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 56.8118 | Val 54.1540 | ES 4/30
[Fold 0] Epoch  100 | Train 49.9492 | Val 51.8565 | ES 1/30
[Fold 0] Early stopping at epoch 150 (best Val Loss: 50.6280)
Fold 1: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 68.9263 | Val 73.6413 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 55.4944 | Val 59.0250 | ES 0/30
[Fold 1] Epoch  100 | Train 49.4695 | Val 55.1093 | ES 2/30
[Fold 1] Epoch  150 | Train 49.1829 | Val 52.4487 | ES 7/30
[Fold 1] Early stopping at epoch 173 (best Val Loss: 50.2192)
Fold 2: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 66.8684 | Val 54.9400 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 54.9400)
Fold 3: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 66.3988 | Val 63.2007 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 53.9043 | Val 58.1387 | ES 4/30
[Fold 3] Epoch  100 | Train 51.9997 | Val 55.3830 | ES 9/30
[Fold 3] Early stopping at epoch 121 (best Val Loss: 53.9075)
Fold 4: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 67.4147 | Val 66.3175 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 58.4652 | Val 68.1321 | ES 2/30
[Fold 4] Early stopping at epoch 90 (best Val Loss: 62.9238)
Fold 5: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 68.3596 | Val 68.1226 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 59.1521 | Val 65.0875 | ES 4/30
[Fold 5] Epoch  100 | Train 54.7904 | Val 59.9810 | ES 4/30
[Fold 5] Epoch  150 | Train 54.3705 | Val 56.6066 | ES 4/30
[Fold 5] Early stopping at epoch 176 (best Val Loss: 55.1450)
Fold 6: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 69.3700 | Val 69.4534 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 57.8060 | Val 67.7161 | ES 9/30
[Fold 6] Early stopping at epoch 71 (best Val Loss: 64.7441)
Fold 7: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 70.4680 | Val 60.2093 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 58.9741 | Val 60.4628 | ES 1/30
[Fold 7] Epoch  100 | Train 61.1134 | Val 60.0472 | ES 2/30
[Fold 7] Early stopping at epoch 128 (best Val Loss: 57.0019)
Fold 8: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 69.3818 | Val 59.7350 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 57.9710 | Val 51.9055 | ES 2/30
[Fold 8] Epoch  100 | Train 55.7064 | Val 51.6233 | ES 26/30
[Fold 8] Early stopping at epoch 104 (best Val Loss: 50.4774)
Fold 9: TL on cpu | freeze=0 | lr=6.87292e-05
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 70.2080 | Val 59.0441 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 60.6583 | Val 54.9306 | ES 4/30
[Fold 9] Epoch  100 | Train 56.4597 | Val 53.3481 | ES 4/30
[Fold 9] Epoch  150 | Train 56.3392 | Val 52.6548 | ES 9/30

[I 2026-02-02 11:30:42,761] Trial 17 finished with value: 54.295793533325195 and parameters: {'learning_rate': 6.87292435243158e-05, 'weight_decay': 7.561295717166942e-05, 'batch_size': 16, 'dropout_rate': 0.20097946413544412}. Best is trial 13 with value: 41.86210613250732.

[Fold 9] Epoch  200 | Train 60.3600 | Val 51.2542 | ES 28/30
[Fold 9] Early stopping at epoch 202 (best Val Loss: 47.9513)
Fold 0: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 69.3147 | Val 57.8060 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 42.5506 | Val 47.8343 | ES 3/30
[Fold 0] Epoch  100 | Train 39.3178 | Val 47.2764 | ES 9/30
[Fold 0] Early stopping at epoch 121 (best Val Loss: 46.5509)
Fold 1: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 68.5958 | Val 69.2390 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 43.1153 | Val 42.9017 | ES 0/30
[Fold 1] Epoch  100 | Train 42.1470 | Val 36.1671 | ES 5/30
[Fold 1] Epoch  150 | Train 37.4716 | Val 35.5964 | ES 14/30
[Fold 1] Early stopping at epoch 196 (best Val Loss: 33.6920)
Fold 2: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 69.8640 | Val 55.1247 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 44.7428 | Val 43.9614 | ES 1/30
[Fold 2] Epoch  100 | Train 37.8718 | Val 43.4586 | ES 3/30
[Fold 2] Early stopping at epoch 143 (best Val Loss: 41.9868)
Fold 3: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 67.1166 | Val 63.4354 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 42.9154 | Val 46.3723 | ES 3/30
[Fold 3] Early stopping at epoch 98 (best Val Loss: 43.2179)
Fold 4: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 65.9885 | Val 68.1670 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 45.2718 | Val 56.6522 | ES 2/30
[Fold 4] Epoch  100 | Train 42.1640 | Val 56.1516 | ES 23/30
[Fold 4] Epoch  150 | Train 37.9205 | Val 58.6995 | ES 26/30
[Fold 4] Early stopping at epoch 154 (best Val Loss: 54.0097)
Fold 5: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 69.3235 | Val 67.8812 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 45.2738 | Val 46.3484 | ES 0/30
[Fold 5] Epoch  100 | Train 39.4710 | Val 42.4859 | ES 16/30
[Fold 5] Epoch  150 | Train 37.8205 | Val 42.0843 | ES 15/30
[Fold 5] Early stopping at epoch 165 (best Val Loss: 41.1722)
Fold 6: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch    1 | Train 69.7678 | Val 69.8568 | ES 0/30
[Fold 6] Epoch   50 | Train 44.6647 | Val 65.1234 | ES 5/30
[Fold 6] Early stopping at epoch 84 (best Val Loss: 64.1019)
Fold 7: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 65.7707 | Val 59.5791 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 40.9990 | Val 46.1630 | ES 3/30
[Fold 7] Epoch  100 | Train 38.6520 | Val 42.1146 | ES 7/30
[Fold 7] Early stopping at epoch 136 (best Val Loss: 40.8639)
Fold 8: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 71.8102 | Val 57.6286 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 45.6184 | Val 43.4361 | ES 0/30
[Fold 8] Epoch  100 | Train 40.1807 | Val 39.4303 | ES 0/30
[Fold 8] Early stopping at epoch 144 (best Val Loss: 38.8493)
Fold 9: TL on cpu | freeze=0 | lr=0.000301173
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 69.0916 | Val 61.3614 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 49.0091 | Val 37.2009 | ES 2/30
[Fold 9] Epoch  100 | Train 42.3543 | Val 32.2853 | ES 8/30

[I 2026-02-02 11:31:01,096] Trial 18 finished with value: 43.57779521942139 and parameters: {'learning_rate': 0.00030117306777428224, 'weight_decay': 1.154544429575133e-05, 'batch_size': 16, 'dropout_rate': 0.3111262104782129}. Best is trial 13 with value: 41.86210613250732.

[Fold 9] Early stopping at epoch 122 (best Val Loss: 31.5645)
Fold 0: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 75.2465 | Val 59.8906 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 63.8401 | Val 57.4536 | ES 16/30
[Fold 0] Early stopping at epoch 64 (best Val Loss: 57.1335)
Fold 1: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 69.2823 | Val 55.9861 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 55.9861)
Fold 2: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 69.3302 | Val 44.4247 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 44.4247)
Fold 3: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 71.3356 | Val 58.4506 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 58.4506)
Fold 4: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 67.1788 | Val 57.5846 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 57.5846)
Fold 5: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 69.9706 | Val 57.6202 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 57.6202)
Fold 6: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 68.6344 | Val 67.2266 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 44 (best Val Loss: 67.0774)
Fold 7: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 71.5424 | Val 51.9433 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.9433)
Fold 8: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 72.8037 | Val 49.1672 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 49.1672)
Fold 9: TL on cpu | freeze=0 | lr=0.000120482
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 73.4884 | Val 44.6369 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:31:04,564] Trial 19 finished with value: 54.40243263244629 and parameters: {'learning_rate': 0.00012048195594975863, 'weight_decay': 0.0003001298474925905, 'batch_size': 64, 'dropout_rate': 0.3648651644261922}. Best is trial 13 with value: 41.86210613250732.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 44.6369)
[no_freeze] Best avg RMSE: 41.8621
[no_freeze] Best params:  {'learning_rate': 0.0008391407174139767, 'weight_decay': 0.00010108606474819895, 'batch_size': 16, 'dropout_rate': 0.3361295973831194}
Fold 0: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 0] Epoch    1 | Train 68.8954 | Val 55.5385 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 42.6979 | Val 46.7161 | ES 6/30
[Fold 0] Early stopping at epoch 74 (best Val Loss: 45.3900)
Fold 1: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 1] Epoch    1 | Train 68.7388 | Val 69.6205 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 39.2704 | Val 36.6319 | ES 3/30
[Fold 1] Early stopping at epoch 77 (best Val Loss: 34.0438)
Fold 2: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 2] Epoch    1 | Train 66.9281 | Val 52.0029 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 37.6452 | Val 42.8853 | ES 25/30
[Fold 2] Early stopping at epoch 55 (best Val Loss: 40.6904)
Fold 3: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 3] Epoch    1 | Train 69.3231 | Val 62.3622 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 39.8375 | Val 42.7607 | ES 1/30
[Fold 3] Early stopping at epoch 86 (best Val Loss: 41.1817)
Fold 4: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 4] Epoch    1 | Train 70.5719 | Val 67.2779 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 34.0973 | Val 55.6704 | ES 15/30
[Fold 4] Epoch  100 | Train 37.9586 | Val 55.3174 | ES 16/30
[Fold 4] Epoch  150 | Train 36.8504 | Val 54.2091 | ES 27/30
[Fold 4] Early stopping at epoch 153 (best Val Loss: 52.5867)
Fold 5: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 5] Epoch    1 | Train 71.3191 | Val 63.7801 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 39.9166 | Val 42.0769 | ES 2/30
[Fold 5] Early stopping at epoch 78 (best Val Loss: 40.2703)
Fold 6: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 6] Epoch    1 | Train 66.6783 | Val 67.7909 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 42 (best Val Loss: 62.9085)
Fold 7: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 7] Epoch    1 | Train 72.0434 | Val 60.9932 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 36.1147 | Val 39.9244 | ES 26/30
[Fold 7] Early stopping at epoch 54 (best Val Loss: 38.9662)
Fold 8: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 8] Epoch    1 | Train 68.1669 | Val 55.8577 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 41.7402 | Val 39.7340 | ES 3/30
[Fold 8] Early stopping at epoch 93 (best Val Loss: 36.3953)
Fold 9: TL on cpu | freeze=0 | lr=0.000839141
Freeze Level 0: all layers trainable
[Fold 9] Epoch    1 | Train 71.0151 | Val 56.4022 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 37.9839 | Val 29.2454 | ES 0/30

[I 2026-02-02 11:31:15,574] A new study created in memory with name: no-name-7fda0d9d-8fee-450d-a169-48f55481c0cd

[Fold 9] Early stopping at epoch 89 (best Val Loss: 27.8696)
[no_freeze] Best fold: 9 → artifacts/TL_Ro5/no_freeze/final_fold_models/fold_9_best.pth

=== Scenario: freeze_fc1 | freeze=[1, 0, 0] (level=1) ===
Fold 0: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.0542 | Val 60.9594 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 48.4559 | Val 49.0597 | ES 9/30
[Fold 0] Early stopping at epoch 71 (best Val Loss: 48.5988)
Fold 1: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 73.8642 | Val 61.0961 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 50.7814 | Val 42.2024 | ES 0/30
[Fold 1] Epoch  100 | Train 48.1718 | Val 41.3049 | ES 15/30
[Fold 1] Early stopping at epoch 115 (best Val Loss: 40.1458)
Fold 2: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 69.7498 | Val 48.7062 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 51.8351 | Val 44.5813 | ES 0/30
[Fold 2] Epoch  100 | Train 50.0992 | Val 44.1021 | ES 27/30
[Fold 2] Early stopping at epoch 103 (best Val Loss: 43.6392)
Fold 3: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 74.6138 | Val 61.9459 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 47.5191 | Val 48.2730 | ES 3/30
[Fold 3] Early stopping at epoch 93 (best Val Loss: 46.0689)
Fold 4: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 68.1064 | Val 63.5944 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 50.0484 | Val 51.8086 | ES 3/30
[Fold 4] Epoch  100 | Train 46.5176 | Val 51.9355 | ES 9/30
[Fold 4] Early stopping at epoch 121 (best Val Loss: 50.6783)
Fold 5: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 70.1387 | Val 62.1449 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 46.9859 | Val 45.6333 | ES 1/30
[Fold 5] Epoch  100 | Train 45.7821 | Val 45.1517 | ES 6/30
[Fold 5] Early stopping at epoch 124 (best Val Loss: 44.0002)
Fold 6: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 70.9525 | Val 67.8669 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 49.0690 | Val 57.6398 | ES 4/30
[Fold 6] Early stopping at epoch 76 (best Val Loss: 57.1355)
Fold 7: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 71.9377 | Val 55.0245 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 48.7238 | Val 40.8187 | ES 1/30
[Fold 7] Early stopping at epoch 100 (best Val Loss: 39.1441)
Fold 8: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 73.0340 | Val 51.9710 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 49.0078 | Val 43.0204 | ES 22/30
[Fold 8] Early stopping at epoch 58 (best Val Loss: 41.9424)
Fold 9: TL on cpu | freeze=1 | lr=0.000982729
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 73.1412 | Val 48.5146 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 54.4511 | Val 33.3150 | ES 5/30
[Fold 9] Epoch  100 | Train 51.6451 | Val 30.8841 | ES 6/30

[I 2026-02-02 11:31:22,650] Trial 0 finished with value: 44.09673156738281 and parameters: {'learning_rate': 0.0009827289067426382, 'weight_decay': 9.711554865937596e-05, 'batch_size': 32, 'dropout_rate': 0.41014536901988474}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 137 (best Val Loss: 29.6139)
Fold 0: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.0365 | Val 58.8796 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 74.2500 | Val 59.8412 | ES 26/30
[Fold 0] Early stopping at epoch 54 (best Val Loss: 58.7141)
Fold 1: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 67.9581 | Val 57.5854 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.5854)
Fold 2: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 74.7043 | Val 45.6205 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.6205)
Fold 3: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 68.8280 | Val 57.5823 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 57.5823)
Fold 4: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 71.8624 | Val 58.9147 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 58.9147)
Fold 5: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 73.2350 | Val 57.9105 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 57.9105)
Fold 6: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 73.6031 | Val 67.1631 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 67.1631)
Fold 7: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 69.6994 | Val 51.7290 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.7290)
Fold 8: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 72.9295 | Val 50.1462 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 50.1462)
Fold 9: TL on cpu | freeze=1 | lr=7.50601e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 67.8815 | Val 43.9506 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:31:25,481] Trial 1 finished with value: 54.93164482116699 and parameters: {'learning_rate': 7.506007304858372e-05, 'weight_decay': 4.003598311358632e-05, 'batch_size': 64, 'dropout_rate': 0.4515691124031009}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 43.9506)
Fold 0: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 68.7875 | Val 60.1203 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 68.4445 | Val 59.1932 | ES 25/30
[Fold 0] Early stopping at epoch 55 (best Val Loss: 58.9680)
Fold 1: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 69.3272 | Val 57.2031 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.2031)
Fold 2: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 72.4806 | Val 45.1648 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.1648)
Fold 3: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 69.9992 | Val 56.3918 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 56.3918)
Fold 4: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 66.8211 | Val 57.8494 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 57.8494)
Fold 5: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 66.7181 | Val 57.5031 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 57.5031)
Fold 6: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 69.1592 | Val 66.5776 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 33 (best Val Loss: 66.5125)
Fold 7: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 66.4738 | Val 51.3492 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.3492)
Fold 8: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 71.4277 | Val 49.4713 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 49.4713)
Fold 9: TL on cpu | freeze=1 | lr=3.22849e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 70.8141 | Val 44.1679 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:31:28,453] Trial 2 finished with value: 54.45810241699219 and parameters: {'learning_rate': 3.2284890470223326e-05, 'weight_decay': 4.9420371861722836e-05, 'batch_size': 64, 'dropout_rate': 0.2451471274476283}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 44.1679)
Fold 0: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 72.1864 | Val 58.6162 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 64.3028 | Val 51.1225 | ES 10/30
[Fold 0] Epoch  100 | Train 56.7338 | Val 49.5021 | ES 3/30
[Fold 0] Early stopping at epoch 127 (best Val Loss: 48.7517)
Fold 1: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 72.3594 | Val 70.4479 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 60.4244 | Val 61.4777 | ES 1/30
[Fold 1] Epoch  100 | Train 58.0294 | Val 52.2252 | ES 1/30
[Fold 1] Epoch  150 | Train 54.5403 | Val 48.5620 | ES 18/30
[Fold 1] Early stopping at epoch 162 (best Val Loss: 46.4024)
Fold 2: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 72.9303 | Val 55.6222 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 68.2421 | Val 53.9692 | ES 7/30
[Fold 2] Epoch  100 | Train 65.8653 | Val 48.9609 | ES 0/30
[Fold 2] Early stopping at epoch 143 (best Val Loss: 48.9197)
Fold 3: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 72.5524 | Val 63.4474 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 67.6143 | Val 62.6450 | ES 10/30
[Fold 3] Epoch  100 | Train 65.3250 | Val 61.6569 | ES 22/30
[Fold 3] Early stopping at epoch 108 (best Val Loss: 60.2356)
Fold 4: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 72.6410 | Val 68.8671 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 59.5611 | Val 61.2050 | ES 2/30
[Fold 4] Epoch  100 | Train 54.0985 | Val 57.5858 | ES 11/30
[Fold 4] Early stopping at epoch 134 (best Val Loss: 55.5757)
Fold 5: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 74.4700 | Val 67.0312 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 64.1083 | Val 58.7736 | ES 4/30
[Fold 5] Epoch  100 | Train 55.8056 | Val 52.9275 | ES 10/30
[Fold 5] Early stopping at epoch 131 (best Val Loss: 51.6150)
Fold 6: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 72.1804 | Val 70.2500 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 66.0504 | Val 67.3419 | ES 1/30
[Fold 6] Epoch  100 | Train 56.0389 | Val 65.6363 | ES 4/30
[Fold 6] Epoch  150 | Train 57.6317 | Val 65.9813 | ES 16/30
[Fold 6] Early stopping at epoch 164 (best Val Loss: 63.9571)
Fold 7: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 73.2652 | Val 60.3301 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 63.8535 | Val 56.7960 | ES 2/30
[Fold 7] Epoch  100 | Train 59.3288 | Val 51.7231 | ES 3/30
[Fold 7] Epoch  150 | Train 60.4172 | Val 50.7688 | ES 25/30
[Fold 7] Early stopping at epoch 155 (best Val Loss: 50.0518)
Fold 8: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 73.0820 | Val 57.9881 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 68.3557 | Val 48.4689 | ES 4/30
[Fold 8] Epoch  100 | Train 55.5292 | Val 44.6380 | ES 8/30
[Fold 8] Early stopping at epoch 122 (best Val Loss: 41.2891)
Fold 9: TL on cpu | freeze=1 | lr=0.000166959
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 76.3535 | Val 60.4247 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 64.0054 | Val 49.2141 | ES 2/30
[Fold 9] Epoch  100 | Train 59.0214 | Val 41.0437 | ES 15/30
[Fold 9] Epoch  150 | Train 58.8383 | Val 39.1814 | ES 3/30

[I 2026-02-02 11:31:44,445] Trial 3 finished with value: 49.96137809753418 and parameters: {'learning_rate': 0.00016695918648847605, 'weight_decay': 1.8734312899471417e-06, 'batch_size': 16, 'dropout_rate': 0.4843875253778162}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 182 (best Val Loss: 37.5357)
Fold 0: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 73.9779 | Val 58.3830 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 67.8732 | Val 57.1640 | ES 0/30
[Fold 0] Early stopping at epoch 89 (best Val Loss: 56.3331)
Fold 1: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 69.0494 | Val 57.3325 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.3325)
Fold 2: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 68.8162 | Val 45.4062 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.4062)
Fold 3: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 68.7054 | Val 57.9187 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 57.9187)
Fold 4: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 66.6728 | Val 57.6723 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 57.6723)
Fold 5: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 72.3248 | Val 57.3578 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 57.3578)
Fold 6: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 70.2735 | Val 67.0935 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 67.0935)
Fold 7: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 72.8202 | Val 51.8192 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.8192)
Fold 8: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 68.0660 | Val 48.7966 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 48.7966)
Fold 9: TL on cpu | freeze=1 | lr=0.000221016
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 74.1010 | Val 43.8673 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:31:47,548] Trial 4 finished with value: 54.35972671508789 and parameters: {'learning_rate': 0.0002210160509367477, 'weight_decay': 0.0001184781689911731, 'batch_size': 64, 'dropout_rate': 0.37680702475664485}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 43.8673)
Fold 0: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 66.9576 | Val 58.6496 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 62.4568 | Val 51.8002 | ES 0/30
[Fold 0] Epoch  100 | Train 57.1511 | Val 51.4944 | ES 6/30
[Fold 0] Epoch  150 | Train 56.6416 | Val 50.5775 | ES 26/30
[Fold 0] Epoch  200 | Train 52.1510 | Val 51.4370 | ES 21/30
[Fold 0] Early stopping at epoch 209 (best Val Loss: 50.0904)
Fold 1: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.7129 | Val 73.2301 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 63.9292 | Val 71.0532 | ES 13/30
[Fold 1] Epoch  100 | Train 60.6150 | Val 69.6398 | ES 22/30
[Fold 1] Early stopping at epoch 108 (best Val Loss: 67.8316)
Fold 2: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.2902 | Val 57.1272 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 57.1272)
Fold 3: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 66.7380 | Val 63.7674 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 61.6782 | Val 62.3496 | ES 9/30
[Fold 3] Epoch  100 | Train 60.2392 | Val 60.8871 | ES 9/30
[Fold 3] Early stopping at epoch 121 (best Val Loss: 58.9840)
Fold 4: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 70.8981 | Val 69.3004 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 58.7416 | Val 64.7048 | ES 4/30
[Fold 4] Epoch  100 | Train 52.8923 | Val 62.1320 | ES 6/30
[Fold 4] Epoch  150 | Train 51.9954 | Val 60.6181 | ES 26/30
[Fold 4] Early stopping at epoch 154 (best Val Loss: 58.3199)
Fold 5: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 70.3885 | Val 65.9917 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 65.9917)
Fold 6: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 69.9914 | Val 70.1536 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 62.5861 | Val 66.7709 | ES 11/30
[Fold 6] Early stopping at epoch 69 (best Val Loss: 65.5667)
Fold 7: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 67.4028 | Val 61.3443 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 64.2894 | Val 61.4465 | ES 1/30
[Fold 7] Epoch  100 | Train 63.9274 | Val 58.8267 | ES 10/30
[Fold 7] Early stopping at epoch 148 (best Val Loss: 56.3394)
Fold 8: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 68.5791 | Val 58.4703 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 58.0134 | Val 53.4667 | ES 1/30
[Fold 8] Epoch  100 | Train 53.4812 | Val 47.2275 | ES 9/30
[Fold 8] Epoch  150 | Train 51.8640 | Val 46.5857 | ES 2/30
[Fold 8] Early stopping at epoch 195 (best Val Loss: 44.9153)
Fold 9: TL on cpu | freeze=1 | lr=7.83938e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.2100 | Val 58.1627 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:31:59,688] Trial 5 finished with value: 57.782175064086914 and parameters: {'learning_rate': 7.839382775013404e-05, 'weight_decay': 3.5461640576444724e-05, 'batch_size': 16, 'dropout_rate': 0.20332501064180009}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 58.1627)
Fold 0: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 73.3745 | Val 60.1095 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 68.0363 | Val 57.0552 | ES 8/30
[Fold 0] Epoch  100 | Train 59.3083 | Val 55.8727 | ES 3/30
[Fold 0] Early stopping at epoch 134 (best Val Loss: 55.4269)
Fold 1: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 69.8087 | Val 56.9456 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 56.9456)
Fold 2: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 69.6224 | Val 45.2894 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.2894)
Fold 3: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 68.0409 | Val 57.1531 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 57.1531)
Fold 4: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 65.1087 | Val 57.7879 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 57.7879)
Fold 5: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 70.1614 | Val 56.9612 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 56.9612)
Fold 6: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 67.4252 | Val 66.9590 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 66.9590)
Fold 7: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 69.5445 | Val 51.2196 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.2196)
Fold 8: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 69.2453 | Val 48.7073 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 48.7073)
Fold 9: TL on cpu | freeze=1 | lr=0.000106898
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 70.0331 | Val 44.1953 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:32:03,028] Trial 6 finished with value: 54.06451072692871 and parameters: {'learning_rate': 0.00010689789191878128, 'weight_decay': 1.1532871499700845e-06, 'batch_size': 64, 'dropout_rate': 0.26671848279564603}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 44.1953)
Fold 0: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 69.4001 | Val 60.7773 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 68.5652 | Val 60.3724 | ES 2/30
[Fold 0] Early stopping at epoch 78 (best Val Loss: 59.8949)
Fold 1: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.1896 | Val 62.9677 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 62.9677)
Fold 2: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.1448 | Val 49.8887 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.8887)
Fold 3: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 66.6874 | Val 60.4958 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.4958)
Fold 4: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 66.8444 | Val 64.3600 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 64.3600)
Fold 5: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 69.9439 | Val 63.1617 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 63.1617)
Fold 6: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 68.0006 | Val 66.8583 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 66.8583)
Fold 7: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 69.2301 | Val 55.2990 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 55.2990)
Fold 8: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 67.0156 | Val 53.2807 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 53.2807)
Fold 9: TL on cpu | freeze=1 | lr=1.34199e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 70.7256 | Val 50.8355 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:32:05,741] Trial 7 finished with value: 58.70422210693359 and parameters: {'learning_rate': 1.3419917891383635e-05, 'weight_decay': 0.00018102006608933303, 'batch_size': 32, 'dropout_rate': 0.24260281589824803}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 50.8355)
Fold 0: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 69.5955 | Val 57.1645 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 57.1645)
Fold 1: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 73.7662 | Val 71.1076 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 71.1076)
Fold 2: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 71.6202 | Val 55.7367 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 55.7367)
Fold 3: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 75.3861 | Val 63.8585 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 63.8585)
Fold 4: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 75.9314 | Val 67.3871 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 67.3871)
Fold 5: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 71.2709 | Val 68.8265 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 70.4928 | Val 70.8492 | ES 25/30
[Fold 5] Early stopping at epoch 55 (best Val Loss: 68.1560)
Fold 6: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 73.3505 | Val 70.5140 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 70.5140)
Fold 7: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 74.3244 | Val 60.7664 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 60.7664)
Fold 8: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 74.1023 | Val 60.3048 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 39 (best Val Loss: 58.9282)
Fold 9: TL on cpu | freeze=1 | lr=1.04676e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 75.5536 | Val 60.3905 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:32:09,562] Trial 8 finished with value: 63.126456069946286 and parameters: {'learning_rate': 1.0467595456189583e-05, 'weight_decay': 0.0003813678016128417, 'batch_size': 16, 'dropout_rate': 0.4618614729765146}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 60.3905)
Fold 0: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 69.7072 | Val 61.1799 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 55.6532 | Val 51.0495 | ES 0/30
[Fold 0] Epoch  100 | Train 44.8931 | Val 49.9311 | ES 6/30
[Fold 0] Epoch  150 | Train 43.9406 | Val 48.9444 | ES 21/30
[Fold 0] Epoch  200 | Train 46.2417 | Val 48.3152 | ES 26/30
[Fold 0] Early stopping at epoch 204 (best Val Loss: 48.2966)
Fold 1: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 68.1674 | Val 62.2782 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 62.2782)
Fold 2: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 69.9183 | Val 49.6457 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.6457)
Fold 3: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 67.7890 | Val 60.7740 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 62.0196 | Val 58.3865 | ES 1/30
[Fold 3] Epoch  100 | Train 53.9749 | Val 54.2104 | ES 0/30
[Fold 3] Epoch  150 | Train 46.2088 | Val 52.1206 | ES 17/30
[Fold 3] Early stopping at epoch 195 (best Val Loss: 50.7848)
Fold 4: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 67.3226 | Val 62.4239 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 62.4239)
Fold 5: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 69.7519 | Val 62.4404 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 62.4404)
Fold 6: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 68.4911 | Val 67.4851 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 52.6838 | Val 61.0622 | ES 6/30
[Fold 6] Epoch  100 | Train 48.8575 | Val 57.1379 | ES 1/30
[Fold 6] Early stopping at epoch 131 (best Val Loss: 56.7773)
Fold 7: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 68.4979 | Val 56.1564 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 61.7082 | Val 56.8146 | ES 21/30
[Fold 7] Epoch  100 | Train 62.7468 | Val 54.2611 | ES 3/30
[Fold 7] Epoch  150 | Train 58.7304 | Val 52.9547 | ES 20/30
[Fold 7] Early stopping at epoch 160 (best Val Loss: 52.3855)
Fold 8: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 67.8224 | Val 52.0781 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 60.3360 | Val 49.3044 | ES 4/30
[Fold 8] Epoch  100 | Train 54.0005 | Val 44.7761 | ES 7/30
[Fold 8] Epoch  150 | Train 49.9572 | Val 44.3888 | ES 26/30
[Fold 8] Early stopping at epoch 182 (best Val Loss: 43.3922)
Fold 9: TL on cpu | freeze=1 | lr=0.0002944
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.3034 | Val 50.5998 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:32:16,742] Trial 9 finished with value: 53.9024600982666 and parameters: {'learning_rate': 0.00029440031483859237, 'weight_decay': 0.00037968227970472173, 'batch_size': 32, 'dropout_rate': 0.33219806611034947}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 50.5998)
Fold 0: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 71.7003 | Val 60.8327 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 49.4568 | Val 48.8975 | ES 6/30
[Fold 0] Early stopping at epoch 81 (best Val Loss: 48.7214)
Fold 1: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 68.8639 | Val 61.2753 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 55.5074 | Val 51.2983 | ES 0/30
[Fold 1] Epoch  100 | Train 49.5581 | Val 44.8566 | ES 5/30
[Fold 1] Epoch  150 | Train 43.2820 | Val 43.2624 | ES 17/30
[Fold 1] Epoch  200 | Train 48.3436 | Val 42.7377 | ES 25/30
[Fold 1] Early stopping at epoch 205 (best Val Loss: 41.4942)
Fold 2: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 72.8979 | Val 49.5228 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 56.8176 | Val 48.5450 | ES 9/30
[Fold 2] Epoch  100 | Train 55.4556 | Val 47.5325 | ES 3/30
[Fold 2] Early stopping at epoch 143 (best Val Loss: 46.0326)
Fold 3: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 70.9875 | Val 61.2263 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 47.0530 | Val 50.5061 | ES 1/30
[Fold 3] Epoch  100 | Train 48.0536 | Val 48.5098 | ES 14/30
[Fold 3] Early stopping at epoch 116 (best Val Loss: 47.0380)
Fold 4: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 70.0352 | Val 61.4956 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 48.6993 | Val 53.1250 | ES 6/30
[Fold 4] Epoch  100 | Train 45.9335 | Val 51.4922 | ES 4/30
[Fold 4] Epoch  150 | Train 44.9662 | Val 51.6781 | ES 2/30
[Fold 4] Epoch  200 | Train 46.3278 | Val 51.9787 | ES 12/30
[Fold 4] Early stopping at epoch 218 (best Val Loss: 50.6173)
Fold 5: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 72.0982 | Val 61.6339 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 48.8280 | Val 47.9068 | ES 1/30
[Fold 5] Epoch  100 | Train 46.9383 | Val 44.9253 | ES 16/30
[Fold 5] Early stopping at epoch 114 (best Val Loss: 44.0705)
Fold 6: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 68.3303 | Val 68.3077 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 48.1343 | Val 57.9604 | ES 6/30
[Fold 6] Early stopping at epoch 74 (best Val Loss: 57.6864)
Fold 7: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 72.8732 | Val 56.6863 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 47.2094 | Val 42.1882 | ES 0/30
[Fold 7] Epoch  100 | Train 46.5726 | Val 40.2371 | ES 0/30
[Fold 7] Early stopping at epoch 145 (best Val Loss: 39.1026)
Fold 8: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 71.1493 | Val 52.2569 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 49.6426 | Val 42.6998 | ES 6/30
[Fold 8] Early stopping at epoch 74 (best Val Loss: 41.5684)
Fold 9: TL on cpu | freeze=1 | lr=0.000685307
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 74.5700 | Val 49.4588 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 53.9394 | Val 40.6861 | ES 1/30
[Fold 9] Epoch  100 | Train 48.0548 | Val 35.0506 | ES 2/30
[Fold 9] Epoch  150 | Train 49.0873 | Val 32.8776 | ES 14/30
[Fold 9] Epoch  200 | Train 46.5972 | Val 32.3640 | ES 12/30

[I 2026-02-02 11:32:27,074] Trial 10 finished with value: 44.82321891784668 and parameters: {'learning_rate': 0.0006853072642203511, 'weight_decay': 0.0006324255903129236, 'batch_size': 32, 'dropout_rate': 0.392478579118195}. Best is trial 0 with value: 44.09673156738281.

[Fold 9] Early stopping at epoch 231 (best Val Loss: 31.9008)
Fold 0: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 69.5362 | Val 60.0390 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 47.2225 | Val 49.5270 | ES 5/30
[Fold 0] Epoch  100 | Train 45.3872 | Val 48.6659 | ES 3/30
[Fold 0] Early stopping at epoch 127 (best Val Loss: 48.3375)
Fold 1: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch    1 | Train 69.0908 | Val 62.0772 | ES 0/30
[Fold 1] Epoch   50 | Train 48.3676 | Val 42.5388 | ES 0/30
[Fold 1] Epoch  100 | Train 43.6726 | Val 41.5768 | ES 1/30
[Fold 1] Epoch  150 | Train 48.6804 | Val 40.1208 | ES 12/30
[Fold 1] Early stopping at epoch 168 (best Val Loss: 39.6740)
Fold 2: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 69.4257 | Val 50.0324 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 51.1744 | Val 43.8495 | ES 9/30
[Fold 2] Early stopping at epoch 83 (best Val Loss: 43.0999)
Fold 3: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 67.1223 | Val 61.6853 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 48.2905 | Val 48.9029 | ES 7/30
[Fold 3] Epoch  100 | Train 42.4649 | Val 47.0609 | ES 22/30
[Fold 3] Early stopping at epoch 138 (best Val Loss: 46.0226)
Fold 4: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 69.9626 | Val 63.6209 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 47.0301 | Val 51.0760 | ES 1/30
[Fold 4] Epoch  100 | Train 41.5128 | Val 50.9420 | ES 26/30
[Fold 4] Early stopping at epoch 104 (best Val Loss: 48.9709)
Fold 5: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 72.5744 | Val 61.4108 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 47.8428 | Val 45.9719 | ES 9/30
[Fold 5] Epoch  100 | Train 49.3111 | Val 45.1900 | ES 18/30
[Fold 5] Early stopping at epoch 146 (best Val Loss: 44.1661)
Fold 6: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 69.3450 | Val 67.4948 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 47.1795 | Val 59.0589 | ES 1/30
[Fold 6] Early stopping at epoch 99 (best Val Loss: 58.3982)
Fold 7: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 69.7946 | Val 55.0028 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 44.6053 | Val 40.1836 | ES 1/30
[Fold 7] Early stopping at epoch 97 (best Val Loss: 38.4062)
Fold 8: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 69.1325 | Val 51.3703 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 43.0949 | Val 43.0828 | ES 0/30
[Fold 8] Early stopping at epoch 80 (best Val Loss: 43.0828)
Fold 9: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 73.5270 | Val 49.9824 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 48.7765 | Val 32.7099 | ES 0/30

[I 2026-02-02 11:32:35,431] Trial 11 finished with value: 43.97364139556885 and parameters: {'learning_rate': 0.0009551946771714858, 'weight_decay': 0.0009459303248566866, 'batch_size': 32, 'dropout_rate': 0.39358067494518556}. Best is trial 11 with value: 43.97364139556885.

[Fold 9] Epoch  100 | Train 45.8503 | Val 31.0535 | ES 22/30
[Fold 9] Early stopping at epoch 108 (best Val Loss: 29.5782)
Fold 0: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.1398 | Val 61.3422 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 50.4313 | Val 49.4356 | ES 12/30
[Fold 0] Early stopping at epoch 68 (best Val Loss: 48.4758)
Fold 1: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 69.3298 | Val 61.3365 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 47.2733 | Val 42.5846 | ES 0/30
[Fold 1] Epoch  100 | Train 45.4321 | Val 41.7045 | ES 14/30
[Fold 1] Epoch  150 | Train 45.9569 | Val 41.4979 | ES 23/30
[Fold 1] Early stopping at epoch 157 (best Val Loss: 40.2373)
Fold 2: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 72.5114 | Val 49.5678 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 51.2147 | Val 44.8665 | ES 0/30
[Fold 2] Epoch  100 | Train 48.1148 | Val 43.1762 | ES 2/30
[Fold 2] Early stopping at epoch 128 (best Val Loss: 42.9126)
Fold 3: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch    1 | Train 70.4757 | Val 60.9587 | ES 0/30
[Fold 3] Epoch   50 | Train 48.3507 | Val 49.0877 | ES 0/30
[Fold 3] Early stopping at epoch 95 (best Val Loss: 46.6984)
Fold 4: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 70.0184 | Val 64.1606 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 50.2598 | Val 51.7398 | ES 6/30
[Fold 4] Early stopping at epoch 91 (best Val Loss: 50.1280)
Fold 5: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 71.4620 | Val 62.7348 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 48.4894 | Val 46.7237 | ES 2/30
[Fold 5] Epoch  100 | Train 43.6217 | Val 44.9653 | ES 17/30
[Fold 5] Early stopping at epoch 113 (best Val Loss: 44.2287)
Fold 6: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 73.3011 | Val 67.2182 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 50.2967 | Val 60.1037 | ES 18/30
[Fold 6] Early stopping at epoch 84 (best Val Loss: 58.8563)
Fold 7: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 72.0808 | Val 54.9717 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 51.1191 | Val 41.2129 | ES 4/30
[Fold 7] Epoch  100 | Train 48.9067 | Val 39.9109 | ES 2/30
[Fold 7] Epoch  150 | Train 46.2366 | Val 40.3115 | ES 12/30
[Fold 7] Early stopping at epoch 168 (best Val Loss: 39.4070)
Fold 8: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 69.3418 | Val 51.8034 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 48.3725 | Val 42.9091 | ES 22/30
[Fold 8] Early stopping at epoch 58 (best Val Loss: 41.5446)
Fold 9: TL on cpu | freeze=1 | lr=0.000913161
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 77.2860 | Val 50.5408 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 49.4321 | Val 33.4251 | ES 6/30
[Fold 9] Epoch  100 | Train 50.5240 | Val 31.7609 | ES 7/30

[I 2026-02-02 11:32:43,691] Trial 12 finished with value: 44.26740970611572 and parameters: {'learning_rate': 0.0009131613510239629, 'weight_decay': 8.08042520337366e-06, 'batch_size': 32, 'dropout_rate': 0.41172144117283793}. Best is trial 11 with value: 43.97364139556885.

[Fold 9] Epoch  150 | Train 48.3009 | Val 31.4132 | ES 21/30
[Fold 9] Early stopping at epoch 159 (best Val Loss: 30.1854)
Fold 0: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.8083 | Val 61.0367 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 47.6897 | Val 49.5850 | ES 2/30
[Fold 0] Epoch  100 | Train 45.6554 | Val 48.4848 | ES 14/30
[Fold 0] Epoch  150 | Train 43.3984 | Val 48.1030 | ES 5/30
[Fold 0] Early stopping at epoch 175 (best Val Loss: 47.7019)
Fold 1: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 67.3782 | Val 61.9287 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 57.0963 | Val 60.1087 | ES 5/30
[Fold 1] Epoch  100 | Train 56.7135 | Val 56.6191 | ES 5/30
[Fold 1] Epoch  150 | Train 56.1315 | Val 56.3678 | ES 8/30
[Fold 1] Early stopping at epoch 172 (best Val Loss: 53.5647)
Fold 2: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 71.2123 | Val 49.8609 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.8609)
Fold 3: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 68.4922 | Val 60.1041 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 53.8144 | Val 56.0466 | ES 4/30
[Fold 3] Epoch  100 | Train 48.3570 | Val 51.0754 | ES 0/30
[Fold 3] Epoch  150 | Train 47.9275 | Val 49.4791 | ES 15/30
[Fold 3] Epoch  200 | Train 50.8451 | Val 48.4893 | ES 13/30
[Fold 3] Epoch  250 | Train 43.5429 | Val 48.4561 | ES 21/30
[Fold 3] Early stopping at epoch 259 (best Val Loss: 47.7075)
Fold 4: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 69.7382 | Val 63.4933 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 54.1112 | Val 59.4011 | ES 2/30
[Fold 4] Epoch  100 | Train 49.2315 | Val 54.7110 | ES 1/30
[Fold 4] Epoch  150 | Train 50.4018 | Val 53.5953 | ES 7/30
[Fold 4] Epoch  200 | Train 52.3514 | Val 53.7945 | ES 18/30
[Fold 4] Early stopping at epoch 212 (best Val Loss: 52.7916)
Fold 5: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 69.4821 | Val 62.3776 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 53.5441 | Val 56.4735 | ES 0/30
[Fold 5] Epoch  100 | Train 50.8256 | Val 50.0941 | ES 5/30
[Fold 5] Epoch  150 | Train 46.9874 | Val 47.7308 | ES 6/30
[Fold 5] Epoch  200 | Train 45.1803 | Val 46.7389 | ES 3/30
[Fold 5] Early stopping at epoch 245 (best Val Loss: 45.3864)
Fold 6: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 69.2272 | Val 68.4044 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 48.8021 | Val 61.3517 | ES 5/30
[Fold 6] Early stopping at epoch 75 (best Val Loss: 59.8055)
Fold 7: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 72.4182 | Val 55.1182 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 55.1182)
Fold 8: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 71.4387 | Val 53.2373 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 50.3022 | Val 43.9979 | ES 0/30
[Fold 8] Early stopping at epoch 100 (best Val Loss: 42.6461)
Fold 9: TL on cpu | freeze=1 | lr=0.00044249
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.8956 | Val 50.6832 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 57.8511 | Val 45.8902 | ES 1/30
[Fold 9] Epoch  100 | Train 52.3337 | Val 39.1075 | ES 3/30
[Fold 9] Epoch  150 | Train 49.2771 | Val 36.7974 | ES 13/30

[I 2026-02-02 11:32:54,906] Trial 13 finished with value: 49.03072242736816 and parameters: {'learning_rate': 0.00044248985206829213, 'weight_decay': 9.477927540215676e-06, 'batch_size': 32, 'dropout_rate': 0.3332323569157946}. Best is trial 11 with value: 43.97364139556885.

[Fold 9] Early stopping at epoch 181 (best Val Loss: 35.7245)
Fold 0: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 71.1007 | Val 60.0575 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 48.8623 | Val 49.0163 | ES 8/30
[Fold 0] Early stopping at epoch 72 (best Val Loss: 48.1067)
Fold 1: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.0679 | Val 60.8376 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 50.2274 | Val 44.0586 | ES 5/30
[Fold 1] Epoch  100 | Train 45.5301 | Val 41.0254 | ES 7/30
[Fold 1] Early stopping at epoch 123 (best Val Loss: 38.9742)
Fold 2: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.5021 | Val 49.5327 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 50.8250 | Val 44.3216 | ES 3/30
[Fold 2] Early stopping at epoch 100 (best Val Loss: 43.1584)
Fold 3: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 73.0428 | Val 60.9327 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 45.7389 | Val 49.1293 | ES 3/30
[Fold 3] Early stopping at epoch 82 (best Val Loss: 47.9102)
Fold 4: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 70.2007 | Val 62.9398 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 46.1009 | Val 51.3489 | ES 6/30
[Fold 4] Early stopping at epoch 74 (best Val Loss: 50.6633)
Fold 5: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 73.8797 | Val 62.5816 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 51.9314 | Val 44.5683 | ES 0/30
[Fold 5] Epoch  100 | Train 42.4497 | Val 43.8405 | ES 3/30
[Fold 5] Early stopping at epoch 127 (best Val Loss: 43.8175)
Fold 6: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 69.8057 | Val 68.7923 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 50.7210 | Val 61.4336 | ES 25/30
[Fold 6] Early stopping at epoch 55 (best Val Loss: 60.0406)
Fold 7: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 71.6484 | Val 56.1402 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 46.5372 | Val 41.1526 | ES 2/30
[Fold 7] Epoch  100 | Train 45.9753 | Val 39.6648 | ES 2/30
[Fold 7] Early stopping at epoch 140 (best Val Loss: 38.8505)
Fold 8: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 73.1932 | Val 52.3794 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 51.1061 | Val 42.7752 | ES 13/30
[Fold 8] Early stopping at epoch 67 (best Val Loss: 41.9158)
Fold 9: TL on cpu | freeze=1 | lr=0.000987486
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 73.3647 | Val 49.1078 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 49.8344 | Val 32.2080 | ES 0/30
[Fold 9] Epoch  100 | Train 46.2442 | Val 30.4910 | ES 4/30

[I 2026-02-02 11:33:01,980] Trial 14 finished with value: 44.35656547546387 and parameters: {'learning_rate': 0.0009874864957852528, 'weight_decay': 0.0009420454326364074, 'batch_size': 32, 'dropout_rate': 0.42434046901134276}. Best is trial 11 with value: 43.97364139556885.

[Fold 9] Early stopping at epoch 126 (best Val Loss: 30.1283)
Fold 0: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 69.7642 | Val 60.4480 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 47.0109 | Val 48.9208 | ES 1/30
[Fold 0] Epoch  100 | Train 40.0458 | Val 47.6008 | ES 16/30
[Fold 0] Early stopping at epoch 114 (best Val Loss: 46.9986)
Fold 1: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 68.6451 | Val 62.3220 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 52.3612 | Val 53.0686 | ES 6/30
[Fold 1] Epoch  100 | Train 45.7316 | Val 45.6478 | ES 3/30
[Fold 1] Epoch  150 | Train 45.7138 | Val 42.1404 | ES 10/30
[Fold 1] Early stopping at epoch 170 (best Val Loss: 41.6694)
Fold 2: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 68.9509 | Val 49.2237 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.2237)
Fold 3: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 70.0572 | Val 60.5393 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 45.6168 | Val 48.2892 | ES 1/30
[Fold 3] Epoch  100 | Train 38.4346 | Val 44.8654 | ES 2/30
[Fold 3] Early stopping at epoch 143 (best Val Loss: 44.3449)
Fold 4: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 67.1700 | Val 62.0033 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 48.9026 | Val 55.4028 | ES 0/30
[Fold 4] Epoch  100 | Train 44.8609 | Val 53.0228 | ES 14/30
[Fold 4] Early stopping at epoch 116 (best Val Loss: 51.9687)
Fold 5: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 73.2839 | Val 62.2788 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 46.9833 | Val 49.3047 | ES 1/30
[Fold 5] Epoch  100 | Train 41.8432 | Val 44.6035 | ES 1/30
[Fold 5] Early stopping at epoch 131 (best Val Loss: 43.9268)
Fold 6: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 68.0657 | Val 67.9417 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 45.0707 | Val 58.5808 | ES 13/30
[Fold 6] Early stopping at epoch 67 (best Val Loss: 57.4378)
Fold 7: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 72.6604 | Val 54.9410 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 51.8318 | Val 46.6117 | ES 0/30
[Fold 7] Epoch  100 | Train 49.5998 | Val 41.6269 | ES 2/30
[Fold 7] Epoch  150 | Train 45.8233 | Val 41.3891 | ES 25/30
[Fold 7] Early stopping at epoch 155 (best Val Loss: 40.0481)
Fold 8: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 70.0035 | Val 51.9269 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 44.3021 | Val 43.7799 | ES 8/30
[Fold 8] Early stopping at epoch 72 (best Val Loss: 43.3895)
Fold 9: TL on cpu | freeze=1 | lr=0.00060381
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.1286 | Val 49.6772 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 55.5147 | Val 42.1602 | ES 4/30
[Fold 9] Epoch  100 | Train 47.3845 | Val 35.3701 | ES 2/30
[Fold 9] Epoch  150 | Train 42.6525 | Val 33.0009 | ES 2/30

[I 2026-02-02 11:33:10,688] Trial 15 finished with value: 45.075023078918456 and parameters: {'learning_rate': 0.0006038098249057272, 'weight_decay': 0.00012451625260871443, 'batch_size': 32, 'dropout_rate': 0.29802429622090354}. Best is trial 11 with value: 43.97364139556885.

[Fold 9] Epoch  200 | Train 41.9823 | Val 32.3942 | ES 22/30
[Fold 9] Early stopping at epoch 208 (best Val Loss: 31.7427)
Fold 0: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 71.3805 | Val 60.5369 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 51.0697 | Val 50.3047 | ES 0/30
[Fold 0] Epoch  100 | Train 45.7451 | Val 48.8187 | ES 1/30
[Fold 0] Early stopping at epoch 134 (best Val Loss: 48.2488)
Fold 1: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 67.0755 | Val 62.8865 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 62.8865)
Fold 2: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.8052 | Val 50.7521 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 50.7521)
Fold 3: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 70.8739 | Val 60.4061 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 55.2551 | Val 56.9707 | ES 6/30
[Fold 3] Epoch  100 | Train 55.5308 | Val 54.6099 | ES 4/30
[Fold 3] Early stopping at epoch 147 (best Val Loss: 53.5627)
Fold 4: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 68.5971 | Val 63.7374 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 58.1259 | Val 58.8400 | ES 0/30
[Fold 4] Epoch  100 | Train 52.5955 | Val 55.1320 | ES 3/30
[Fold 4] Epoch  150 | Train 45.1749 | Val 52.7195 | ES 3/30
[Fold 4] Epoch  200 | Train 46.5581 | Val 52.4597 | ES 6/30
[Fold 4] Early stopping at epoch 241 (best Val Loss: 51.1101)
Fold 5: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 70.0808 | Val 63.0215 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 63.0215)
Fold 6: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 70.4034 | Val 68.3231 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 52.6740 | Val 59.8881 | ES 2/30
[Fold 6] Epoch  100 | Train 49.7082 | Val 59.5134 | ES 18/30
[Fold 6] Early stopping at epoch 112 (best Val Loss: 58.7064)
Fold 7: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 72.0938 | Val 55.5841 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 58.2076 | Val 51.3500 | ES 1/30
[Fold 7] Epoch  100 | Train 50.2604 | Val 47.0019 | ES 10/30
[Fold 7] Epoch  150 | Train 47.8795 | Val 42.9598 | ES 0/30
[Fold 7] Epoch  200 | Train 51.0142 | Val 41.8876 | ES 6/30
[Fold 7] Early stopping at epoch 224 (best Val Loss: 41.7717)
Fold 8: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 68.4272 | Val 52.6652 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 57.4720 | Val 46.9064 | ES 2/30
[Fold 8] Epoch  100 | Train 55.9510 | Val 44.8230 | ES 23/30
[Fold 8] Early stopping at epoch 107 (best Val Loss: 43.8557)
Fold 9: TL on cpu | freeze=1 | lr=0.000381712
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.3358 | Val 50.6849 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 64.5153 | Val 50.3678 | ES 1/30
[Fold 9] Epoch  100 | Train 60.8250 | Val 46.9135 | ES 5/30

[I 2026-02-02 11:33:19,433] Trial 16 finished with value: 51.90798416137695 and parameters: {'learning_rate': 0.00038171187789691317, 'weight_decay': 1.0977949513048032e-05, 'batch_size': 32, 'dropout_rate': 0.36417537120322657}. Best is trial 11 with value: 43.97364139556885.

[Fold 9] Epoch  150 | Train 58.6291 | Val 46.9624 | ES 13/30
[Fold 9] Early stopping at epoch 167 (best Val Loss: 45.1645)
Fold 0: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 70.5069 | Val 61.6939 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 59.8747 | Val 50.6689 | ES 2/30
[Fold 0] Epoch  100 | Train 53.7085 | Val 50.3245 | ES 22/30
[Fold 0] Early stopping at epoch 108 (best Val Loss: 49.2153)
Fold 1: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 72.1407 | Val 61.9533 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 61.9533)
Fold 2: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 71.7901 | Val 50.7938 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 58.1087 | Val 48.8568 | ES 0/30
[Fold 2] Epoch  100 | Train 59.5720 | Val 48.3167 | ES 19/30
[Fold 2] Early stopping at epoch 131 (best Val Loss: 47.2095)
Fold 3: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 71.0094 | Val 61.6853 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 54.7865 | Val 54.8982 | ES 6/30
[Fold 3] Epoch  100 | Train 51.8025 | Val 50.9480 | ES 0/30
[Fold 3] Epoch  150 | Train 51.4783 | Val 50.2739 | ES 2/30
[Fold 3] Epoch  200 | Train 50.2055 | Val 49.2930 | ES 16/30
[Fold 3] Early stopping at epoch 239 (best Val Loss: 48.8979)
Fold 4: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 69.5981 | Val 63.1793 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 59.6812 | Val 57.9863 | ES 3/30
[Fold 4] Epoch  100 | Train 54.3285 | Val 53.7360 | ES 16/30
[Fold 4] Epoch  150 | Train 50.7938 | Val 52.4582 | ES 4/30
[Fold 4] Early stopping at epoch 188 (best Val Loss: 51.3232)
Fold 5: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 74.8240 | Val 63.2502 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 60.2991 | Val 59.4971 | ES 3/30
[Fold 5] Epoch  100 | Train 56.6956 | Val 53.9842 | ES 8/30
[Fold 5] Early stopping at epoch 122 (best Val Loss: 52.1821)
Fold 6: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 73.9083 | Val 69.9287 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 53.7082 | Val 60.9278 | ES 1/30
[Fold 6] Epoch  100 | Train 52.2646 | Val 59.6816 | ES 17/30
[Fold 6] Epoch  150 | Train 54.5411 | Val 59.6472 | ES 11/30
[Fold 6] Early stopping at epoch 194 (best Val Loss: 58.3618)
Fold 7: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 71.1607 | Val 55.8369 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 56.5498 | Val 50.1940 | ES 0/30
[Fold 7] Epoch  100 | Train 53.2536 | Val 46.0700 | ES 5/30
[Fold 7] Epoch  150 | Train 56.7846 | Val 43.8605 | ES 10/30
[Fold 7] Early stopping at epoch 187 (best Val Loss: 42.8412)
Fold 8: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 72.3158 | Val 52.8882 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 55.7741 | Val 42.3042 | ES 9/30
[Fold 8] Epoch  100 | Train 58.3251 | Val 41.5777 | ES 18/30
[Fold 8] Early stopping at epoch 138 (best Val Loss: 41.0077)
Fold 9: TL on cpu | freeze=1 | lr=0.000499074
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 74.7771 | Val 49.5302 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 65.8091 | Val 46.0189 | ES 0/30
[Fold 9] Epoch  100 | Train 62.3354 | Val 41.3700 | ES 1/30
[Fold 9] Epoch  150 | Train 58.5435 | Val 40.7016 | ES 16/30

[I 2026-02-02 11:33:30,757] Trial 17 finished with value: 49.222513580322264 and parameters: {'learning_rate': 0.0004990740850650059, 'weight_decay': 0.0002337031259398333, 'batch_size': 32, 'dropout_rate': 0.4999985837140921}. Best is trial 11 with value: 43.97364139556885.

[Fold 9] Epoch  200 | Train 58.5862 | Val 40.2968 | ES 5/30
[Fold 9] Early stopping at epoch 225 (best Val Loss: 39.2331)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 71.0928 | Val 60.2194 | ES 0/30
[Fold 0] Epoch   50 | Train 70.9119 | Val 60.9905 | ES 16/30
[Fold 0] Early stopping at epoch 64 (best Val Loss: 59.4135)
Fold 1: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.0105 | Val 62.8871 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 62.8871)
Fold 2: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 71.7996 | Val 51.3752 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 51.3752)
Fold 3: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 70.1462 | Val 62.5688 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 62.5688)
Fold 4: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 71.1799 | Val 65.4732 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 65.4732)
Fold 5: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 75.0225 | Val 63.3013 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 63.3013)
Fold 6: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 72.4350 | Val 68.5416 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 68.5416)
Fold 7: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 76.0536 | Val 56.8618 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 56.8618)
Fold 8: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 74.2157 | Val 52.6120 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 52.6120)
Fold 9: TL on cpu | freeze=1 | lr=3.80943e-05
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 74.4801 | Val 49.9465 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:33:33,288] Trial 18 finished with value: 59.29811820983887 and parameters: {'learning_rate': 3.809429413752461e-05, 'weight_decay': 7.925466398192705e-05, 'batch_size': 32, 'dropout_rate': 0.4316346047341488}. Best is trial 11 with value: 43.97364139556885.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 49.9465)
Fold 0: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 71.7108 | Val 58.0152 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 59.4669 | Val 50.6434 | ES 3/30
[Fold 0] Epoch  100 | Train 55.0163 | Val 49.3320 | ES 8/30
[Fold 0] Early stopping at epoch 146 (best Val Loss: 48.5390)
Fold 1: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 1] Epoch    1 | Train 70.2743 | Val 69.6306 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 62.7100 | Val 65.7453 | ES 0/30
[Fold 1] Epoch  100 | Train 59.6915 | Val 62.3943 | ES 9/30
[Fold 1] Early stopping at epoch 147 (best Val Loss: 58.3983)
Fold 2: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 69.9811 | Val 56.0560 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 63.4064 | Val 53.6066 | ES 16/30
[Fold 2] Epoch  100 | Train 62.7801 | Val 52.3010 | ES 9/30
[Fold 2] Epoch  150 | Train 59.9689 | Val 50.7138 | ES 22/30
[Fold 2] Early stopping at epoch 158 (best Val Loss: 49.2832)
Fold 3: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 70.5086 | Val 62.9636 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 61.9367 | Val 62.0134 | ES 2/30
[Fold 3] Epoch  100 | Train 64.4095 | Val 61.0411 | ES 15/30
[Fold 3] Early stopping at epoch 115 (best Val Loss: 58.7130)
Fold 4: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 69.6707 | Val 69.4429 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 59.3848 | Val 61.1587 | ES 0/30
[Fold 4] Epoch  100 | Train 57.3802 | Val 60.1330 | ES 2/30
[Fold 4] Early stopping at epoch 128 (best Val Loss: 58.1212)
Fold 5: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 72.5089 | Val 67.0664 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 59.2813 | Val 58.9669 | ES 3/30
[Fold 5] Epoch  100 | Train 52.8265 | Val 53.3714 | ES 1/30
[Fold 5] Epoch  150 | Train 51.7967 | Val 52.6737 | ES 10/30
[Fold 5] Early stopping at epoch 170 (best Val Loss: 48.1170)
Fold 6: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 74.4283 | Val 68.7065 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 59.4315 | Val 65.4022 | ES 1/30
[Fold 6] Epoch  100 | Train 53.9470 | Val 62.9898 | ES 25/30
[Fold 6] Early stopping at epoch 105 (best Val Loss: 61.6634)
Fold 7: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 69.8168 | Val 61.8170 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 57.4805 | Val 51.7239 | ES 1/30
[Fold 7] Epoch  100 | Train 51.8252 | Val 46.6796 | ES 0/30
[Fold 7] Epoch  150 | Train 53.6123 | Val 47.1431 | ES 21/30
[Fold 7] Early stopping at epoch 159 (best Val Loss: 45.6108)
Fold 8: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 68.8386 | Val 56.9530 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 62.1815 | Val 47.6947 | ES 0/30
[Fold 8] Epoch  100 | Train 53.8979 | Val 45.8283 | ES 16/30
[Fold 8] Early stopping at epoch 150 (best Val Loss: 42.1436)
Fold 9: TL on cpu | freeze=1 | lr=0.00015147
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 69.9491 | Val 57.5599 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 60.8011 | Val 50.2734 | ES 1/30
[Fold 9] Epoch  100 | Train 58.2587 | Val 39.8095 | ES 4/30
[Fold 9] Epoch  150 | Train 53.5447 | Val 37.8354 | ES 23/30

[I 2026-02-02 11:33:49,451] Trial 19 finished with value: 50.08299446105957 and parameters: {'learning_rate': 0.00015147048859512677, 'weight_decay': 2.0664679425552963e-05, 'batch_size': 16, 'dropout_rate': 0.3997438660504713}. Best is trial 11 with value: 43.97364139556885.

[Fold 9] Early stopping at epoch 182 (best Val Loss: 35.7156)
[freeze_fc1] Best avg RMSE: 43.9736
[freeze_fc1] Best params:  {'learning_rate': 0.0009551946771714858, 'weight_decay': 0.0009459303248566866, 'batch_size': 32, 'dropout_rate': 0.39358067494518556}
Fold 0: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 0] Epoch    1 | Train 68.8147 | Val 60.3517 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 49.4952 | Val 49.7710 | ES 3/30
[Fold 0] Early stopping at epoch 77 (best Val Loss: 48.5614)
Fold 1: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch    1 | Train 71.8698 | Val 62.3215 | ES 0/30
[Fold 1] Epoch   50 | Train 48.7823 | Val 42.9819 | ES 3/30
[Fold 1] Epoch  100 | Train 45.6056 | Val 41.8925 | ES 14/30
[Fold 1] Early stopping at epoch 148 (best Val Loss: 41.0129)
Fold 2: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 2] Epoch    1 | Train 70.5214 | Val 48.2751 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 53.7153 | Val 46.9670 | ES 6/30
[Fold 2] Epoch  100 | Train 46.9063 | Val 45.2915 | ES 25/30
[Fold 2] Early stopping at epoch 105 (best Val Loss: 44.6962)
Fold 3: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 3] Epoch    1 | Train 70.8766 | Val 60.6399 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 47.1523 | Val 48.4677 | ES 1/30
[Fold 3] Early stopping at epoch 86 (best Val Loss: 47.0674)
Fold 4: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 4] Epoch    1 | Train 67.4236 | Val 62.5841 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 48.3417 | Val 50.7359 | ES 3/30
[Fold 4] Epoch  100 | Train 49.7286 | Val 50.7650 | ES 27/30
[Fold 4] Early stopping at epoch 103 (best Val Loss: 49.7274)
Fold 5: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 5] Epoch    1 | Train 72.4795 | Val 61.9776 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 50.1834 | Val 45.1603 | ES 4/30
[Fold 5] Early stopping at epoch 96 (best Val Loss: 43.3871)
Fold 6: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 6] Epoch    1 | Train 68.4537 | Val 66.9641 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 48.1299 | Val 59.7069 | ES 10/30
[Fold 6] Early stopping at epoch 95 (best Val Loss: 58.8862)
Fold 7: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 7] Epoch    1 | Train 69.7555 | Val 54.9485 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 47.5314 | Val 39.9820 | ES 0/30
[Fold 7] Epoch  100 | Train 48.0351 | Val 39.4189 | ES 16/30
[Fold 7] Epoch  150 | Train 46.9887 | Val 39.0873 | ES 8/30
[Fold 7] Early stopping at epoch 172 (best Val Loss: 38.2062)
Fold 8: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 8] Epoch    1 | Train 70.2914 | Val 51.8302 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 48.7642 | Val 43.7818 | ES 10/30
[Fold 8] Early stopping at epoch 70 (best Val Loss: 42.7353)
Fold 9: TL on cpu | freeze=1 | lr=0.000955195
Freeze Level 1: freezing 1 block(s)
[Fold 9] Epoch    1 | Train 71.1527 | Val 49.2253 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 46.5494 | Val 32.8973 | ES 7/30
[Fold 9] Epoch  100 | Train 47.8843 | Val 30.1940 | ES 0/30

[I 2026-02-02 11:33:57,404] A new study created in memory with name: no-name-c74261f8-5a89-4632-8392-bee3e04d1f2e

[Fold 9] Early stopping at epoch 140 (best Val Loss: 30.0884)
[freeze_fc1] Best fold: 9 → artifacts/TL_Ro5/freeze_fc1/final_fold_models/fold_9_best.pth

=== Scenario: freeze_fc1_fc2 | freeze=[1, 1, 0] (level=2) ===
Fold 0: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 70.3329 | Val 61.2052 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 64.3204 | Val 55.8228 | ES 0/30
[Fold 0] Epoch  100 | Train 56.4241 | Val 53.4585 | ES 1/30
[Fold 0] Epoch  150 | Train 54.2470 | Val 52.2749 | ES 5/30
[Fold 0] Early stopping at epoch 175 (best Val Loss: 51.7506)
Fold 1: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 68.0355 | Val 62.8824 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 62.8824)
Fold 2: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 68.8002 | Val 49.1633 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.1633)
Fold 3: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 69.3977 | Val 60.0246 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.0246)
Fold 4: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 67.7350 | Val 64.0269 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 64.0269)
Fold 5: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 71.1587 | Val 62.9768 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 62.9768)
Fold 6: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 66.2632 | Val 67.7261 | ES 0/30
[Fold 6] Epoch   50 | Train 65.8974 | Val 67.8459 | ES 14/30
[Fold 6] Early stopping at epoch 66 (best Val Loss: 67.6236)
Fold 7: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 68.5576 | Val 56.8759 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 56.8759)
Fold 8: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 69.7676 | Val 52.4592 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 52.4592)
Fold 9: TL on cpu | freeze=2 | lr=0.000140639
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 69.8540 | Val 51.5070 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:34:00,167] Trial 0 finished with value: 57.929033279418945 and parameters: {'learning_rate': 0.00014063854695809243, 'weight_decay': 1.242099622107798e-06, 'batch_size': 32, 'dropout_rate': 0.20480953122714005}. Best is trial 0 with value: 57.929033279418945.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 51.5070)
Fold 0: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 71.0655 | Val 60.4801 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 67.7190 | Val 59.6075 | ES 14/30
[Fold 0] Early stopping at epoch 84 (best Val Loss: 58.5853)
Fold 1: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 67.6314 | Val 63.3489 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 63.3489)
Fold 2: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.2088 | Val 49.9252 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.9252)
Fold 3: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 66.9734 | Val 61.0225 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 61.0225)
Fold 4: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 67.7846 | Val 63.4620 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 63.4620)
Fold 5: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 65.9562 | Val 63.2662 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 63.2662)
Fold 6: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 67.9801 | Val 67.9147 | ES 0/30
[Fold 6] Early stopping at epoch 32 (best Val Loss: 67.4339)
Fold 7: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 68.0359 | Val 56.4047 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 56.4047)
Fold 8: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 69.8642 | Val 52.7461 | ES 0/30
[Fold 8] Early stopping at epoch 31 (best Val Loss: 52.7461)
Fold 9: TL on cpu | freeze=2 | lr=5.35238e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 67.2387 | Val 50.3192 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:34:02,290] Trial 1 finished with value: 58.651390075683594 and parameters: {'learning_rate': 5.352378075369102e-05, 'weight_decay': 0.0004428396100283949, 'batch_size': 32, 'dropout_rate': 0.21763283182491222}. Best is trial 0 with value: 57.929033279418945.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 50.3192)
Fold 0: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 71.8818 | Val 59.9064 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 43 (best Val Loss: 59.6207)
Fold 1: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 71.1166 | Val 57.4425 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.4425)
Fold 2: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 74.0056 | Val 46.1722 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 46.1722)
Fold 3: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 69.0506 | Val 57.8855 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 57.8855)
Fold 4: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch    1 | Train 72.8357 | Val 58.7699 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 58.7699)
Fold 5: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch    1 | Train 76.0390 | Val 57.4380 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 57.4380)
Fold 6: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 79.3597 | Val 67.3548 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 67.3548)
Fold 7: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 73.7835 | Val 52.0855 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 52.0855)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 8: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.7644 | Val 49.5082 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 49.5082)
Fold 9: TL on cpu | freeze=2 | lr=7.31315e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 73.2784 | Val 43.7060 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:34:04,574] Trial 2 finished with value: 54.99833030700684 and parameters: {'learning_rate': 7.313145162346762e-05, 'weight_decay': 2.449752019374488e-05, 'batch_size': 64, 'dropout_rate': 0.46896022527229736}. Best is trial 2 with value: 54.99833030700684.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 43.7060)
Fold 0: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 75.2190 | Val 60.4856 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 69.8915 | Val 59.4209 | ES 0/30
[Fold 0] Early stopping at epoch 80 (best Val Loss: 59.4209)
Fold 1: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 71.3589 | Val 57.4653 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.4653)
Fold 2: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.2192 | Val 44.5938 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 44.5938)
Fold 3: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 70.0382 | Val 58.0428 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 58.0428)
Fold 4: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 70.0480 | Val 57.6178 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 57.6178)
Fold 5: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 74.7750 | Val 57.5909 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 57.5909)
Fold 6: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 73.8969 | Val 67.7597 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 67.7597)
Fold 7: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 74.7320 | Val 51.7879 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.7879)
Fold 8: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 74.4455 | Val 48.8002 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 48.8002)
Fold 9: TL on cpu | freeze=2 | lr=4.25925e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 68.0030 | Val 44.1653 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:34:07,130] Trial 3 finished with value: 54.72445411682129 and parameters: {'learning_rate': 4.259249435052429e-05, 'weight_decay': 0.0001099711688560446, 'batch_size': 64, 'dropout_rate': 0.4172101168271201}. Best is trial 3 with value: 54.72445411682129.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 44.1653)
Fold 0: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 69.4963 | Val 56.3147 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 53.7808 | Val 51.0044 | ES 1/30
[Fold 0] Early stopping at epoch 82 (best Val Loss: 50.5188)
Fold 1: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 67.8876 | Val 70.6603 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 54.5021 | Val 62.3727 | ES 9/30
[Fold 1] Epoch  100 | Train 53.6796 | Val 56.1732 | ES 6/30
[Fold 1] Epoch  150 | Train 52.1311 | Val 51.4454 | ES 0/30
[Fold 1] Epoch  200 | Train 49.0482 | Val 50.9579 | ES 25/30
[Fold 1] Early stopping at epoch 205 (best Val Loss: 50.6922)
Fold 2: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 69.6739 | Val 56.5678 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 56.4873 | Val 41.9337 | ES 0/30
[Fold 2] Epoch  100 | Train 53.3672 | Val 41.4755 | ES 29/30
[Fold 2] Early stopping at epoch 101 (best Val Loss: 41.3484)
Fold 3: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 71.3631 | Val 65.9402 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 56.0075 | Val 55.9678 | ES 4/30
[Fold 3] Epoch  100 | Train 48.9055 | Val 52.3376 | ES 3/30
[Fold 3] Early stopping at epoch 144 (best Val Loss: 51.0469)
Fold 4: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 70.4254 | Val 69.9871 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 55.3532 | Val 57.7902 | ES 6/30
[Fold 4] Epoch  100 | Train 55.8771 | Val 55.4078 | ES 0/30
[Fold 4] Epoch  150 | Train 48.2997 | Val 55.6683 | ES 21/30
[Fold 4] Early stopping at epoch 159 (best Val Loss: 55.1272)
Fold 5: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 66.7449 | Val 66.8663 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 53.4783 | Val 54.4547 | ES 0/30
[Fold 5] Epoch  100 | Train 49.7010 | Val 51.6503 | ES 10/30
[Fold 5] Early stopping at epoch 131 (best Val Loss: 50.4410)
Fold 6: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 70.2210 | Val 67.7627 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 55.8606 | Val 63.3250 | ES 5/30
[Fold 6] Epoch  100 | Train 51.1260 | Val 64.0246 | ES 27/30
[Fold 6] Early stopping at epoch 103 (best Val Loss: 61.7719)
Fold 7: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 71.6630 | Val 62.3534 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 54.5136 | Val 46.7051 | ES 2/30
[Fold 7] Epoch  100 | Train 50.9490 | Val 43.1228 | ES 3/30
[Fold 7] Early stopping at epoch 127 (best Val Loss: 41.6265)
Fold 8: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.4448 | Val 60.2651 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 54.6986 | Val 42.8141 | ES 1/30
[Fold 8] Epoch  100 | Train 52.4578 | Val 42.5391 | ES 18/30
[Fold 8] Early stopping at epoch 112 (best Val Loss: 41.2536)
Fold 9: TL on cpu | freeze=2 | lr=0.000360942
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.5081 | Val 57.3852 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 54.5396 | Val 41.9436 | ES 1/30
[Fold 9] Epoch  100 | Train 51.4549 | Val 36.1654 | ES 5/30

[I 2026-02-02 11:34:19,029] Trial 4 finished with value: 47.61222114562988 and parameters: {'learning_rate': 0.0003609422133864663, 'weight_decay': 5.600586589625181e-06, 'batch_size': 16, 'dropout_rate': 0.2769807563832883}. Best is trial 4 with value: 47.61222114562988.

[Fold 9] Epoch  150 | Train 56.2756 | Val 36.2256 | ES 15/30
[Fold 9] Early stopping at epoch 165 (best Val Loss: 35.0840)
Fold 0: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch    1 | Train 69.2874 | Val 60.7721 | ES 0/30
[Fold 0] Epoch   50 | Train 67.9079 | Val 61.2224 | ES 8/30
[Fold 0] Early stopping at epoch 72 (best Val Loss: 59.5492)
Fold 1: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 69.3009 | Val 63.2429 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 63.2429)
Fold 2: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 66.9044 | Val 50.3712 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 50.3712)
Fold 3: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 68.0108 | Val 60.5720 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.5720)
Fold 4: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 66.1929 | Val 63.0939 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 63.0939)
Fold 5: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 65.1252 | Val 62.3414 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 62.3414)
Fold 6: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 69.2716 | Val 67.1243 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 67.1243)
Fold 7: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 71.1019 | Val 55.4248 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 55.4248)
Fold 8: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.0118 | Val 52.7257 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:34:21,188] Trial 5 finished with value: 58.59107894897461 and parameters: {'learning_rate': 1.0974884081266037e-05, 'weight_decay': 3.4586133241965733e-06, 'batch_size': 32, 'dropout_rate': 0.20284365756719555}. Best is trial 4 with value: 47.61222114562988.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 52.7257)
Fold 9: TL on cpu | freeze=2 | lr=1.09749e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 72.6198 | Val 51.4655 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 51.4655)
Fold 0: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 70.4301 | Val 58.7798 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 31 (best Val Loss: 58.7798)
Fold 1: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 68.9264 | Val 57.3514 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.3514)
Fold 2: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 67.5252 | Val 44.4257 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 44.4257)
Fold 3: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 73.9361 | Val 58.0391 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Early stopping at epoch 31 (best Val Loss: 58.0391)
Fold 4: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 67.2367 | Val 58.4354 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 58.4354)
Fold 5: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 70.7173 | Val 57.7373 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 57.7373)
Fold 6: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 71.3859 | Val 67.5899 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 67.5899)
Fold 7: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 70.7024 | Val 51.7836 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.7836)
Fold 8: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 74.1026 | Val 49.2744 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 49.2744)
Fold 9: TL on cpu | freeze=2 | lr=0.000212855
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 69.2430 | Val 44.2588 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:34:23,424] Trial 6 finished with value: 54.76753616333008 and parameters: {'learning_rate': 0.00021285459395786432, 'weight_decay': 4.2814067912189836e-05, 'batch_size': 64, 'dropout_rate': 0.3806078754254609}. Best is trial 4 with value: 47.61222114562988.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 44.2588)
Fold 0: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 73.9485 | Val 57.8986 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 63.4046 | Val 52.9427 | ES 1/30
[Fold 0] Epoch  100 | Train 60.1492 | Val 51.3847 | ES 3/30
[Fold 0] Early stopping at epoch 148 (best Val Loss: 50.4552)
Fold 1: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 70.6655 | Val 68.4442 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 68.4442)
Fold 2: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.0383 | Val 54.8971 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 54.8971)
Fold 3: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 71.2036 | Val 65.3304 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 62.4214 | Val 62.3594 | ES 11/30
[Fold 3] Epoch  100 | Train 66.3039 | Val 61.0430 | ES 16/30
[Fold 3] Early stopping at epoch 114 (best Val Loss: 58.1685)
Fold 4: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 69.5597 | Val 68.7269 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 68.6472 | Val 66.7711 | ES 18/30
[Fold 4] Epoch  100 | Train 62.5299 | Val 66.2928 | ES 13/30
[Fold 4] Early stopping at epoch 117 (best Val Loss: 64.7496)
Fold 5: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 72.1802 | Val 67.7278 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 64.9747 | Val 64.1974 | ES 6/30
[Fold 5] Epoch  100 | Train 63.4410 | Val 58.3571 | ES 2/30
[Fold 5] Early stopping at epoch 128 (best Val Loss: 56.6333)
Fold 6: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 71.3079 | Val 69.6813 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 65.4305 | Val 69.0649 | ES 7/30
[Fold 6] Epoch  100 | Train 62.7665 | Val 67.9293 | ES 17/30
[Fold 6] Early stopping at epoch 113 (best Val Loss: 65.8947)
Fold 7: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 69.5716 | Val 60.2012 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 68.5595 | Val 59.1976 | ES 12/30
[Fold 7] Epoch  100 | Train 67.9855 | Val 62.7477 | ES 14/30
[Fold 7] Early stopping at epoch 116 (best Val Loss: 57.7966)
Fold 8: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 70.8180 | Val 58.3581 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 63.7314 | Val 50.3294 | ES 2/30
[Fold 8] Epoch  100 | Train 61.1882 | Val 47.5438 | ES 2/30
[Fold 8] Early stopping at epoch 149 (best Val Loss: 44.7898)
Fold 9: TL on cpu | freeze=2 | lr=0.000135405
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 71.5079 | Val 59.3463 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 66.3176 | Val 53.9157 | ES 2/30
[Fold 9] Epoch  100 | Train 59.0627 | Val 46.4519 | ES 0/30

[I 2026-02-02 11:34:33,176] Trial 7 finished with value: 56.27319145202637 and parameters: {'learning_rate': 0.0001354046582204827, 'weight_decay': 1.2958446318404308e-05, 'batch_size': 16, 'dropout_rate': 0.4417771502122083}. Best is trial 4 with value: 47.61222114562988.

[Fold 9] Early stopping at epoch 137 (best Val Loss: 44.6610)
Fold 0: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 77.4222 | Val 59.7836 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 60.9304 | Val 53.5619 | ES 7/30
[Fold 0] Early stopping at epoch 88 (best Val Loss: 51.9205)
Fold 1: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 75.3308 | Val 57.2003 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 57.2003)
Fold 2: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 72.1046 | Val 45.7693 | ES 0/30
[Fold 2] Early stopping at epoch 31 (best Val Loss: 45.7693)
Fold 3: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch    1 | Train 71.2041 | Val 58.3375 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 58.3375)
Fold 4: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch    1 | Train 69.5734 | Val 58.4417 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 58.4417)
Fold 5: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 74.3722 | Val 57.6329 | ES 0/30
[Fold 5] Early stopping at epoch 31 (best Val Loss: 57.6329)
Fold 6: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 71.9625 | Val 67.5615 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 31 (best Val Loss: 67.5615)
Fold 7: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 77.0066 | Val 51.7966 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 51.7966)
Fold 8: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 75.6438 | Val 49.5623 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 49.5623)
Fold 9: TL on cpu | freeze=2 | lr=0.00080318
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.5719 | Val 43.7538 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 43.7538)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:34:35,740] Trial 8 finished with value: 54.19763679504395 and parameters: {'learning_rate': 0.0008031798193199768, 'weight_decay': 6.5611766427698485e-06, 'batch_size': 64, 'dropout_rate': 0.4965329006951873}. Best is trial 4 with value: 47.61222114562988.
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 70.0861 | Val 58.6065 | ES 0/30
[Fold 0] Epoch   50 | Train 67.9389 | Val 57.2368 | ES 3/30
[Fold 0] Epoch  100 | Train 66.1597 | Val 57.5248 | ES 20/30
[Fold 0] Epoch  150 | Train 68.8132 | Val 58.3949 | ES 17/30
[Fold 0] Early stopping at epoch 163 (best Val Loss: 55.9325)
Fold 1: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 68.7810 | Val 71.3387 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Early stopping at epoch 31 (best Val Loss: 71.3387)
Fold 2: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.9697 | Val 58.3890 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 66.2968 | Val 61.6878 | ES 26/30
[Fold 2] Early stopping at epoch 54 (best Val Loss: 57.6817)
Fold 3: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 67.6128 | Val 64.4510 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 68.9691 | Val 65.8366 | ES 11/30
[Fold 3] Early stopping at epoch 69 (best Val Loss: 63.3325)
Fold 4: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 66.9823 | Val 68.7368 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Early stopping at epoch 31 (best Val Loss: 68.7368)
Fold 5: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 70.5112 | Val 68.7402 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 68.7402)
Fold 6: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 68.7899 | Val 69.7280 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Early stopping at epoch 38 (best Val Loss: 68.7022)
Fold 7: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 67.5314 | Val 61.7725 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Early stopping at epoch 31 (best Val Loss: 61.7725)
Fold 8: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 68.9052 | Val 56.6667 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Early stopping at epoch 31 (best Val Loss: 56.6667)
Fold 9: TL on cpu | freeze=2 | lr=2.18255e-05
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.8565 | Val 58.9859 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:34:40,484] Trial 9 finished with value: 62.78369979858398 and parameters: {'learning_rate': 2.182550696522319e-05, 'weight_decay': 0.0001971642864707106, 'batch_size': 16, 'dropout_rate': 0.20612541034506865}. Best is trial 4 with value: 47.61222114562988.

[Fold 9] Early stopping at epoch 31 (best Val Loss: 58.9859)
Fold 0: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 70.7122 | Val 56.4498 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 48.9200 | Val 51.2490 | ES 17/30
[Fold 0] Early stopping at epoch 63 (best Val Loss: 49.9970)
Fold 1: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 68.2946 | Val 69.0303 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 54.6787 | Val 54.7210 | ES 1/30
[Fold 1] Epoch  100 | Train 50.1195 | Val 50.3363 | ES 5/30
[Fold 1] Early stopping at epoch 143 (best Val Loss: 49.1373)
Fold 2: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 69.0014 | Val 55.5668 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 56.4633 | Val 41.8380 | ES 1/30
[Fold 2] Epoch  100 | Train 51.1620 | Val 41.7204 | ES 4/30
[Fold 2] Epoch  150 | Train 52.7393 | Val 41.8534 | ES 11/30
[Fold 2] Early stopping at epoch 169 (best Val Loss: 39.9295)
Fold 3: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 68.4012 | Val 65.0697 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 53.3075 | Val 53.6451 | ES 4/30
[Fold 3] Epoch  100 | Train 53.7521 | Val 52.6147 | ES 26/30
[Fold 3] Early stopping at epoch 104 (best Val Loss: 50.7341)
Fold 4: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 69.9124 | Val 68.9345 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 53.0889 | Val 57.2354 | ES 9/30
[Fold 4] Epoch  100 | Train 49.7159 | Val 56.9509 | ES 11/30
[Fold 4] Epoch  150 | Train 55.4566 | Val 58.2862 | ES 25/30
[Fold 4] Early stopping at epoch 155 (best Val Loss: 55.1273)
Fold 5: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 72.5057 | Val 65.1407 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 53.1772 | Val 53.6733 | ES 4/30
[Fold 5] Early stopping at epoch 76 (best Val Loss: 51.3708)
Fold 6: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 68.9942 | Val 68.8488 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 49.1170 | Val 63.9492 | ES 3/30
[Fold 6] Epoch  100 | Train 54.6419 | Val 61.8140 | ES 18/30
[Fold 6] Early stopping at epoch 143 (best Val Loss: 59.5309)
Fold 7: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 71.3174 | Val 61.7412 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 50.6430 | Val 44.1351 | ES 0/30
[Fold 7] Epoch  100 | Train 54.2438 | Val 43.3553 | ES 11/30
[Fold 7] Early stopping at epoch 119 (best Val Loss: 40.4178)
Fold 8: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.8481 | Val 56.1411 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 51.3182 | Val 42.4756 | ES 2/30
[Fold 8] Early stopping at epoch 78 (best Val Loss: 41.4181)
Fold 9: TL on cpu | freeze=2 | lr=0.000558453
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.2736 | Val 56.4891 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 56.8018 | Val 38.5050 | ES 1/30

[I 2026-02-02 11:34:50,776] Trial 10 finished with value: 47.14360313415527 and parameters: {'learning_rate': 0.0005584527119514958, 'weight_decay': 1.044810351853655e-06, 'batch_size': 16, 'dropout_rate': 0.30136292653299823}. Best is trial 10 with value: 47.14360313415527.

[Fold 9] Epoch  100 | Train 53.3133 | Val 37.5138 | ES 14/30
[Fold 9] Early stopping at epoch 116 (best Val Loss: 35.4645)
Fold 0: TL on cpu | freeze=2 | lr=0.000587469

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 68.2000 | Val 56.3382 | ES 0/30
[Fold 0] Epoch   50 | Train 51.5507 | Val 51.3649 | ES 20/30
[Fold 0] Early stopping at epoch 60 (best Val Loss: 49.9319)
Fold 1: TL on cpu | freeze=2 | lr=0.000587469
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 70.4925 | Val 70.3970 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 52.0581 | Val 52.2241 | ES 0/30
[Fold 1] Epoch  100 | Train 52.7995 | Val 50.1801 | ES 3/30
[Fold 1] Early stopping at epoch 127 (best Val Loss: 48.3583)
Fold 2: TL on cpu | freeze=2 | lr=0.000587469
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.4856 | Val 55.3947 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 52.9232 | Val 41.6327 | ES 8/30
[Fold 2] Epoch  100 | Train 51.5298 | Val 41.4597 | ES 28/30
[Fold 2] Early stopping at epoch 102 (best Val Loss: 40.8968)
Fold 3: TL on cpu | freeze=2 | lr=0.000587469
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 69.0077 | Val 64.1952 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 53.4585 | Val 53.5864 | ES 6/30
[Fold 3] Early stopping at epoch 97 (best Val Loss: 50.6931)
Fold 4: TL on cpu | freeze=2 | lr=0.000587469
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 70.0328 | Val 69.4889 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 51.3663 | Val 55.3338 | ES 0/30
[Fold 4] Epoch  100 | Train 52.4441 | Val 55.7750 | ES 22/30
[Fold 4] Early stopping at epoch 108 (best Val Loss: 54.7195)
Fold 5: TL on cpu | freeze=2 | lr=0.000587469
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 68.4290 | Val 67.1266 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 54.7282 | Val 52.8810 | ES 2/30
[Fold 5] Epoch  100 | Train 50.1473 | Val 52.6801 | ES 8/30
[Fold 5] Early stopping at epoch 122 (best Val Loss: 49.6187)
Fold 6: TL on cpu | freeze=2 | lr=0.000587469
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 69.2099 | Val 68.0856 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 48.9092 | Val 63.1246 | ES 20/30
[Fold 6] Early stopping at epoch 100 (best Val Loss: 60.7833)
Fold 7: TL on cpu | freeze=2 | lr=0.000587469
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 68.7477 | Val 60.4041 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 53.9866 | Val 45.1462 | ES 4/30
[Fold 7] Early stopping at epoch 99 (best Val Loss: 41.5619)
Fold 8: TL on cpu | freeze=2 | lr=0.000587469
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.9951 | Val 57.4730 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 52.7059 | Val 42.3781 | ES 3/30
[Fold 8] Early stopping at epoch 85 (best Val Loss: 40.9005)
Fold 9: TL on cpu | freeze=2 | lr=0.000587469
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 67.3545 | Val 58.0131 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 55.0616 | Val 36.8050 | ES 0/30

[I 2026-02-02 11:35:00,100] Trial 11 finished with value: 47.03233642578125 and parameters: {'learning_rate': 0.0005874687235390675, 'weight_decay': 1.1685517407189745e-06, 'batch_size': 16, 'dropout_rate': 0.2939789609870561}. Best is trial 11 with value: 47.03233642578125.

[Fold 9] Epoch  100 | Train 53.4718 | Val 36.2620 | ES 11/30
[Fold 9] Early stopping at epoch 119 (best Val Loss: 34.9997)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 73.0409 | Val 57.2230 | ES 0/30
[Fold 0] Epoch   50 | Train 53.0495 | Val 52.1696 | ES 20/30
[Fold 0] Early stopping at epoch 60 (best Val Loss: 50.2718)
Fold 1: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 67.2704 | Val 70.8935 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 48.5927 | Val 49.3822 | ES 0/30
[Fold 1] Epoch  100 | Train 51.8121 | Val 49.4357 | ES 14/30
[Fold 1] Early stopping at epoch 147 (best Val Loss: 47.2326)
Fold 2: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.5366 | Val 54.8818 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 51.3948 | Val 41.5601 | ES 9/30
[Fold 2] Epoch  100 | Train 50.0206 | Val 41.1941 | ES 23/30
[Fold 2] Early stopping at epoch 107 (best Val Loss: 40.6438)
Fold 3: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 68.7723 | Val 64.4585 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 50.0090 | Val 52.2633 | ES 2/30
[Fold 3] Early stopping at epoch 90 (best Val Loss: 50.1024)
Fold 4: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 69.3751 | Val 66.9152 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 54.3345 | Val 54.8955 | ES 0/30
[Fold 4] Early stopping at epoch 80 (best Val Loss: 54.8955)
Fold 5: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 67.8948 | Val 65.4885 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 52.3394 | Val 51.4546 | ES 1/30
[Fold 5] Early stopping at epoch 90 (best Val Loss: 50.6086)
Fold 6: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 69.6032 | Val 69.4809 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 55.5538 | Val 60.6257 | ES 3/30
[Fold 6] Epoch  100 | Train 49.7098 | Val 60.3020 | ES 14/30
[Fold 6] Epoch  150 | Train 49.3118 | Val 59.7020 | ES 9/30
[Fold 6] Early stopping at epoch 171 (best Val Loss: 56.8266)
Fold 7: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 71.1343 | Val 61.0225 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 55.6794 | Val 43.6833 | ES 2/30
[Fold 7] Early stopping at epoch 83 (best Val Loss: 40.5707)
Fold 8: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.0403 | Val 57.2850 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 50.5511 | Val 41.8049 | ES 20/30
[Fold 8] Early stopping at epoch 60 (best Val Loss: 40.5092)
Fold 9: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.7814 | Val 58.4075 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 51.5526 | Val 36.2636 | ES 4/30

[I 2026-02-02 11:35:08,976] Trial 12 finished with value: 46.32807960510254 and parameters: {'learning_rate': 0.0009364489305091467, 'weight_decay': 1.1318639610919661e-06, 'batch_size': 16, 'dropout_rate': 0.3039144530075713}. Best is trial 12 with value: 46.32807960510254.

[Fold 9] Early stopping at epoch 83 (best Val Loss: 34.5987)
Fold 0: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 70.0526 | Val 57.1650 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 55.2399 | Val 51.5361 | ES 9/30
[Fold 0] Early stopping at epoch 71 (best Val Loss: 50.5828)
Fold 1: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 72.3035 | Val 69.8983 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 52.2872 | Val 51.4320 | ES 1/30
[Fold 1] Early stopping at epoch 89 (best Val Loss: 48.8426)
Fold 2: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 67.0290 | Val 53.9723 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 52.9161 | Val 40.5225 | ES 3/30
[Fold 2] Early stopping at epoch 77 (best Val Loss: 40.3436)
Fold 3: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 66.6301 | Val 61.7376 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 49.4806 | Val 53.2578 | ES 8/30
[Fold 3] Epoch  100 | Train 52.9172 | Val 51.9502 | ES 27/30
[Fold 3] Early stopping at epoch 103 (best Val Loss: 50.0325)
Fold 4: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 71.6996 | Val 66.9612 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 51.3026 | Val 55.4622 | ES 10/30
[Fold 4] Epoch  100 | Train 51.0521 | Val 55.7872 | ES 10/30
[Fold 4] Epoch  150 | Train 54.1919 | Val 55.9478 | ES 16/30
[Fold 4] Early stopping at epoch 164 (best Val Loss: 53.6731)
Fold 5: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 71.1591 | Val 65.5840 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 52.3005 | Val 53.5390 | ES 3/30
[Fold 5] Epoch  100 | Train 51.0412 | Val 51.3013 | ES 4/30
[Fold 5] Early stopping at epoch 126 (best Val Loss: 49.8298)
Fold 6: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 67.9588 | Val 68.8621 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 50.6295 | Val 62.0413 | ES 1/30
[Fold 6] Early stopping at epoch 91 (best Val Loss: 60.8472)
Fold 7: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 73.7816 | Val 59.8621 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 52.6534 | Val 44.1506 | ES 8/30
[Fold 7] Early stopping at epoch 96 (best Val Loss: 41.4532)
Fold 8: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 70.3036 | Val 54.8629 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 53.9281 | Val 42.0179 | ES 5/30
[Fold 8] Early stopping at epoch 75 (best Val Loss: 41.2985)
Fold 9: TL on cpu | freeze=2 | lr=0.000900056
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.2545 | Val 58.8459 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 51.6336 | Val 36.9731 | ES 6/30
[Fold 9] Epoch  100 | Train 51.2512 | Val 36.1351 | ES 11/30

[I 2026-02-02 11:35:18,176] Trial 13 finished with value: 46.92441291809082 and parameters: {'learning_rate': 0.0009000555297296147, 'weight_decay': 2.1672261006454107e-06, 'batch_size': 16, 'dropout_rate': 0.3179191318035021}. Best is trial 12 with value: 46.32807960510254.

[Fold 9] Early stopping at epoch 139 (best Val Loss: 34.4180)
Fold 0: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 72.0731 | Val 57.4182 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 43 (best Val Loss: 50.5103)
Fold 1: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 70.3265 | Val 67.4875 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 52.8138 | Val 51.0494 | ES 11/30
[Fold 1] Early stopping at epoch 88 (best Val Loss: 49.8719)
Fold 2: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.8210 | Val 54.8806 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 52.0773 | Val 41.6921 | ES 2/30
[Fold 2] Epoch  100 | Train 50.1012 | Val 41.0666 | ES 5/30
[Fold 2] Early stopping at epoch 125 (best Val Loss: 39.9895)
Fold 3: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 67.3004 | Val 62.7125 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 52.2056 | Val 53.6516 | ES 11/30
[Fold 3] Early stopping at epoch 69 (best Val Loss: 52.6499)
Fold 4: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 71.1757 | Val 69.4311 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 52.2365 | Val 57.6223 | ES 25/30
[Fold 4] Early stopping at epoch 55 (best Val Loss: 56.3333)
Fold 5: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 68.3758 | Val 66.0994 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 50.8117 | Val 51.9494 | ES 16/30
[Fold 5] Early stopping at epoch 64 (best Val Loss: 51.5626)
Fold 6: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 68.5127 | Val 69.7862 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 53.8456 | Val 64.8264 | ES 3/30
[Fold 6] Epoch  100 | Train 51.3418 | Val 62.6342 | ES 8/30
[Fold 6] Early stopping at epoch 122 (best Val Loss: 60.7001)
Fold 7: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch    1 | Train 70.5627 | Val 60.9948 | ES 0/30
[Fold 7] Epoch   50 | Train 56.0272 | Val 45.0721 | ES 9/30
[Fold 7] Early stopping at epoch 100 (best Val Loss: 41.8179)
Fold 8: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.3849 | Val 57.6850 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 52.8581 | Val 42.7086 | ES 25/30
[Fold 8] Early stopping at epoch 55 (best Val Loss: 40.9643)
Fold 9: TL on cpu | freeze=2 | lr=0.000949058
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 71.2353 | Val 57.0449 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 55.3452 | Val 36.8108 | ES 5/30

[I 2026-02-02 11:35:25,315] Trial 14 finished with value: 47.74890365600586 and parameters: {'learning_rate': 0.0009490582125964063, 'weight_decay': 3.1870179734435785e-06, 'batch_size': 16, 'dropout_rate': 0.35422848462731343}. Best is trial 12 with value: 46.32807960510254.

[Fold 9] Early stopping at epoch 93 (best Val Loss: 34.6572)
Fold 0: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 69.4348 | Val 58.3398 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 54.6031 | Val 50.6271 | ES 9/30
[Fold 0] Early stopping at epoch 71 (best Val Loss: 50.0524)
Fold 1: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 70.1226 | Val 70.7751 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 58.0615 | Val 64.0672 | ES 0/30
[Fold 1] Epoch  100 | Train 54.6619 | Val 59.6174 | ES 1/30
[Fold 1] Epoch  150 | Train 53.6361 | Val 58.5801 | ES 6/30
[Fold 1] Early stopping at epoch 191 (best Val Loss: 56.8237)
Fold 2: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.4778 | Val 56.3271 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 53.5634 | Val 43.6503 | ES 0/30
[Fold 2] Epoch  100 | Train 51.8467 | Val 42.1097 | ES 9/30
[Fold 2] Epoch  150 | Train 53.6067 | Val 41.2193 | ES 29/30
[Fold 2] Early stopping at epoch 151 (best Val Loss: 40.7872)
Fold 3: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 67.4900 | Val 63.1015 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 56.4940 | Val 55.1359 | ES 0/30
[Fold 3] Epoch  100 | Train 50.0863 | Val 52.9635 | ES 13/30
[Fold 3] Epoch  150 | Train 48.7400 | Val 52.4238 | ES 15/30
[Fold 3] Early stopping at epoch 187 (best Val Loss: 51.0528)
Fold 4: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 69.1119 | Val 67.7528 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 52.2965 | Val 60.1963 | ES 11/30
[Fold 4] Epoch  100 | Train 50.0839 | Val 59.1009 | ES 18/30
[Fold 4] Early stopping at epoch 135 (best Val Loss: 56.3686)
Fold 5: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 69.9784 | Val 68.7689 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 55.1344 | Val 55.9968 | ES 3/30
[Fold 5] Epoch  100 | Train 48.7026 | Val 52.7064 | ES 6/30
[Fold 5] Early stopping at epoch 124 (best Val Loss: 50.3145)
Fold 6: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 66.6446 | Val 68.4014 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 52.3593 | Val 63.7390 | ES 1/30
[Fold 6] Epoch  100 | Train 50.2128 | Val 64.2056 | ES 3/30
[Fold 6] Epoch  150 | Train 52.2018 | Val 62.4863 | ES 28/30
[Fold 6] Early stopping at epoch 152 (best Val Loss: 60.9627)
Fold 7: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 67.4860 | Val 60.6214 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 55.7918 | Val 48.5455 | ES 3/30
[Fold 7] Epoch  100 | Train 51.0470 | Val 44.9527 | ES 9/30
[Fold 7] Epoch  150 | Train 48.7631 | Val 44.2886 | ES 9/30
[Fold 7] Early stopping at epoch 171 (best Val Loss: 41.7931)
Fold 8: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 68.1014 | Val 60.7560 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 60.0794 | Val 45.3534 | ES 1/30
[Fold 8] Epoch  100 | Train 55.9382 | Val 41.5432 | ES 11/30
[Fold 8] Early stopping at epoch 119 (best Val Loss: 41.3626)
Fold 9: TL on cpu | freeze=2 | lr=0.000307536
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 70.1863 | Val 59.2194 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 55.0823 | Val 42.6341 | ES 0/30
[Fold 9] Epoch  100 | Train 52.0114 | Val 37.3234 | ES 6/30

[I 2026-02-02 11:35:38,277] Trial 15 finished with value: 48.19162826538086 and parameters: {'learning_rate': 0.0003075362811678319, 'weight_decay': 2.2653049755906523e-06, 'batch_size': 16, 'dropout_rate': 0.2623431480815909}. Best is trial 12 with value: 46.32807960510254.

[Fold 9] Epoch  150 | Train 53.4438 | Val 35.5925 | ES 9/30
[Fold 9] Early stopping at epoch 171 (best Val Loss: 34.9749)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 0: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 69.2527 | Val 56.5169 | ES 0/30
[Fold 0] Epoch   50 | Train 56.1978 | Val 51.0954 | ES 19/30
[Fold 0] Early stopping at epoch 92 (best Val Loss: 49.8900)
Fold 1: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 67.9781 | Val 69.2875 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 50.9370 | Val 55.1574 | ES 1/30
[Fold 1] Epoch  100 | Train 51.2962 | Val 49.9652 | ES 0/30
[Fold 1] Early stopping at epoch 140 (best Val Loss: 49.3430)
Fold 2: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 69.3314 | Val 54.8908 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 57.1816 | Val 42.9012 | ES 3/30
[Fold 2] Epoch  100 | Train 49.2740 | Val 41.6307 | ES 7/30
[Fold 2] Early stopping at epoch 123 (best Val Loss: 40.3651)
Fold 3: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch    1 | Train 68.6514 | Val 63.5038 | ES 0/30
[Fold 3] Epoch   50 | Train 56.4191 | Val 54.9085 | ES 6/30
[Fold 3] Epoch  100 | Train 52.6402 | Val 53.3177 | ES 12/30
[Fold 3] Early stopping at epoch 118 (best Val Loss: 52.2418)
Fold 4: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.5620 | Val 68.2502 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 52.6436 | Val 58.2947 | ES 2/30
[Fold 4] Epoch  100 | Train 50.4789 | Val 57.0761 | ES 1/30
[Fold 4] Early stopping at epoch 139 (best Val Loss: 55.2483)
Fold 5: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 73.8370 | Val 65.3976 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 55.6890 | Val 52.5884 | ES 0/30
[Fold 5] Epoch  100 | Train 54.9037 | Val 51.8016 | ES 20/30
[Fold 5] Early stopping at epoch 132 (best Val Loss: 51.4586)
Fold 6: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 69.7056 | Val 68.6697 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 52.5469 | Val 64.2852 | ES 24/30
[Fold 6] Early stopping at epoch 56 (best Val Loss: 63.5882)
Fold 7: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 68.9998 | Val 58.1876 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 57.4205 | Val 46.3439 | ES 1/30
[Fold 7] Epoch  100 | Train 54.8440 | Val 42.7471 | ES 13/30
[Fold 7] Early stopping at epoch 117 (best Val Loss: 42.4216)
Fold 8: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 69.8374 | Val 57.8234 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 55.8504 | Val 42.8140 | ES 3/30
[Fold 8] Epoch  100 | Train 51.8252 | Val 42.1573 | ES 1/30
[Fold 8] Early stopping at epoch 129 (best Val Loss: 41.1580)
Fold 9: TL on cpu | freeze=2 | lr=0.000437869
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 68.0279 | Val 58.1463 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 53.2830 | Val 41.0611 | ES 2/30
[Fold 9] Epoch  100 | Train 55.2096 | Val 37.1958 | ES 11/30
[Fold 9] Epoch  150 | Train 53.8133 | Val 36.4853 | ES 26/30

[I 2026-02-02 11:35:48,905] Trial 16 finished with value: 47.926699829101565 and parameters: {'learning_rate': 0.00043786863582489567, 'weight_decay': 1.0307801657673764e-05, 'batch_size': 16, 'dropout_rate': 0.3261588202103531}. Best is trial 12 with value: 46.32807960510254.

[Fold 9] Early stopping at epoch 183 (best Val Loss: 35.6814)
Fold 0: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 72.3914 | Val 57.6630 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 60.4453 | Val 51.0706 | ES 0/30
[Fold 0] Early stopping at epoch 94 (best Val Loss: 50.1541)
Fold 1: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 68.5142 | Val 71.6660 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 58.9672 | Val 63.9965 | ES 2/30
[Fold 1] Epoch  100 | Train 56.4077 | Val 58.2165 | ES 2/30
[Fold 1] Early stopping at epoch 144 (best Val Loss: 55.4372)
Fold 2: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 71.4453 | Val 54.6399 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 59.3365 | Val 51.4540 | ES 6/30
[Fold 2] Epoch  100 | Train 60.5287 | Val 47.0444 | ES 8/30
[Fold 2] Epoch  150 | Train 57.9133 | Val 49.0264 | ES 13/30
[Fold 2] Early stopping at epoch 167 (best Val Loss: 45.6586)
Fold 3: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 70.9104 | Val 63.6686 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 61.1879 | Val 56.2445 | ES 0/30
[Fold 3] Early stopping at epoch 91 (best Val Loss: 54.3437)
Fold 4: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.2947 | Val 68.5196 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 60.2575 | Val 62.1744 | ES 1/30
[Fold 4] Epoch  100 | Train 57.7553 | Val 58.2026 | ES 6/30
[Fold 4] Epoch  150 | Train 54.5300 | Val 57.9892 | ES 16/30
[Fold 4] Early stopping at epoch 164 (best Val Loss: 55.7072)
Fold 5: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 72.6721 | Val 68.4610 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 58.1420 | Val 61.5598 | ES 2/30
[Fold 5] Epoch  100 | Train 60.8308 | Val 54.3773 | ES 10/30
[Fold 5] Epoch  150 | Train 57.8645 | Val 54.4946 | ES 15/30
[Fold 5] Early stopping at epoch 197 (best Val Loss: 52.8104)
Fold 6: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 70.9699 | Val 68.8863 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 58.7004 | Val 65.1295 | ES 8/30
[Fold 6] Epoch  100 | Train 51.4785 | Val 63.8259 | ES 6/30
[Fold 6] Early stopping at epoch 124 (best Val Loss: 62.7814)
Fold 7: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 71.5371 | Val 59.2887 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 64.7704 | Val 57.5170 | ES 3/30
[Fold 7] Epoch  100 | Train 61.2900 | Val 51.9077 | ES 10/30
[Fold 7] Epoch  150 | Train 57.2317 | Val 49.9852 | ES 16/30
[Fold 7] Early stopping at epoch 164 (best Val Loss: 47.5433)
Fold 8: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 68.4704 | Val 60.3143 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 62.3821 | Val 47.3631 | ES 5/30
[Fold 8] Epoch  100 | Train 55.7951 | Val 44.1951 | ES 4/30
[Fold 8] Epoch  150 | Train 53.1155 | Val 42.5960 | ES 15/30
[Fold 8] Early stopping at epoch 165 (best Val Loss: 40.8620)
Fold 9: TL on cpu | freeze=2 | lr=0.000216469
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 71.4742 | Val 61.5382 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 58.6533 | Val 50.0202 | ES 2/30
[Fold 9] Epoch  100 | Train 58.0636 | Val 39.7686 | ES 0/30
[Fold 9] Epoch  150 | Train 53.6093 | Val 38.4393 | ES 1/30
[Fold 9] Epoch  200 | Train 54.0438 | Val 38.9002 | ES 13/30

[I 2026-02-02 11:36:02,091] Trial 17 finished with value: 50.069295501708986 and parameters: {'learning_rate': 0.00021646922253221927, 'weight_decay': 3.201777528310012e-05, 'batch_size': 16, 'dropout_rate': 0.3683995196188316}. Best is trial 12 with value: 46.32807960510254.

[Fold 9] Early stopping at epoch 244 (best Val Loss: 37.4621)
Fold 0: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 69.3700 | Val 57.0097 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Early stopping at epoch 44 (best Val Loss: 49.9980)
Fold 1: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 70.9778 | Val 70.5583 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 51.6499 | Val 49.4526 | ES 0/30
[Fold 1] Epoch  100 | Train 50.3470 | Val 49.8946 | ES 16/30
[Fold 1] Early stopping at epoch 146 (best Val Loss: 47.6040)
Fold 2: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 69.6995 | Val 53.2690 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 49.9780 | Val 40.4684 | ES 0/30
[Fold 2] Early stopping at epoch 86 (best Val Loss: 40.1319)
Fold 3: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 66.5134 | Val 62.8500 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 49.9210 | Val 52.3745 | ES 3/30
[Fold 3] Early stopping at epoch 77 (best Val Loss: 51.1492)
Fold 4: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 68.1161 | Val 65.4964 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 52.4859 | Val 56.6022 | ES 11/30
[Fold 4] Early stopping at epoch 83 (best Val Loss: 54.0544)
Fold 5: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 73.8947 | Val 66.4981 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 47.3590 | Val 53.2666 | ES 18/30
[Fold 5] Epoch  100 | Train 47.8747 | Val 51.5844 | ES 5/30
[Fold 5] Early stopping at epoch 125 (best Val Loss: 49.3834)
Fold 6: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 69.9596 | Val 69.2824 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 46.6355 | Val 61.9296 | ES 29/30
[Fold 6] Early stopping at epoch 51 (best Val Loss: 60.7425)
Fold 7: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 68.8392 | Val 60.8678 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 47.2835 | Val 42.5765 | ES 4/30
[Fold 7] Early stopping at epoch 76 (best Val Loss: 40.9088)
Fold 8: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 70.0643 | Val 57.0960 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 48.3705 | Val 42.9602 | ES 15/30
[Fold 8] Early stopping at epoch 65 (best Val Loss: 41.3819)
Fold 9: TL on cpu | freeze=2 | lr=0.000994609
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 69.3648 | Val 57.7902 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 51.9119 | Val 36.9287 | ES 9/30

[I 2026-02-02 11:36:09,681] Trial 18 finished with value: 46.7679328918457 and parameters: {'learning_rate': 0.000994609325689326, 'weight_decay': 2.349014288452408e-06, 'batch_size': 16, 'dropout_rate': 0.2501328049466667}. Best is trial 12 with value: 46.32807960510254.

[Fold 9] Early stopping at epoch 97 (best Val Loss: 34.5523)
Fold 0: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 71.6641 | Val 60.3460 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 58.4626 | Val 54.2041 | ES 1/30
[Fold 0] Epoch  100 | Train 54.9187 | Val 51.7068 | ES 1/30
[Fold 0] Early stopping at epoch 141 (best Val Loss: 51.0509)
Fold 1: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 68.0027 | Val 62.3530 | ES 0/30
[Fold 1] Early stopping at epoch 31 (best Val Loss: 62.3530)
Fold 2: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 70.0556 | Val 49.9553 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Early stopping at epoch 31 (best Val Loss: 49.9553)
Fold 3: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 66.7464 | Val 60.5953 | ES 0/30
[Fold 3] Early stopping at epoch 31 (best Val Loss: 60.5953)

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

Fold 4: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 66.6643 | Val 63.5598 | ES 0/30
[Fold 4] Early stopping at epoch 31 (best Val Loss: 63.5598)
Fold 5: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 70.3200 | Val 63.1807 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Early stopping at epoch 31 (best Val Loss: 63.1807)
Fold 6: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 68.5677 | Val 67.4180 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 61.9178 | Val 66.9914 | ES 11/30
[Fold 6] Early stopping at epoch 94 (best Val Loss: 65.1251)
Fold 7: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 71.5557 | Val 56.0265 | ES 0/30
[Fold 7] Early stopping at epoch 31 (best Val Loss: 56.0265)
Fold 8: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 71.4106 | Val 52.7549 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)
[I 2026-02-02 11:36:12,526] Trial 19 finished with value: 57.50232696533203 and parameters: {'learning_rate': 0.0002508926429335451, 'weight_decay': 9.502051277360507e-05, 'batch_size': 32, 'dropout_rate': 0.24710627449059108}. Best is trial 12 with value: 46.32807960510254.

[Fold 8] Early stopping at epoch 31 (best Val Loss: 52.7549)
Fold 9: TL on cpu | freeze=2 | lr=0.000250893
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 68.7443 | Val 50.4217 | ES 0/30
[Fold 9] Early stopping at epoch 31 (best Val Loss: 50.4217)
[freeze_fc1_fc2] Best avg RMSE: 46.3281
[freeze_fc1_fc2] Best params:  {'learning_rate': 0.0009364489305091467, 'weight_decay': 1.1318639610919661e-06, 'batch_size': 16, 'dropout_rate': 0.3039144530075713}
Fold 0: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 0] Epoch    1 | Train 71.0056 | Val 55.8038 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 0] Epoch   50 | Train 50.8805 | Val 52.1813 | ES 26/30
[Fold 0] Early stopping at epoch 54 (best Val Loss: 50.3453)
Fold 1: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 1] Epoch    1 | Train 67.2927 | Val 69.1891 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 1] Epoch   50 | Train 52.3394 | Val 51.6023 | ES 2/30
[Fold 1] Epoch  100 | Train 51.2107 | Val 49.0331 | ES 16/30
[Fold 1] Early stopping at epoch 138 (best Val Loss: 47.4231)
Fold 2: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 2] Epoch    1 | Train 69.7072 | Val 54.9716 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 2] Epoch   50 | Train 52.4089 | Val 40.8647 | ES 16/30
[Fold 2] Early stopping at epoch 64 (best Val Loss: 40.5623)
Fold 3: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 3] Epoch    1 | Train 69.1324 | Val 63.1634 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 3] Epoch   50 | Train 52.1722 | Val 53.2036 | ES 1/30
[Fold 3] Epoch  100 | Train 51.5764 | Val 51.8531 | ES 17/30
[Fold 3] Epoch  150 | Train 50.5065 | Val 53.2426 | ES 7/30
[Fold 3] Early stopping at epoch 173 (best Val Loss: 51.0630)
Fold 4: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 4] Epoch    1 | Train 69.4496 | Val 69.8996 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 4] Epoch   50 | Train 52.0219 | Val 56.6434 | ES 11/30
[Fold 4] Early stopping at epoch 69 (best Val Loss: 55.1916)
Fold 5: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 5] Epoch    1 | Train 74.6132 | Val 67.0476 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 5] Epoch   50 | Train 47.7751 | Val 52.7436 | ES 9/30
[Fold 5] Early stopping at epoch 89 (best Val Loss: 50.3835)
Fold 6: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 6] Epoch    1 | Train 67.8932 | Val 68.8854 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 6] Epoch   50 | Train 50.5594 | Val 60.1913 | ES 3/30
[Fold 6] Epoch  100 | Train 47.2196 | Val 57.6891 | ES 8/30
[Fold 6] Early stopping at epoch 150 (best Val Loss: 57.0479)
Fold 7: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 7] Epoch    1 | Train 72.3710 | Val 60.3712 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 7] Epoch   50 | Train 51.9672 | Val 42.8665 | ES 8/30
[Fold 7] Early stopping at epoch 85 (best Val Loss: 41.2073)
Fold 8: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 8] Epoch    1 | Train 69.0591 | Val 58.8521 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 8] Epoch   50 | Train 52.0569 | Val 41.6986 | ES 19/30
[Fold 8] Early stopping at epoch 61 (best Val Loss: 41.0970)
Fold 9: TL on cpu | freeze=2 | lr=0.000936449
Freeze Level 2: freezing 2 block(s)
[Fold 9] Epoch    1 | Train 69.9012 | Val 56.4841 | ES 0/30

/Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/NN_model_helper.py:428: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(baseline_ckpt, map_location=device)

[Fold 9] Epoch   50 | Train 52.8830 | Val 35.4944 | ES 0/30
[Fold 9] Early stopping at epoch 100 (best Val Loss: 34.0826)
[freeze_fc1_fc2] Best fold: 9 → artifacts/TL_Ro5/freeze_fc1_fc2/final_fold_models/fold_9_best.pth

Summary: {
  "no_freeze": {
    "best": 41.86210613250732,
    "manifest": {
      "scenario": "no_freeze",
      "freeze_vector": [
        0,
        0,
        0
      ],
      "freeze_level": 0,
      "best_fold": 9,
      "checkpoint": "artifacts/TL_Ro5/no_freeze/final_fold_models/fold_9_best.pth",
      "hidden_layers": [
        224,
        112,
        56
      ],
      "best_params": {
        "learning_rate": 0.0008391407174139767,
        "weight_decay": 0.00010108606474819895,
        "batch_size": 16,
        "dropout_rate": 0.3361295973831194
      }
    }
  },
  "freeze_fc1": {
    "best": 43.97364139556885,
    "manifest": {
      "scenario": "freeze_fc1",
      "freeze_vector": [
        1,
        0,
        0
      ],
      "freeze_level": 1,
      "best_fold": 9,
      "checkpoint": "artifacts/TL_Ro5/freeze_fc1/final_fold_models/fold_9_best.pth",
      "hidden_layers": [
        224,
        112,
        56
      ],
      "best_params": {
        "learning_rate": 0.0009551946771714858,
        "weight_decay": 0.0009459303248566866,
        "batch_size": 32,
        "dropout_rate": 0.39358067494518556
      }
    }
  },
  "freeze_fc1_fc2": {
    "best": 46.32807960510254,
    "manifest": {
      "scenario": "freeze_fc1_fc2",
      "freeze_vector": [
        1,
        1,
        0
      ],
      "freeze_level": 2,
      "best_fold": 9,
      "checkpoint": "artifacts/TL_Ro5/freeze_fc1_fc2/final_fold_models/fold_9_best.pth",
      "hidden_layers": [
        224,
        112,
        56
      ],
      "best_params": {
        "learning_rate": 0.0009364489305091467,
        "weight_decay": 1.1318639610919661e-06,
        "batch_size": 16,
        "dropout_rate": 0.3039144530075713
      }
    }
  }
}

In [11]:
from NN_model import ImprovedNN
import torch
import pandas as pd
from pathlib import Path
import json

def load_best_models_for_scenarios(
    root_dir="artifacts/TL_Ro5",
    scenarios=("no_freeze", "freeze_fc1", "freeze_fc1_fc2"),
):
    root_dir = Path(root_dir)
    models = {}
    manifests = {}

    for tag in scenarios:
        manifest_path = root_dir / tag / "manifest.json"
        cv_metrics_path = root_dir / tag / "cv_final_metrics.csv"

        # Load manifest
        with open(manifest_path, "r") as f:
            manifest = json.load(f)
        manifests[tag] = manifest

        # Load best RMSE from cv_final_metrics.csv
        cv_df = pd.read_csv(cv_metrics_path)
        best_row = cv_df.sort_values("rmse").iloc[0]
        best_rmse = float(best_row["rmse"])

        # Load checkpoint
        ckpt_path = Path(best_row["checkpoint"]).resolve()
        state = torch.load(ckpt_path, map_location="cpu")

        # Build model
        input_size = state["network.0.weight"].shape[1]
        hidden_layers = manifest["hidden_layers"]
        dropout_rate = manifest["best_params"]["dropout_rate"]

        model = ImprovedNN(
            input_size=input_size,
            hidden_layers=hidden_layers,
            dropout_rate=dropout_rate,
        )
        model.load_state_dict(state)
        model.eval()

        models[tag] = model

        print(f"Loaded model for scenario '{tag}'")
        print(f"  └─ Best fold checkpoint: {ckpt_path}")
        print(f"  └─ Best RMSE: {best_rmse:.4f}\n")

    return models, manifests

models, manifests = load_best_models_for_scenarios(
    root_dir="artifacts/TL_Ro5",
    scenarios=["no_freeze", "freeze_fc1", "freeze_fc1_fc2"]
)

Loaded model for scenario 'no_freeze'
  └─ Best fold checkpoint: /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/TL_Ro5/no_freeze/final_fold_models/fold_9_best.pth
  └─ Best RMSE: 27.7796

Loaded model for scenario 'freeze_fc1'
  └─ Best fold checkpoint: /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/TL_Ro5/freeze_fc1/final_fold_models/fold_9_best.pth
  └─ Best RMSE: 30.0884

Loaded model for scenario 'freeze_fc1_fc2'
  └─ Best fold checkpoint: /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/TL_Ro5/freeze_fc1_fc2/final_fold_models/fold_9_best.pth
  └─ Best RMSE: 33.3732

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_37957/1213320820.py:31: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(ckpt_path, map_location="cpu")
/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_37957/1213320820.py:31: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(ckpt_path, map_location="cpu")
/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_37957/1213320820.py:31: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  state = torch.load(ckpt_path, map_location="cpu")

In [12]:
import pandas as pd
from pathlib import Path

def print_rmse_all_folds(
    root_dir="artifacts/TL_Ro5",
    scenarios=("no_freeze", "freeze_fc1", "freeze_fc1_fc2"),
):
    root_dir = Path(root_dir)

    for tag in scenarios:
        cv_metrics_path = root_dir / tag / "cv_final_metrics.csv"

        if not cv_metrics_path.exists():
            print(f"[WARN] Missing CV metrics for scenario '{tag}'")
            continue

        cv_df = pd.read_csv(cv_metrics_path)

        print(f"\nScenario: {tag}")
        print("-" * (10 + len(tag)))

        # Expecting columns like: fold, rmse, r2, q2, checkpoint, ...
        for _, row in cv_df.iterrows():
            fold = row.get("fold", "N/A")
            rmse = row["rmse"]
            print(f"  Fold {fold}: RMSE = {rmse:.4f}")

        print(f"  Mean RMSE: {cv_df['rmse'].mean():.4f}")
        print(f"  Std  RMSE: {cv_df['rmse'].std():.4f}")

# Run it
print_rmse_all_folds(
    root_dir="artifacts/TL_Ro5",
    scenarios=["no_freeze", "freeze_fc1", "freeze_fc1_fc2"]
)

Scenario: no_freeze
-------------------
  Fold 9: RMSE = 27.7796
  Fold 8: RMSE = 35.7503
  Fold 1: RMSE = 35.8358
  Fold 7: RMSE = 39.3880
  Fold 2: RMSE = 40.2949
  Fold 3: RMSE = 41.6339
  Fold 5: RMSE = 41.6666
  Fold 0: RMSE = 46.4810
  Fold 4: RMSE = 51.1832
  Fold 6: RMSE = 61.2382
  Mean RMSE: 42.1252
  Std  RMSE: 9.2112

Scenario: freeze_fc1
--------------------
  Fold 9: RMSE = 30.0884
  Fold 7: RMSE = 38.2062
  Fold 1: RMSE = 41.0129
  Fold 8: RMSE = 42.7353
  Fold 5: RMSE = 43.3871
  Fold 2: RMSE = 44.6962
  Fold 3: RMSE = 47.0674
  Fold 0: RMSE = 48.5614
  Fold 4: RMSE = 49.7274
  Fold 6: RMSE = 58.8862
  Mean RMSE: 44.4369
  Std  RMSE: 7.6099

Scenario: freeze_fc1_fc2
------------------------
  Fold 9: RMSE = 33.3732
  Fold 8: RMSE = 39.8710
  Fold 7: RMSE = 40.8214
  Fold 2: RMSE = 41.1697
  Fold 1: RMSE = 47.4890
  Fold 5: RMSE = 50.6710
  Fold 3: RMSE = 50.8095
  Fold 0: RMSE = 52.1373
  Fold 4: RMSE = 53.7067
  Fold 6: RMSE = 55.7774
  Mean RMSE: 46.5826
  Std  RMSE: 7.3302

In [14]:
import sys
# classifier/ → MELTING_POINT_2026/
PROJECT_ROOT = Path.cwd().parent        # directory above a path: .../MELTING_POINT_2026

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

test_path = PROJECT_ROOT / "Ro5" / "artifacts" / "df_test_scaled.parquet"
df_test = pd.read_parquet(test_path)

df_test.head()

,SMILES,MP,Type,Ro5,RDKit_PEOE_VSA3,RDKit_NumAliphaticRings X RDKit_SlogP_VSA8,RDKit_NHOHCount,RDKit_SMR_VSA10 X RDKit_VSA_EState6,MACCS_105 X RDKit_NHOHCount,MACCS_105 X RDKit_fr_Ar_COO,...,MACCS_161,RDKit_NHOHCount X RDKit_SlogP_VSA8,RDKit_BertzCT X RDKit_RingCount,RDKit_fr_ArN,RDKit_SMR_VSA5,MACCS_126 X RDKit_NumHDonors,RDKit_MaxAbsPartialCharge,MACCS_155 X RDKit_fr_Ar_OH,RDKit_Chi3n X RDKit_NumRotatableBonds,RDKit_SlogP_VSA2
0,[O-][N+](=O)c1c(C)c(C(=O)C)c(c(c1C(C)(C)C)[N+]...,135.5,Test,1,-0.651134,-0.195586,-0.839721,-0.618301,-0.350082,-0.077211,...,0.821926,-0.258763,-0.385976,-0.268728,0.998128,-0.316404,-0.871431,-0.145223,-0.020079,-0.165679
1,CN(NC(=O)CCC(=O)O)C,154.5,Test,1,0.432729,-0.195586,0.694148,-0.618301,-0.350082,-0.077211,...,0.821926,-0.258763,-0.775069,-0.268728,-0.226208,-0.316404,0.764344,-0.145223,-0.315950,1.029142
2,CCCCc1ccc(cc1)NC(=O)Oc1ccc(cc1)OC,143.0,Test,1,0.386341,-0.195586,-0.072787,0.145154,-0.350082,-0.077211,...,0.821926,-0.258763,-0.027957,-0.268728,0.252697,1.006958,0.900505,-0.145223,0.410717,-0.307419
3,OC(=O)COCCN1C(=O)c2c(C1=O)cccc2,128.0,Test,1,0.386341,-0.195586,-0.072787,-0.103564,0.862879,-0.077211,...,0.821926,-0.258763,-0.173134,-0.268728,-0.687065,1.006958,0.749574,-0.145223,0.097925,1.698546
4,CCCCCCCCCCCCCCC,10.0,Test,1,-0.651134,-0.195586,-0.839721,-0.618301,-0.350082,-0.077211,...,-1.216654,-0.258763,-0.775069,-0.268728,2.805458,-0.316404,-2.878269,-0.145223,1.258066,-1.078546

In [15]:
from pathlib import Path
import numpy as np
import pandas as pd
import torch
import joblib

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from NN_model import ImprovedNN  # adjust if needed

# --------------------
# PATHS
# --------------------
BASE = Path.cwd()  # wherever your notebook is running
CKPT_PTH = BASE / "artifacts/TL_Ro5/no_freeze/final_fold_models/fold_9_best.pth"

TEST_SCALED = BASE / "artifacts/df_test_scaled.parquet"   # <-- adjust to your actual location
OUT_PRED_CSV = BASE / "artifacts/test_TL_Ro5_predictions.csv"

# --------------------
# MODEL PARAMETERS (must match checkpoint architecture)
# --------------------
HIDDEN_LAYERS = [224, 112, 56]
DROPOUT_RATE = 0.31955324794371087  # must match best params used for that checkpoint

# --------------------
# Load scaled test set
# --------------------
df_test = pd.read_parquet(TEST_SCALED)

NON_FEATURES = ["SMILES", "MP", "Type", "Ro5"]
feature_cols = [c for c in df_test.columns if c not in NON_FEATURES]
feature_cols = [c for c in feature_cols if pd.api.types.is_numeric_dtype(df_test[c])]

# Optional: enforce deterministic order (better: load exact feature list from training manifest)
feature_cols = sorted(feature_cols)

X_test = df_test[feature_cols].to_numpy(dtype=np.float32)
y_true = df_test["MP"].to_numpy(dtype=float)
smiles = df_test["SMILES"].astype(str).to_numpy()

print("Test rows:", len(df_test))
print("Features:", X_test.shape[1])

# --------------------
# Recreate model + load checkpoint
# --------------------
device = torch.device("cpu")

model = ImprovedNN(
    input_size=X_test.shape[1],
    hidden_layers=HIDDEN_LAYERS,
    dropout_rate=DROPOUT_RATE
).to(device)

loaded = torch.load(CKPT_PTH, map_location=device)

if isinstance(loaded, dict) and "model_state_dict" in loaded:
    model.load_state_dict(loaded["model_state_dict"], strict=True)
else:
    model.load_state_dict(loaded, strict=True)

model.eval()

# --------------------
# Predict
# --------------------
X_tensor = torch.tensor(X_test, dtype=torch.float32, device=device)

with torch.no_grad():
    y_pred = model(X_tensor).squeeze().cpu().numpy().astype(float)

# --------------------
# Evaluate
# --------------------
rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
mae  = float(mean_absolute_error(y_true, y_pred))
r2   = float(r2_score(y_true, y_pred))

print("\n=== TEST METRICS ===")
print(f"RMSE: {rmse:.4f}")
print(f"MAE : {mae:.4f}")
print(f"R^2 : {r2:.4f}")

# --------------------
# Save predictions
# --------------------
out_df = pd.DataFrame({
    "SMILES": smiles,
    "exp MP": y_true,
    "pred MP": y_pred,
    "error": y_pred - y_true,
    "abs_error": np.abs(y_pred - y_true),
})

OUT_PRED_CSV.parent.mkdir(parents=True, exist_ok=True)
out_df.to_csv(OUT_PRED_CSV, index=False)
print(f"\nSaved predictions -> {OUT_PRED_CSV}")

Test rows: 5166
Features: 118

=== TEST METRICS ===
RMSE: 73.2610
MAE : 59.8750
R^2 : -0.0591

Saved predictions -> /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/test_TL_Ro5_predictions.csv

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_37957/1242408231.py:55: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded = torch.load(CKPT_PTH, map_location=device)

In [19]:

from pathlib import Path
import numpy as np
import pandas as pd
import torch
import joblib

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from NN_model import ImprovedNN  # adjust if needed

# --------------------
# PATHS
# --------------------
BASE = Path.cwd()  # wherever your notebook is running
CKPT_PTH = BASE / "artifacts/TL_Ro5/freeze_fc1/final_fold_models/fold_9_best.pth"

TEST_SCALED = BASE / "artifacts/df_test_scaled.parquet"   # <-- adjust to your actual location
OUT_PRED_CSV = BASE / "artifacts/test_TL_Ro5_freeze_fc1_predictions.csv"

# --------------------
# MODEL PARAMETERS (must match checkpoint architecture)
# --------------------
HIDDEN_LAYERS = [224, 112, 56]
DROPOUT_RATE = 0.31955324794371087  # must match best params used for that checkpoint

# --------------------
# Load scaled test set
# --------------------
df_test = pd.read_parquet(TEST_SCALED)

NON_FEATURES = ["SMILES", "MP", "Type", "Ro5"]
feature_cols = [c for c in df_test.columns if c not in NON_FEATURES]
feature_cols = [c for c in feature_cols if pd.api.types.is_numeric_dtype(df_test[c])]

# Optional: enforce deterministic order (better: load exact feature list from training manifest)
feature_cols = sorted(feature_cols)

X_test = df_test[feature_cols].to_numpy(dtype=np.float32)
y_true = df_test["MP"].to_numpy(dtype=float)
smiles = df_test["SMILES"].astype(str).to_numpy()

print("Test rows:", len(df_test))
print("Features:", X_test.shape[1])

# --------------------
# Recreate model + load checkpoint
# --------------------
device = torch.device("cpu")

model = ImprovedNN(
    input_size=X_test.shape[1],
    hidden_layers=HIDDEN_LAYERS,
    dropout_rate=DROPOUT_RATE
).to(device)

loaded = torch.load(CKPT_PTH, map_location=device)

if isinstance(loaded, dict) and "model_state_dict" in loaded:
    model.load_state_dict(loaded["model_state_dict"], strict=True)
else:
    model.load_state_dict(loaded, strict=True)

model.eval()

# --------------------
# Predict
# --------------------
X_tensor = torch.tensor(X_test, dtype=torch.float32, device=device)

with torch.no_grad():
    y_pred = model(X_tensor).squeeze().cpu().numpy().astype(float)

# --------------------
# Evaluate
# --------------------
rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
mae  = float(mean_absolute_error(y_true, y_pred))
r2   = float(r2_score(y_true, y_pred))

print("\n=== TEST METRICS ===")
print(f"RMSE: {rmse:.4f}")
print(f"MAE : {mae:.4f}")
print(f"R^2 : {r2:.4f}")

# --------------------
# Save predictions
# --------------------
out_df = pd.DataFrame({
    "SMILES": smiles,
    "exp MP": y_true,
    "pred MP": y_pred,
    "error": y_pred - y_true,
    "abs_error": np.abs(y_pred - y_true),
})

OUT_PRED_CSV.parent.mkdir(parents=True, exist_ok=True)
out_df.to_csv(OUT_PRED_CSV, index=False)
print(f"\nSaved predictions -> {OUT_PRED_CSV}")

Test rows: 5166
Features: 118

=== TEST METRICS ===
RMSE: 73.9640
MAE : 60.2683
R^2 : -0.0796

Saved predictions -> /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/test_TL_Ro5_freeze_fc1_predictions.csv

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_37957/677483318.py:55: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded = torch.load(CKPT_PTH, map_location=device)

In [21]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error

PRED_CSV = "artifacts/test_TL_Ro5_freeze_fc1_predictions.csv"

df = pd.read_csv(PRED_CSV)

MP_THRESHOLD = 250.0   # <-- example, change if needed

df_low  = df[df["exp MP"] < MP_THRESHOLD]
df_high = df[df["exp MP"] >= MP_THRESHOLD]

print("Low MP samples :", len(df_low))
print("High MP samples:", len(df_high))

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


rmse_low = rmse(df_low["exp MP"], df_low["pred MP"])
rmse_high = rmse(df_high["exp MP"], df_high["pred MP"])
rmse_all = rmse(df["exp MP"], df["pred MP"])

print("\n=== RMSE by group ===")
print(f"Overall RMSE : {rmse_all:.4f}")
print(f"Low MP RMSE  : {rmse_low:.4f}")
print(f"High MP RMSE : {rmse_high:.4f}")

Low MP samples : 4894
High MP samples: 272

=== RMSE by group ===
Overall RMSE : 73.9640
Low MP RMSE  : 69.1632
High MP RMSE : 133.5436

In [22]:

from pathlib import Path
import numpy as np
import pandas as pd
import torch
import joblib

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from NN_model import ImprovedNN  # adjust if needed

# --------------------
# PATHS
# --------------------
BASE = Path.cwd()  # wherever your notebook is running
CKPT_PTH = BASE / "artifacts/TL_Ro5/freeze_fc1_fc2/final_fold_models/fold_9_best.pth"

TEST_SCALED = BASE / "artifacts/df_test_scaled.parquet"   # <-- adjust to your actual location
OUT_PRED_CSV = BASE / "artifacts/test_TL_Ro5_freeze_fc1_fc2_predictions.csv"

# --------------------
# MODEL PARAMETERS (must match checkpoint architecture)
# --------------------
HIDDEN_LAYERS = [224, 112, 56]
DROPOUT_RATE = 0.31955324794371087  # must match best params used for that checkpoint

# --------------------
# Load scaled test set
# --------------------
df_test = pd.read_parquet(TEST_SCALED)

NON_FEATURES = ["SMILES", "MP", "Type", "Ro5"]
feature_cols = [c for c in df_test.columns if c not in NON_FEATURES]
feature_cols = [c for c in feature_cols if pd.api.types.is_numeric_dtype(df_test[c])]

# Optional: enforce deterministic order (better: load exact feature list from training manifest)
feature_cols = sorted(feature_cols)

X_test = df_test[feature_cols].to_numpy(dtype=np.float32)
y_true = df_test["MP"].to_numpy(dtype=float)
smiles = df_test["SMILES"].astype(str).to_numpy()

print("Test rows:", len(df_test))
print("Features:", X_test.shape[1])

# --------------------
# Recreate model + load checkpoint
# --------------------
device = torch.device("cpu")

model = ImprovedNN(
    input_size=X_test.shape[1],
    hidden_layers=HIDDEN_LAYERS,
    dropout_rate=DROPOUT_RATE
).to(device)

loaded = torch.load(CKPT_PTH, map_location=device)

if isinstance(loaded, dict) and "model_state_dict" in loaded:
    model.load_state_dict(loaded["model_state_dict"], strict=True)
else:
    model.load_state_dict(loaded, strict=True)

model.eval()

# --------------------
# Predict
# --------------------
X_tensor = torch.tensor(X_test, dtype=torch.float32, device=device)

with torch.no_grad():
    y_pred = model(X_tensor).squeeze().cpu().numpy().astype(float)

# --------------------
# Evaluate
# --------------------
rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
mae  = float(mean_absolute_error(y_true, y_pred))
r2   = float(r2_score(y_true, y_pred))

print("\n=== TEST METRICS ===")
print(f"RMSE: {rmse:.4f}")
print(f"MAE : {mae:.4f}")
print(f"R^2 : {r2:.4f}")

# --------------------
# Save predictions
# --------------------
out_df = pd.DataFrame({
    "SMILES": smiles,
    "exp MP": y_true,
    "pred MP": y_pred,
    "error": y_pred - y_true,
    "abs_error": np.abs(y_pred - y_true),
})

OUT_PRED_CSV.parent.mkdir(parents=True, exist_ok=True)
out_df.to_csv(OUT_PRED_CSV, index=False)
print(f"\nSaved predictions -> {OUT_PRED_CSV}")

Test rows: 5166
Features: 118

=== TEST METRICS ===
RMSE: 75.4103
MAE : 61.3265
R^2 : -0.1222

Saved predictions -> /Users/sdl5_mp/Documents/GitHub/melting_point_2026/Ro5/artifacts/test_TL_Ro5_freeze_fc1_fc2_predictions.csv

/var/folders/4j/q1b8spls57ldz2j3g8k6nxh40000gn/T/ipykernel_37957/3236927072.py:55: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  loaded = torch.load(CKPT_PTH, map_location=device)

In [23]:
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error

PRED_CSV = "artifacts/test_TL_Ro5_freeze_fc1_fc2_predictions.csv"

df = pd.read_csv(PRED_CSV)

MP_THRESHOLD = 250.0   # <-- example, change if needed

df_low  = df[df["exp MP"] < MP_THRESHOLD]
df_high = df[df["exp MP"] >= MP_THRESHOLD]

print("Low MP samples :", len(df_low))
print("High MP samples:", len(df_high))

def rmse(y_true, y_pred):
    return np.sqrt(mean_squared_error(y_true, y_pred))


rmse_low = rmse(df_low["exp MP"], df_low["pred MP"])
rmse_high = rmse(df_high["exp MP"], df_high["pred MP"])
rmse_all = rmse(df["exp MP"], df["pred MP"])

print("\n=== RMSE by group ===")
print(f"Overall RMSE : {rmse_all:.4f}")
print(f"Low MP RMSE  : {rmse_low:.4f}")
print(f"High MP RMSE : {rmse_high:.4f}")

Low MP samples : 4894
High MP samples: 272

=== RMSE by group ===
Overall RMSE : 75.4103
Low MP RMSE  : 70.9051
High MP RMSE : 132.4653